Bottom Class Reference
#include <bottom.h>
Public Member Functions
Bottom ()
Bottom (float astartTime, float aDuration, int aType, char *aName)
Bottom (const Bottom &origBottom)
~Bottom ()
Bottom & operator= (const Bottom &origBottom)
void clear ()
void setName (char *aName)
virtual void setStartTime (float aStartTime)
virtual void setDuration (float aDuration)
void setDensity (double aDensity)
void setNumPartials (int aNumPartials)
void CreateNewObjects ()
void Implement ()
void buildSound (Score *score)
float AssignFreq (double checkPoint)
int NumPart (float freq)
int Spectrum (Sound *s, float freq)
void CreatePartials (Sound *s, int numPartials)
void SetFrequency (Sound *s, float deviation, float baseFreq, int numPartials)
void OneStep (Sound *s, double checkPoint, int numPartials)
void ThreeStep (Sound *s, double checkPoint, int numPartials)
void Rules (int numPartials, float ampScale[])
float Loud (Sound *s, double checkPoint)
void Modifiers (Sound *s, int numPartials, double checkPoint)
void ChooseSoundDynParam (Sound *s, const char *modifier, Envelope *env)
void ChoosePartialDynParam (Sound *s, const char *modifier, Envelope *env, int i)
void Spatialization (Sound *s, double checkPoint)
void Spatialization (Sound *s, double checkPoint, string method, Envelope *chance, Envelope *pan)
void Reverberation (Sound *s, double checkPoint)
void Reverberation (Sound *s, double checkPoint, string method, Envelope *chance, float roomSize)
void Print ()
void PrintSound (int numPartials, float freq, float sones)
virtual void buildNote ()
Public Attributes
FileValue * bottom_newObjectMethod
FileValue * bottom_slope
FileValue * bottom_freqMethod
FileValue * bottom_freqMethod2
FileValue * bottom_absRange
FileValue * bottom_patFile
FileValue * bottom_fundamental
FileValue * bottom_soundMethod
FileValue * bottom_envMethod
FileValue * bottom_ampMethod
FileValue * bottom_rule
FileValue * bottom_randFlag
FileValue * bottom_ampScale
FileValue * bottom_factor
FileValue * bottom_attenuation
FileValue * bottom_modifier
FileValue * bottom_select
FileValue * bottom_spatMethod
FileValue * bottom_reverbMethod
Protected Attributes
char * bottomName
float bottomStartTime
float bottomDuration
int bottomType
int bottomNumPartials
Private Attributes
double bottomDensity
Detailed Description
This class is used to store and manage the details of a bottom event.
Definition at line 50 of file bottom.h.
Constructor & Destructor Documentation
Bottom::Bottom () [inline]
Definition at line 63 of file bottom.h.
Bottom::Bottom (float astartTime, float aDuration, int aType, char * aName)
This is a constructor.
Parameters:
astartTime The start time of the event
aDuration The duration of the event
aType The type of the event
aName A name for the event
Returns: A Bottom object
Definition at line 39 of file bottom.cpp.
References Event::aName, bottomID, bottomType, setDensity(), setDuration(), setName(), and setStartTime().
Bottom::Bottom (const Bottom & origBottom)
This is the copy constructor.
Parameters:
origBottom The Bottom to copy
Returns: A copy of origBottom
Definition at line 56 of file bottom.cpp.
References bottomID.
Bottom::~Bottom ()
This is the destructor.
Definition at line 65 of file bottom.cpp.
Member Function Documentation
float Bottom::AssignFreq (double checkPoint)
This function contains three methods to determine the frequency: FUNDAMENTAL: assumes that each frequency is an `overtone` of a common fundamental, the total duration of the piece WELL_TEMPERED: produces frequencies corresponding to the well-temperate tuning with C0=16.35Hz, the lowest possible frequency CONTINUUM: uses a distribution within a give range
FUNDAMENTAL and WELL_TEMPERED also use a second method selected from: SIEVE: uses a given sieve SEQUENCE: reproduces an ordered sequence of values. The location in the array (offset) can be determined by either the type or the number of the object.
Parameters:
checkPoint
Returns: the frequency determined
void Bottom::buildNote () [virtual]
Reimplemented from Event (p.).
Definition at line 1046 of file bottom.cpp.
References Note::Activate(), Event::barLen, bottomStartTime, Event::buildNote(), Event::checkPoint, Event::durSec, Event::newObj, Event::note_dynamicMark, Event::note_modifiers, Event::note_pitchClass, Note::Print(), Event::stimeSec, Event::type, and Event::uPerSec.
void Bottom::buildSound (Score * score)
buildSound. Creates Sound(s) for the event and its children and adds the Sound(s) to the Score.
Definition at line 889 of file bottom.cpp.
References CEILING, Event::checkPoint, ChoosePartialDynParam(), ChooseSoundDynParam(), Event::durSec, FileValue::Evaluate(), FileValue::getList(), FileValue::getListPtr(), MINFREQ, Random::Rand(), Reverberation(), score, Event::sound_reverberation, Event::sound_spatialization, Spatialization(), and Event::stimeSec.
Referenced by Event::BuildSubEvents().
void Bottom::ChoosePartialDynParam (Sound * s, const char * modifier, Envelope * env, int i)
FUNCTION: choosepartialdynparam INPUTS: Pointer to a sound Pointer to a const char containing the modifier information Pointer to an envelope Integer i representing the ith partial of a sound s
DESCRIPTION: This function sets the partial parameter specified in the modifier variable to what is contained in the envelope for a given partial of a sound s.
Definition at line 672 of file bottom.cpp.
Referenced by buildSound(), and Modifiers().
void Bottom::ChooseSoundDynParam (Sound * s, const char * modifier, Envelope * env)
FUNCTION: choosesounddynparam INPUTS: Pointer to a sound Pointer to a const char containing the modifier information Pointer to an envelope
DESCRIPTION: This function sets the partial parameter specified in the modifier variable to what is contained in the envelope for a given sound s.
Definition at line 622 of file bottom.cpp.
References Event::checkPoint.
Referenced by buildSound(), and Modifiers().
void Bottom::clear () [virtual]
This function clears values of the Bottom object and to clear dynamic memory.
Reimplemented from Event (p.).
Reimplemented in Note (p.).
Definition at line 78 of file bottom.cpp.
References bottom_absRange, bottom_ampMethod, bottom_ampScale, bottom_attenuation, bottom_envMethod, bottom_factor, bottom_freqMethod, bottom_freqMethod2, bottom_fundamental, bottom_modifier, bottom_newObjectMethod, bottom_patFile, bottom_randFlag, bottom_reverbMethod, bottom_rule, bottom_select, bottom_slope, bottom_soundMethod, bottom_spatMethod, Event::durArray, Event::layerDens, Event::maxTypes, Event::nameType, Event::objsInLayer, Event::probDurArray, Event::probSieveArray, Event::remainObjs, Event::starTarray, Event::TestNameType(), Event::theName, and Event::typesInLayer.
void Bottom::CreateNewObjects ()
This function uses a variety of methods to create new objects for the Bottom event.
Reimplemented from Event (p.).
void Bottom::CreatePartials (Sound * s, int numPartials)
This function employs the LASS Partial class constructor and setParam function.
Parameters:
s A sound
numPartials The number of partials
Definition at line 265 of file bottom.cpp.
Referenced by Spectrum().
void Bottom::Implement ()
This function chooses to implement a sound, a note, or a visual according to the type of output and the file used.
float Bottom::Loud (Sound * s, double checkPoint)
This function calculates the loudness of the given sound.
Parameters:
s A sound
checkPoint
Returns: The loudness of the sound
Definition at line 493 of file bottom.cpp.
References Event::bottom_loudness, FileValue::Evaluate(), and FileValue::getNumber().
void Bottom::Modifiers (Sound * s, int numPartials, double checkPoint)
THIS FUNCTION NEEDS TO BE CONVERTED TO THE NEW CODE FUNCTION: modifiers INPUT: a pointer to a sound an integer containing the number of partials a double checkpoint
DESCRIPTION:
Definition at line 524 of file bottom.cpp.
References bottom_modifier, bottom_select, Chance(), ChoosePartialDynParam(), ChooseSoundDynParam(), EnvelopeBuilder(), envlib, FileValue::getListPtr(), FileValue::getString(), and ReadComputeInt().
int Bottom::NumPart (float freq)
This function determines how many partials a sound has by receiving the number of partials and then checking if any partial has a frequency higher than CEILING and discards those who have.
Parameters:
freq
numPartials
Returns: the number of partials a sound has
Definition at line 201 of file bottom.cpp.
References CEILING, FileValue::getNumber(), sever, and Event::sound_numPartials.
Referenced by Spectrum().
void Bottom::OneStep (Sound * s, double checkPoint, int numPartials)
This function chooses an envelope for each partial and assigns it.
Parameters:
s A sound
checkPoint
numPartials The number of partials
soundFile
Definition at line 330 of file bottom.cpp.
References ChooseOffset(), EnvelopeBuilder(), Event::newObj, and Event::type.
Referenced by Spectrum().
Bottom& Bottom::operator= (const Bottom & origBottom)
This is an operator overload to define '=' as a call to the copy constructor.
Parameters:
origBottom The Bottom to copy
Returns: A copy of origBottom
void Bottom::Print () [virtual]
FUNCTION: public: print
DESCRIPTION: Prints bottom id, name, start time and duration to outputfile
Reimplemented from Event (p.).
Definition at line 848 of file bottom.cpp.
References bottomID, outputFile, Event::theDuration, Event::theName, Event::theStartTime, and Event::uPerSec.
Referenced by Note::Activate().
void Bottom::PrintSound (int numPartials, float freq, float sones)
FUNCTION: printsound INPUT: Integer containing the number of partials Float containing the freq value Float containing the sones value
DESCRIPTION: Prints the sound id, start time, duration, type, freq, and sones of a sound
Definition at line 871 of file bottom.cpp.
References Event::durSec, Event::objID, outputFile, Event::stimeSec, and Event::type.
void Bottom::Reverberation (Sound * s, double checkPoint, string method, Envelope * chance, float roomSize)
THIS FUNCTION IS OLD AND NEEDS TO BE UPDATED TO THE NEW CODE FUNCTION: reverberation INPUT: Pointer to a sound Double checkpoint String contain `room_size`, `custom`, or `single_partial` Pointer to an envelope Float roomsize
DESCRIPTION: Uses chance function and method to randomly create the reverberation for a sound
Definition at line 779 of file bottom.cpp.
References bottom_reverbMethod, Chance(), and FileValue::getString().
void Bottom::Reverberation (Sound * s, double checkPoint)
Referenced by buildSound().
void Bottom::Rules (int numPartials, float ampScale[])
NOT DEFINED YET
Parameters:
numPartials The number of partials
ampScale
Definition at line 439 of file bottom.cpp.
References bottom_ampScale, bottom_attenuation, bottom_factor, bottom_randFlag, bottom_rule, Exponential(), FileValue::getNumber(), FileValue::getString(), Random::Rand(), Random::RAND_SIGN, and sever.
Referenced by ThreeStep().
void Bottom::setDensity (double aDensity) [virtual]
This function sets the density of the Bottom event.
Parameters:
aDensity The amount to set the density to
Reimplemented from Event (p.).
Definition at line 175 of file bottom.cpp.
References bottomDensity.
Referenced by Bottom().
void Bottom::setDuration (float aDuration) [virtual]
This function sets the duration of the Bottom event.
Parameters:
aDuration The amount to set the duration to
Reimplemented from Event (p.).
Definition at line 166 of file bottom.cpp.
References bottomDuration.
Referenced by Bottom().
void Bottom::SetFrequency (Sound * s, float deviation, float baseFreq, int numPartials)
This function assigns a frequency to each partial according to baseFreq and the deviation (which is randomly selected as positive or negative). Individual frequencies are checked against the MINFREQ and CEILING (see define.h(p.)) and set (applied to the sound object) with setParam (LASS).
Parameters:
s A sound
deviation The deviation
baseFreq The base frequency
numPartials The number of partials
Definition at line 291 of file bottom.cpp.
References CEILING, MINFREQ, and Random::Rand().
Referenced by Spectrum().
void Bottom::setName (char * aName) [virtual]
This function sets the name of the Bottom event.
Parameters:
aName The name to set the bottom event to
Reimplemented from Event (p.).
Definition at line 142 of file bottom.cpp.
References bottomName.
Referenced by Bottom().
void Bottom::setNumPartials (int aNumPartials)
This function sets the number of partials of the Bottom Event(p.)
Parameters:
aNumPartials The numbers of partials
void Bottom::setStartTime (float aStartTime) [virtual]
This function sets the start time of the Bottom event.
Parameters:
aStartTime The time to set the start time to
Reimplemented from Event (p.).
Definition at line 157 of file bottom.cpp.
References bottomStartTime.
Referenced by Bottom().
void Bottom::Spatialization (Sound * s, double checkPoint, string method, Envelope * chance, Envelope * pan)
NOTE: multi_pan is unfinished. Think function is in process of being updated? FUNCTION: spatialization INPUT: Pointer to a sound Double checkpoint String containing the method Pointer to an envelope for chance Pointer to an envelope for pan
DESCRIPTION: Sets the spatialization of a sound according to method and random chance
Definition at line 727 of file bottom.cpp.
References Chance(), Event::numObjs, and sever.
void Bottom::Spatialization (Sound * s, double checkPoint)
Referenced by buildSound().
int Bottom::Spectrum (Sound * s, float freq)
NOT YET DEFINED
Parameters:
s A sound
freq
Definition at line 230 of file bottom.cpp.
References bottom_soundMethod, Event::checkPoint, CreatePartials(), FileValue::getNumber(), FileValue::getString(), NumPart(), OneStep(), SetFrequency(), sever, Event::sound_deviation, and ThreeStep().
void Bottom::ThreeStep (Sound * s, double checkPoint, int numPartials)
NOT DEFINED YET
Parameters:
s A sound
checkPoint
numPartials The number of partials
Definition at line 362 of file bottom.cpp.
References bottom_absRange, bottom_ampMethod, bottom_ampScale, bottom_envMethod, envlib, FileValue::getList(), FileValue::getNumber(), FileValue::getString(), Rules(), Sequence(), sever, and ValuePick().
Referenced by Spectrum().
Member Data Documentation
FileValue* Bottom::bottom_absRange
Definition at line 302 of file bottom.h.
Referenced by clear(), and ThreeStep().
FileValue* Bottom::bottom_ampMethod
Definition at line 307 of file bottom.h.
Referenced by clear(), and ThreeStep().
FileValue* Bottom::bottom_ampScale
Definition at line 310 of file bottom.h.
Referenced by clear(), Rules(), and ThreeStep().
FileValue* Bottom::bottom_attenuation
Definition at line 312 of file bottom.h.
Referenced by clear(), and Rules().
FileValue* Bottom::bottom_envMethod
Definition at line 306 of file bottom.h.
Referenced by clear(), and ThreeStep().
FileValue* Bottom::bottom_factor
Definition at line 311 of file bottom.h.
Referenced by clear(), and Rules().
FileValue* Bottom::bottom_freqMethod
Definition at line 300 of file bottom.h.
Referenced by clear().
FileValue* Bottom::bottom_freqMethod2
Definition at line 301 of file bottom.h.
Referenced by clear().
FileValue* Bottom::bottom_fundamental
Definition at line 304 of file bottom.h.
Referenced by clear().
FileValue* Bottom::bottom_modifier
Definition at line 313 of file bottom.h.
Referenced by clear(), and Modifiers().
FileValue* Bottom::bottom_newObjectMethod
Definition at line 298 of file bottom.h.
Referenced by clear().
FileValue* Bottom::bottom_patFile
Definition at line 303 of file bottom.h.
Referenced by clear().
FileValue* Bottom::bottom_randFlag
Definition at line 309 of file bottom.h.
Referenced by clear(), and Rules().
FileValue* Bottom::bottom_reverbMethod
Definition at line 316 of file bottom.h.
Referenced by clear(), and Reverberation().
FileValue* Bottom::bottom_rule
Definition at line 308 of file bottom.h.
Referenced by clear(), and Rules().
FileValue* Bottom::bottom_select
Definition at line 314 of file bottom.h.
Referenced by clear(), and Modifiers().
FileValue* Bottom::bottom_slope
Definition at line 299 of file bottom.h.
Referenced by clear().
FileValue* Bottom::bottom_soundMethod
Definition at line 305 of file bottom.h.
Referenced by clear(), and Spectrum().
FileValue* Bottom::bottom_spatMethod
Definition at line 315 of file bottom.h.
Referenced by clear().
double Bottom::bottomDensity [private]
This is a double to hold the density
Definition at line 56 of file bottom.h.
Referenced by setDensity().
float Bottom::bottomDuration [protected]
Definition at line 336 of file bottom.h.
Referenced by setDuration().
char* Bottom::bottomName [protected]
Definition at line 326 of file bottom.h.
Referenced by setName().
int Bottom::bottomNumPartials [protected]
Definition at line 346 of file bottom.h.
float Bottom::bottomStartTime [protected]
Definition at line 331 of file bottom.h.
Referenced by buildNote(), and setStartTime().
int Bottom::bottomType [protected]
Definition at line 341 of file bottom.h.
Referenced by Bottom().
The documentation for this class was generated from the following files:
bottom.h
bottom.cpp