Event Class Reference
#include <event.h>
Public Member Functions
Event ()
Event (char *aName)
Event (float aStartTime, float aDuration, int aType, char *aName)
Event (float aStartTime, float aDuration, double aDensity, int aType, char *aName)
Event (const Event &origEvent)
~Event ()
Event & operator= (const Event &origEvent)
virtual void setStartTime (float aStartTime)
virtual void setDuration (float aDuration)
virtual void setType (int aType)
virtual void setName (char *aName)
virtual void setDensity (double aDensity)
virtual void clear ()
float getStartTime ()
float getDuration ()
char * getName ()
double getDensity ()
int getType ()
int getNewObj ()
void Basics ()
void Build ()
void Build (list< FileValue > data)
void CreateNewObjects ()
void BuildSubEvents (map< string, EventFactory * > library, FileValue *Calculations)
void LayerDef ()
void NewLayerDef (list< FileValue > data)
void NumObjs ()
void NewNumObjs (list< FileValue > data)
void CopyName ()
void NewCopyName (list< FileValue > data)
void Continuum3 ()
void Discrete3 (int slope)
void Sweep3 ()
void AttackMethods ()
void NewAttackMethods (FileValue args)
void DurationMethods ()
void NewDurationMethods (FileValue args)
void Attacks ()
void Attacks (const char *eMethod, vector< int > eArgVector, const char *wMethod, vector< int > wArgVector)
void PointsProbs ()
void PointsProbs (const char *eMethod, vector< int > eArgVector, const char *wMethod, vector< int > wArgVector)
void GoldenMean ()
int Stimes ()
void Durations ()
void TimeConvert ()
void SelectNextEvent ()
void Parameters (int otherParams)
void setStartDurationType (list< FileValue > data)
void Continuum (list< FileValue > data)
void TestNameType ()
void CreateMatrices ()
void NewCreateMatrices (FileValue args)
void ObjCoordinates ()
virtual void buildScore (Score *s)
void Adjustments (int slope)
int FindDur (int remainO, float density)
int FindLen ()
virtual void Print ()
virtual void buildNote ()
double getCheckPoint ()
FileValue * getBottomFreq ()
void setBottomFreq (FileValue *s)
FileValue * getBottomLoud ()
void setBottomLoud (FileValue *s)
FileValue * getSoundNumPartials ()
void setSoundNumPartials (FileValue *s)
FileValue * getSoundDeviation ()
void setSoundDeviation (FileValue *s)
FileValue * getSoundPartEnvs ()
void setSoundPartEnvs (FileValue *s)
FileValue * getSoundModifiers ()
void setSoundModifiers (FileValue *s)
FileValue * getSoundReverberation ()
void setSoundReverberation (FileValue *s)
FileValue * getSoundSpatialization ()
void setSoundSpatialization (FileValue *s)
FileValue * getNotePitchClass ()
void setNotePitchClass (FileValue *s)
FileValue * getNoteDynamicMark ()
void setNoteDynamicMark (FileValue *s)
FileValue * getNoteModifiers ()
void setNoteModifiers (FileValue *s)
Public Attributes
double checkPoint
Matrix * s0
Matrix * d0
Matrix * s1
Matrix * d1
float theStartTime
float theDuration
int theType
char * theName
char * aName
char ** nameType
double theDensity
list< Event * > subevents
int numLayers
int objMaxDur
int uPerSec
int barLen
int maxTypes
int numChars
int levels
int length
int numObjs
int objID
int * typesInLayer
int noWeights
int arraySize
int listLen
int durLen
int * starTarray
int * durArray
double * probSieveArray
double * probDurArray
float * layerDens
int * objsInLayer
int * remainObjs
int durMatrix
int durUnits
int stimeMatrix
int stimeUnits
float durSec
float stimeSec
double duRatio
long loc0
long loc1
int newObj
int type
char * keepName
int layer
char * fname
int numParam
float * probParam
int ** dataParam
float ** coefParam
int ** sieveParam
int ** tempSieves
int ** maxLen
int * envParam
float * scaleParam
Protected Attributes
FileValue * bottom_frequency
FileValue * bottom_loudness
FileValue * sound_numPartials
FileValue * sound_deviation
FileValue * sound_partEnvs
FileValue * sound_modifiers
FileValue * sound_reverberation
FileValue * sound_spatialization
FileValue * note_pitchClass
FileValue * note_dynamicMark
FileValue * note_modifiers
float lastime
Friends
class Matrix
Constructor & Destructor Documentation
Event::Event () [inline]
Default constructor for an Event. It creates an Event object with no data.
Definition at line 55 of file event.h.
Referenced by Event().
Event::Event (char * aName)
Constructor for an Event. Empty event, generic; has only a name.
Parameters:
aName Name of the event
Definition at line 55 of file event.cpp.
References durArray, layerDens, nameType, objID, objsInLayer, probDurArray, probSieveArray, remainObjs, setName(), starTarray, and typesInLayer.
Event::Event (float aStartTime, float aDuration, int aType, char * aName)
Constructor for an Event. Includes basic information.
Parameters:
aStartTime Start Time of the event
aDuration Duration of the event
aType Type of the event
Name of the event
Definition at line 78 of file event.cpp.
References durArray, layerDens, nameType, objID, objsInLayer, probDurArray, probSieveArray, remainObjs, setDuration(), setName(), setStartTime(), setType(), starTarray, theDensity, and typesInLayer.
Event::Event (float aStartTime, float aDuration, double aDensity, int aType, char * aName)
Constructor for an Event. Includes basic information.
Parameters:
aStartTime Start Time of the event
aDuration Duration of the event
aDensity Density of the event
aType Type of the event
Name of the event
Definition at line 102 of file event.cpp.
References Event(), and theDensity.
Event::Event (const Event & origEvent)
This is the copy constructor.
Parameters:
origEvent Event object to make a copy of
Definition at line 113 of file event.cpp.
References theDensity, theDuration, theName, and theStartTime.
Event::~Event ()
This is the destructor.
Definition at line 137 of file event.cpp.
References clear().
Member Function Documentation
void Event::Adjustments (int slope)
Works only on the s0 (attacks/types matrix). Find the layer this objType belongs to. Determine the duration of this obj. Adjust the vector and matrix; get them ready for next choice. The sizes of stimeMatrix and durMatrix are measured in number of entries in the matrix while endUnitsM is measured in basic units (pulses, not seconds).
Parameters:
slope Slope value to pass to AdjustMatrix()
Definition at line 1151 of file event.cpp.
References Matrix::AdjustMatrix(), Matrix::AdjustVector(), FindDur(), layer, layerDens, newObj, numLayers, numObjs, remainObjs, s0, stimeMatrix, type, and typesInLayer.
Referenced by Discrete3().
void Event::AttackMethods ()
Choosing a method to determine attack times
Deprecated Use NewAttackMethods()(p.) with the new interface
void Event::Attacks (const char * eMethod, vector< int > eArgVector, const char * wMethod, vector< int > wArgVector)
Creates an array (sieve) with all possible attacks and another array with their probabilities.
Parameters:
eMethod e-Method for Sieve(p.)
eArgVector e-Vector for Sieve(p.)
wMethod w-Method for Sieve(p.)
wArgVector w-Vector for Sieve(p.)
Definition at line 889 of file event.cpp.
References arraySize, Sieve::Build(), Sieve::FillInArrays(), Sieve::GetListLen(), listLen, probSieveArray, starTarray, theDuration, and uPerSec.
void Event::Attacks ()
Creates an array (sieve) with all possible attacks and another array with their probabilities.
Deprecated Not in use (use Attacks(char*, vector<int>, char*, vector<int>) instead)
Referenced by NewAttackMethods().
void Event::Basics ()
Chooses the values needed for start time, type, and duration.
Deprecated
void Event::Build (list< FileValue > data)
Builds the event by calling a series of functions and determining: the number of streams/layers in this event; the number of objects in each layer; the names of the files describing the objects contained in this event.
Parameters:
data A list of file values to build the event.
Definition at line 380 of file event.cpp.
References NewCopyName(), NewLayerDef(), and NewNumObjs().
void Event::Build ()
Builds the event by calling a series of functions and determining: the number of streams/layers in this event; the number of objects in each layer; the names of the files describing the objects contained in this event.
Deprecated Use Build(list<FileValue> data)(p.) instead
void Event::buildNote () [virtual]
Reimplemented in Bottom (p.).
Definition at line 2038 of file event.cpp.
References Print(), and subevents.
Referenced by Bottom::buildNote(), and BuildSubEvents().
void Event::buildScore (Score * s) [virtual]
Definition at line 2028 of file event.cpp.
References subevents.
void Event::BuildSubEvents (map< string, EventFactory * > library, FileValue * Calculations)
BuildSubEvents. Taken from CreateNewObjects. Build sub-events from parsed information and information already set for this event. --- To be used with new interface.---
Parameters:
library XXXXXXXXXXXXXXXXXXX
Calculations YYYYYYYYYYYYY
Definition at line 1459 of file event.cpp.
References EventFactory::Build(), buildNote(), Bottom::buildSound(), checkPoint, Discrete3(), durSec, FileValue::Evaluate(), FileValue::getListPtr(), FileValue::getNumber(), FileValue::getString(), EventFactory::Inherit(), lastime, loc0, nameType, NewAttackMethods(), NewCreateMatrices(), NewDurationMethods(), newObj, numObjs, objID, score, sever, stimeSec, subevents, theDuration, theName, type, and uPerSec.
Referenced by EventFactory::Build().
void Event::clear () [virtual]
Clears several internal structures in the Event: nameType, maxTypes, layerDens, objsInLayer, remainObjs, typesInLayer, starTarray, probSieveArray, durArray, probDurArray
Reimplemented in Bottom (p.), High (p.), Low (p.), Note (p.), and Top (p.).
Definition at line 147 of file event.cpp.
References durArray, layerDens, maxTypes, nameType, objsInLayer, probDurArray, probSieveArray, remainObjs, starTarray, and typesInLayer.
Referenced by ~Event().
void Event::Continuum (list< FileValue > data)
Deprecated DO NOT USE
Definition at line 1723 of file event.cpp.
References checkPoint, durSec, objMaxDur, stimeSec, theDuration, type, and uPerSec.
void Event::Continuum3 ()
DEPRECATED
Continuum3. Method for assigning values for stimeSec, and duration using continuous (stochastic) distributions and for type - actually, a discrete value..
Definition at line 1691 of file event.cpp.
References checkPoint, ChooseOffset(), durSec, newObj, objMaxDur, Random::Rand(), ReadComputeFloat(), ReadComputeInt(), stimeSec, theDuration, type, and uPerSec.
void Event::CopyName ()
Reads the names of the files defining the elements of the next level and stores them in the two dimenssional character array NameType.
Deprecated Use NewCopyName instead
Definition at line 605 of file event.cpp.
References DataIn::intVect, maxTypes, DataIn::nameOf, nameType, numChars, DataIn::ReadChars(), DataIn::ReadDummies(), and DataIn::ReadInts().
void Event::CreateMatrices ()
Deprecated DO NOT USE: Use NewCreateMatrices()(p.) instead
void Event::CreateNewObjects ()
Contains a loop whthin which objects arec created one at a time. Each object has at least three parameters: start time, duration, and type. They are selected using one of the following methods: CONTINUUM for continuous probability, non-sequential order DISCRETE for discrete values, using a Matrix(p.) object, non-sequential SWEEP for reading values from a file provided by the user, sequential order
Deprecated Not currently in use (no replacement)
Reimplemented in Bottom (p.).
void Event::Discrete3 (int slope)
Sweep. Method for assigning stimeSec and durSec values in sequential order - `sweepeing` from left to right or beginning to end of the event. For stime and duration two different methods are used, one for integer values the other for float values. Type being a discrete value, the integer values method is used for it. ** For use with new interface **
Definition at line 1872 of file event.cpp.
References Adjustments(), ObjCoordinates(), and TimeConvert().
Referenced by BuildSubEvents().
void Event::DurationMethods ()
Choosing a method to determine durations.
Deprecated Use NewDurationMethods()(p.) with the new interface
Definition at line 749 of file event.cpp.
References List< Etype >::InsertInOrder(), DataIn::nameOf, PointsProbs(), DataIn::ReadChars(), DataIn::ReadDummies(), and sever.
void Event::Durations ()
Deprecated NOT IMPLEMENTED - DO NOT USE
int Event::FindDur (int remainO, float density)
Finds the available space (durLoc) in the matrix for the next duration (max lenght for the next dur starting at this stimeMatrix). Copies the original duration matrix and adjusts it; selects a duration for this obj type, at this stimeMatrix. stimeMatrix, durMatrix, and endLocM are expressed in matrix locations; endUnitsM is expressed in basic units (pulses). Units: theDuration - seconds endUnitsM, starTarray[stimeMatrix], durArray[location] - units (pulses) durLoc, listLen, durLen, stimeMatrix, durMatrix, starTarray, tryloc, durArray - array locations
Parameters:
remain0 ...
density ...
Definition at line 1213 of file event.cpp.
References Matrix::ChooseM(), d0, d1, durArray, durMatrix, FindLen(), listLen, Matrix, Matrix::Mult(), Matrix::Normalize(), Matrix::row, starTarray, stimeMatrix, Matrix::TrimMatrix(), and type.
Referenced by Adjustments().
int Event::FindLen ()
FindLen. Finds the matrix location where the event ends (endLocM). starTarray: array of possible start times (in units) stimeMatrix: a location in starTarray (locations) durArray: array of possible durations (in units) durLen: cardinal of durrArray (locations) durLoc: a location in durrArray (locations) theDuration: total duration of parent event (in seconds) uPerSec: number of units in a second endUnitsM: the end of the event (in units) testEnd: the end of the event (locations)
Definition at line 1266 of file event.cpp.
References durArray, durLen, listLen, Matrix::matrix, s0, starTarray, stimeMatrix, theDuration, type, and uPerSec.
Referenced by FindDur().
FileValue* Event::getBottomFreq () [inline]
Get bottom frequency
Returns: A FileValue(p.) * to the bottom frequency of the event
Definition at line 541 of file event.h.
References bottom_frequency.
Referenced by EventFactory::Inherit().
FileValue* Event::getBottomLoud () [inline]
Get bottom loudness
Returns: A FileValue(p.) * to the bottom loudness of the event
Definition at line 552 of file event.h.
References bottom_loudness.
Referenced by EventFactory::Inherit().
double Event::getCheckPoint () [inline]
Returns check point of the event
Returns: check point of the event as a double
Definition at line 514 of file event.h.
References checkPoint.
Referenced by FileValue::Evaluate().
double Event::getDensity ()
Returns the density of the Event
Returns: Density of the Event
Definition at line 313 of file event.cpp.
References theDensity.
float Event::getDuration ()
Returns the duration of the Event
Returns: Duration of the Event
Definition at line 280 of file event.cpp.
References theDuration.
char * Event::getName ()
Returns the name of the Event
Returns: Name of the Event
Definition at line 302 of file event.cpp.
References theName.
int Event::getNewObj ()
Returns the number of a new object
Returns: number of a new object
Definition at line 319 of file event.cpp.
References newObj.
Referenced by FileValue::Evaluate().
FileValue* Event::getNoteDynamicMark () [inline]
Get note_dynamicMark for event
Returns: A FileValue(p.) * to note_dynamicMark for the event
Definition at line 640 of file event.h.
References note_dynamicMark.
Referenced by EventFactory::Inherit().
FileValue* Event::getNoteModifiers () [inline]
Get note_modifiers for event
Returns: A FileValue(p.) * to note_modifiers for the event
Definition at line 651 of file event.h.
References note_modifiers.
Referenced by EventFactory::Inherit().
FileValue* Event::getNotePitchClass () [inline]
Get note_pitchClass for event
Returns: A FileValue(p.) * to note_pitchClass for the event
Definition at line 629 of file event.h.
References note_pitchClass.
Referenced by EventFactory::Inherit().
FileValue* Event::getSoundDeviation () [inline]
Get sound_deviation for event
Returns: A FileValue(p.) * to sound_deviation for the event
Definition at line 574 of file event.h.
References sound_deviation.
Referenced by EventFactory::Inherit().
FileValue* Event::getSoundModifiers () [inline]
Get sound_modifiers for event /return A FileValue(p.) * to sound_modifiers for the event
Definition at line 596 of file event.h.
References sound_modifiers.
Referenced by EventFactory::Inherit().
FileValue* Event::getSoundNumPartials () [inline]
Get sound_numPartials for event
Returns: A FileValue(p.) * to sound_numPartials for the event
Definition at line 563 of file event.h.
References sound_numPartials.
Referenced by EventFactory::Inherit().
FileValue* Event::getSoundPartEnvs () [inline]
Get sound_partEnvs for event
Returns: A FileValue(p.) * to sound_partEnvs for the event
Definition at line 585 of file event.h.
References sound_partEnvs.
Referenced by EventFactory::Inherit().
FileValue* Event::getSoundReverberation () [inline]
Get sound_reverberation for event
Returns: A FileValue(p.) * to sound_reverberation for the event
Definition at line 607 of file event.h.
References sound_reverberation.
FileValue* Event::getSoundSpatialization () [inline]
Get sound_spatialization for event
Returns: A FileValue(p.) * to sound_spatialization for the event
Definition at line 618 of file event.h.
References sound_spatialization.
float Event::getStartTime ()
Returns the start time of the Event
Returns: Start time of the Event
Definition at line 291 of file event.cpp.
References theStartTime.
int Event::getType ()
Returns the type of the Event
Returns: Type of the Event
Definition at line 233 of file event.cpp.
References theType.
Referenced by FileValue::Evaluate().
void Event::GoldenMean ()
Deprecated NOT IMPLEMENTED - DO NOT USE
void Event::LayerDef ()
Determines how many layers or streams are active in this event (similar to `voices`) and how many types of objects are in each layer.
Deprecated Use NewLayerDef()(p.) instead
Definition at line 401 of file event.cpp.
References barLen, durSec, DataIn::intVect, maxTypes, numLayers, objMaxDur, DataIn::ReadDummies(), DataIn::ReadInts(), typesInLayer, and uPerSec.
void Event::NewAttackMethods (FileValue args)
Choosing a method to determine attack times
Parameters:
args FileValue(p.) of attack methods to use
Definition at line 683 of file event.cpp.
References Attacks(), FileValue::getListPtr(), and sever.
Referenced by BuildSubEvents().
void Event::NewCopyName (list< FileValue > data)
Reads the names of the files defining the elements of the next level and stores them in the two dimenssional character array NameType.
Definition at line 634 of file event.cpp.
References maxTypes, and nameType.
Referenced by Build().
void Event::NewCreateMatrices (FileValue args)
First creates a `generic matrix` of attacks (or units or max sieve elements) * obj types. It will be modified as choices are made. Then, a second matrix of durations (in matrix units) * obj_types is created .
Parameters:
args FileValue(p.) with a matrix vector and two lists of envelopes
Definition at line 1039 of file event.cpp.
References arraySize, d0, durLen, Matrix::Envelopes(), FileValue::Evaluate(), FileValue::getList(), FileValue::getListPtr(), Matrix::GetVector(), Matrix::IncludeArray(), listLen, Matrix, maxTypes, probSieveArray, and s0.
Referenced by BuildSubEvents().
void Event::NewDurationMethods (FileValue args)
Choosing a method to determine durations. /param args A FileValue(p.) of the duration methods to use
Definition at line 786 of file event.cpp.
References FileValue::getList(), PointsProbs(), and sever.
Referenced by BuildSubEvents().
void Event::NewLayerDef (list< FileValue > data)
Determines how many layers or streams are active in this event (similar to `voices`) and how many types of objects are in each layer.
Definition at line 444 of file event.cpp.
References barLen, maxTypes, numLayers, objMaxDur, typesInLayer, and uPerSec.
Referenced by Build().
void Event::NewNumObjs (list< FileValue > data)
Determines how many objects are in each layer according to a `given density per layer
Parameters:
data FileValues to pass in for new objects
Definition at line 541 of file event.cpp.
References layerDens, numLayers, numObjs, objsInLayer, remainObjs, sever, SoundsPerSec(), and theDuration.
Referenced by EventFactory::Build(), and Build().
void Event::NumObjs ()
Determines how many objects are in each layer according to a `given density per layer
Deprecated Use NewNumObjs()(p.) instead
Definition at line 485 of file event.cpp.
References checkPoint, ChooseOffset(), DataIn::fileLoc(), layerDens, DataIn::nameOf, numLayers, numObjs, objsInLayer, DataIn::ReadChars(), ReadComputeFloat(), ReadComputeInt(), DataIn::ReadDummies(), remainObjs, DataIn::rewindFile(), sever, SoundsPerSec(), and theDuration.
void Event::ObjCoordinates ()
Copy the original matrix, include the sieve weights and choose an attack (expressed as location in the sieve) and a obj type.
Definition at line 1114 of file event.cpp.
References Matrix::ChooseM(), Matrix::col, Matrix::IncludeArray(), Matrix, maxTypes, Matrix::Print(), Matrix::PrintVector(), Matrix::row, s0, s1, stimeMatrix, and type.
Referenced by Discrete3().
Event & Event::operator= (const Event & origEvent)
This assigns one Event to another.
Parameters:
origEvent The Event to assign
Definition at line 178 of file event.cpp.
References theDuration, theName, and theStartTime.
void Event::Parameters (int otherParams)
Handles all parameters besides stime, type, and duration. could control ranges (duration, freq. register, modifiers [scales ?] -
like filters or masks or sieves? -, densities, and contrast between objects.
Deprecated DO NOT USE
Definition at line 1890 of file event.cpp.
void Event::PointsProbs (const char * eMethod, vector< int > eArgVector, const char * wMethod, vector< int > wArgVector)
Reads in two arrays at a time according to the method desired: for POINTS, one with all possible attacks (starTarray/stimesMatrix) and one with their probabilities; for INTERVALS, one with all possible durations and a second with their probabilities.
Parameters:
eMethod e-Method for Sieve(p.)
eArgVector e-Vector for Sieve(p.)
wMethod w-Method for Sieve(p.)
wArgVector w-Vector for Sieve(p.)
Definition at line 983 of file event.cpp.
References arraySize, Sieve::Build(), durArray, durLen, Sieve::FillInArrays(), Sieve::GetListLen(), listLen, probDurArray, theDuration, and uPerSec.
void Event::PointsProbs ()
Reads in two arrays at a time according to the method desired: for POINTS, one with all possible attacks (starTarray/stimesMatrix) and one with their probabilities; for INTERVALS, one with all possible durations and a second with their probabilities.
Deprecated DO NOT USE (use PointsProbs(char*, vector<int>, char*, vector<int>) instead)
Definition at line 923 of file event.cpp.
References durArray, durLen, DataIn::floatVect, DataIn::intVect, listLen, DataIn::nameOf, probDurArray, probSieveArray, DataIn::ReadChars(), DataIn::ReadDummies(), DataIn::ReadFloats(), DataIn::ReadInts(), sever, and starTarray.
Referenced by DurationMethods(), and NewDurationMethods().
void Event::Print () [virtual]
Reimplemented in Bottom (p.), High (p.), Low (p.), and Top (p.).
Definition at line 2046 of file event.cpp.
References nameType, numObjs, subevents, theDuration, theName, theStartTime, and theType.
Referenced by EventFactory::Build(), and buildNote().
void Event::SelectNextEvent ()
Identifies the type of the next object, calls its constructor and opens the file associated with it. Then, it calls Build and CreateNewObjects in a recursive process.
Deprecated NOT IMPLEMENTED - DO NOT USE
void Event::setBottomFreq (FileValue * s) [inline]
Set bottom frequency
Parameters:
s A FileValue(p.) * to the new bottom frequency of the event
Definition at line 546 of file event.h.
References bottom_frequency.
Referenced by EventFactory::Build().
void Event::setBottomLoud (FileValue * s) [inline]
Set bottom loudness
Parameters:
s A FileValue(p.) * to the new bottom loudness of the event
Definition at line 557 of file event.h.
References bottom_loudness.
Referenced by EventFactory::Build().
void Event::setDensity (double aDensity) [virtual]
Sets the density of the event
Parameters:
aDensity Density of the event
Reimplemented in Bottom (p.).
Definition at line 269 of file event.cpp.
References theDensity.
Referenced by High::High(), and Low::Low().
void Event::setDuration (float aDuration) [virtual]
Sets the duration of the event
Parameters:
aDuration Duration of the event
Reimplemented in Bottom (p.).
Definition at line 242 of file event.cpp.
References theDuration.
Referenced by Event(), High::High(), Low::Low(), and Top::Top().
void Event::setName (char * aName) [virtual]
Sets the name of the event
Parameters:
aName Name of the event
Reimplemented in Bottom (p.).
Definition at line 252 of file event.cpp.
References theName.
Referenced by Event(), High::High(), Low::Low(), and Top::Top().
void Event::setNoteDynamicMark (FileValue * s) [inline]
Set note_dynamicMark for event
Parameters:
s A FileValue(p.) * to new note_dynamicMark for the event
Definition at line 645 of file event.h.
References note_dynamicMark.
Referenced by EventFactory::Build().
void Event::setNoteModifiers (FileValue * s) [inline]
Set note_modifiers for event
Parameters:
s A FileValue(p.) * to new note_modifiers for the event
Definition at line 656 of file event.h.
References note_modifiers.
Referenced by EventFactory::Build().
void Event::setNotePitchClass (FileValue * s) [inline]
Set note_pitchClass for event
Parameters:
s A FileValue(p.) * to new note_pitchClass for the event
Definition at line 634 of file event.h.
References note_pitchClass.
Referenced by EventFactory::Build().
void Event::setSoundDeviation (FileValue * s) [inline]
Set sound_deviation for event
Parameters:
s A FileValue(p.) * to new sound_deviation for the event
Definition at line 579 of file event.h.
References sound_deviation.
Referenced by EventFactory::Build().
void Event::setSoundModifiers (FileValue * s) [inline]
Set sound_modifiers for event /param s A FileValue(p.) * to new sound_modifiers for the event
Definition at line 601 of file event.h.
References sound_modifiers.
Referenced by EventFactory::Build().
void Event::setSoundNumPartials (FileValue * s) [inline]
Set sound_numPartials for event
Parameters:
s A FileValue(p.) * to new sound_numPartials for the event
Definition at line 568 of file event.h.
References sound_numPartials.
Referenced by EventFactory::Build().
void Event::setSoundPartEnvs (FileValue * s) [inline]
Set sound_partEnvs for event
Parameters:
s A FileValue(p.) * to new sound_partEnvs for the event
Definition at line 590 of file event.h.
References sound_partEnvs.
Referenced by EventFactory::Build().
void Event::setSoundReverberation (FileValue * s) [inline]
Set sound_reverberation for event
Parameters:
s A FileValue(p.) * to new sound_reverberation for the event
Definition at line 612 of file event.h.
References sound_reverberation.
void Event::setSoundSpatialization (FileValue * s) [inline]
Set sound_spatialization for event
Parameters:
s A FileValue(p.) * to new sound_spatialization for the event
Definition at line 623 of file event.h.
References sound_spatialization.
void Event::setStartDurationType (list< FileValue > data)
Deprecated DO NOT USE
void Event::setStartTime (float aStartTime) [virtual]
Sets the start time of the event
Parameters:
aStartTime Start time for the event
Reimplemented in Bottom (p.), and Top (p.).
Definition at line 209 of file event.cpp.
References theStartTime.
Referenced by Event(), High::High(), and Low::Low().
void Event::setType (int aType) [virtual]
Sets the type of the event
Parameters:
aType Type of the event
Definition at line 224 of file event.cpp.
References theType.
Referenced by Event(), High::High(), and Low::Low().
int Event::Stimes ()
Deprecated DO NOT USE (Used to be private... not sure why it isn't anymore)
Reimplemented in Top (p.).
Definition at line 1350 of file event.cpp.
References arraySize, GSection(), List< Etype >::Head(), List< Etype >::InsertInOrder(), DataIn::intVect, List< Etype >::Length(), levels, DataIn::ReadInts(), List< Etype >::Retrieve(), starTarray, theDuration, and uPerSec.
void Event::Sweep3 ()
DEPRECATED
Sweep3. Method for assigning stimeSec and durSec values in sequential order - `sweepeing` from left to right or beginning to end of the event. For stime and duration two different methods are used, one for integer values the other for float values. Type being a discrete value, the integer values method is used for it.
Definition at line 1766 of file event.cpp.
References checkPoint, ChooseOffset(), durSec, lastime, DataIn::nameOf, newObj, objMaxDur, DataIn::ReadChars(), ReadComputeFloat(), ReadComputeInt(), sever, stimeSec, theDuration, type, uPerSec, and ValuePick().
void Event::TestNameType ()
Prints the test name type to standard output (cout).
Definition at line 2006 of file event.cpp.
References maxTypes, nameType, numChars, and sever.
Referenced by Bottom::clear().
void Event::TimeConvert ()
Converts stimeMatrix and durMatrix as defined in the (sieve) array into time units (for notation) and into seconds (for synthesis). It also determines the checkPoint (a) or where this object is in the larger event for use in further calculations.
Definition at line 1323 of file event.cpp.
References checkPoint, durArray, duRatio, durMatrix, durSec, durUnits, listLen, objMaxDur, starTarray, stimeMatrix, stimeSec, stimeUnits, theDuration, theStartTime, and uPerSec.
Referenced by Discrete3().
Friends And Related Function Documentation
friend class Matrix [friend]
Definition at line 45 of file event.h.
Referenced by FindDur(), NewCreateMatrices(), and ObjCoordinates().
Member Data Documentation
char* Event::aName
Definition at line 231 of file event.h.
Referenced by Bottom::Bottom(), High::High(), Low::Low(), and Top::Top().
int Event::arraySize
Definition at line 405 of file event.h.
Referenced by Attacks(), NewCreateMatrices(), PointsProbs(), and Stimes().
int Event::barLen
Reimplemented in Note (p.).
Definition at line 400 of file event.h.
Referenced by EventFactory::Build(), Bottom::buildNote(), LayerDef(), and NewLayerDef().
FileValue* Event::bottom_frequency [protected]
Definition at line 519 of file event.h.
Referenced by Note::AssignPitch(), getBottomFreq(), and setBottomFreq().
FileValue* Event::bottom_loudness [protected]
Definition at line 520 of file event.h.
Referenced by Note::AssignLoudness(), getBottomLoud(), Bottom::Loud(), and setBottomLoud().
double Event::checkPoint
Definition at line 222 of file event.h.
Referenced by EventFactory::Build(), Bottom::buildNote(), Bottom::buildSound(), BuildSubEvents(), Bottom::ChooseSoundDynParam(), Continuum(), Continuum3(), getCheckPoint(), NumObjs(), Bottom::Spectrum(), Sweep3(), and TimeConvert().
float** Event::coefParam
Definition at line 502 of file event.h.
Matrix * Event::d0
Definition at line 223 of file event.h.
Referenced by FindDur(), and NewCreateMatrices().
Matrix * Event::d1
Definition at line 223 of file event.h.
Referenced by FindDur().
int** Event::dataParam
Definition at line 501 of file event.h.
int* Event::durArray
Definition at line 407 of file event.h.
Referenced by clear(), Bottom::clear(), Event(), FindDur(), FindLen(), PointsProbs(), and TimeConvert().
double Event::duRatio
Definition at line 489 of file event.h.
Referenced by TimeConvert().
int Event::durLen
Definition at line 405 of file event.h.
Referenced by FindLen(), NewCreateMatrices(), and PointsProbs().
int Event::durMatrix
Definition at line 487 of file event.h.
Referenced by FindDur(), and TimeConvert().
float Event::durSec
Reimplemented in Note (p.).
Definition at line 488 of file event.h.
Referenced by Bottom::buildNote(), Bottom::buildSound(), BuildSubEvents(), Continuum(), Continuum3(), LayerDef(), Bottom::PrintSound(), Sweep3(), and TimeConvert().
int Event::durUnits
Reimplemented in Note (p.).
Definition at line 487 of file event.h.
Referenced by TimeConvert().
int* Event::envParam
Definition at line 507 of file event.h.
char* Event::fname
Definition at line 495 of file event.h.
char* Event::keepName
Definition at line 492 of file event.h.
Referenced by Top::Top().
float Event::lastime [protected]
Definition at line 533 of file event.h.
Referenced by BuildSubEvents(), and Sweep3().
int Event::layer
Definition at line 493 of file event.h.
Referenced by Adjustments().
float* Event::layerDens
Definition at line 411 of file event.h.
Referenced by Adjustments(), clear(), Bottom::clear(), Event(), NewNumObjs(), and NumObjs().
int Event::length
Reimplemented in Top (p.).
Definition at line 401 of file event.h.
int Event::levels
Reimplemented in Top (p.).
Definition at line 401 of file event.h.
Referenced by Stimes().
int Event::listLen
Definition at line 405 of file event.h.
Referenced by Attacks(), FindDur(), FindLen(), NewCreateMatrices(), PointsProbs(), and TimeConvert().
long Event::loc0
Definition at line 490 of file event.h.
Referenced by BuildSubEvents().
long Event::loc1
Definition at line 490 of file event.h.
int** Event::maxLen
Definition at line 506 of file event.h.
int Event::maxTypes
Definition at line 400 of file event.h.
Referenced by EventFactory::Build(), clear(), Bottom::clear(), CopyName(), LayerDef(), NewCopyName(), NewCreateMatrices(), NewLayerDef(), ObjCoordinates(), and TestNameType().
char** Event::nameType
Definition at line 232 of file event.h.
Referenced by EventFactory::Build(), BuildSubEvents(), clear(), Bottom::clear(), CopyName(), Event(), NewCopyName(), Print(), and TestNameType().
int Event::newObj
Definition at line 491 of file event.h.
Referenced by Adjustments(), Bottom::buildNote(), BuildSubEvents(), Continuum3(), getNewObj(), Bottom::OneStep(), and Sweep3().
FileValue* Event::note_dynamicMark [protected]
Definition at line 530 of file event.h.
Referenced by Note::AssignLoudness(), Bottom::buildNote(), getNoteDynamicMark(), and setNoteDynamicMark().
FileValue* Event::note_modifiers [protected]
Definition at line 531 of file event.h.
Referenced by Bottom::buildNote(), getNoteModifiers(), Note::Modifiers(), and setNoteModifiers().
FileValue* Event::note_pitchClass [protected]
Definition at line 529 of file event.h.
Referenced by Note::AssignPitch(), Bottom::buildNote(), getNotePitchClass(), and setNotePitchClass().
int Event::noWeights
Definition at line 405 of file event.h.
int Event::numChars
Definition at line 400 of file event.h.
Referenced by CopyName(), and TestNameType().
int Event::numLayers
Definition at line 400 of file event.h.
Referenced by Adjustments(), EventFactory::Build(), LayerDef(), NewLayerDef(), NewNumObjs(), and NumObjs().
int Event::numObjs
Definition at line 402 of file event.h.
Referenced by Adjustments(), BuildSubEvents(), NewNumObjs(), NumObjs(), Print(), and Bottom::Spatialization().
int Event::numParam
Definition at line 498 of file event.h.
int Event::objID
Definition at line 402 of file event.h.
Referenced by BuildSubEvents(), Event(), Bottom::PrintSound(), and Top::Top().
int Event::objMaxDur
Definition at line 400 of file event.h.
Referenced by EventFactory::Build(), Continuum(), Continuum3(), LayerDef(), NewLayerDef(), Sweep3(), and TimeConvert().
int* Event::objsInLayer
Definition at line 412 of file event.h.
Referenced by clear(), Bottom::clear(), Event(), NewNumObjs(), and NumObjs().
double* Event::probDurArray
Definition at line 409 of file event.h.
Referenced by clear(), Bottom::clear(), Event(), and PointsProbs().
float* Event::probParam
Definition at line 499 of file event.h.
double* Event::probSieveArray
Definition at line 408 of file event.h.
Referenced by Attacks(), clear(), Bottom::clear(), Event(), NewCreateMatrices(), and PointsProbs().
int* Event::remainObjs
Definition at line 413 of file event.h.
Referenced by Adjustments(), clear(), Bottom::clear(), Event(), NewNumObjs(), and NumObjs().
Matrix* Event::s0
Definition at line 223 of file event.h.
Referenced by Adjustments(), FindLen(), NewCreateMatrices(), and ObjCoordinates().
Matrix * Event::s1
Definition at line 223 of file event.h.
Referenced by ObjCoordinates().
float* Event::scaleParam
Definition at line 508 of file event.h.
int** Event::sieveParam
Definition at line 503 of file event.h.
FileValue* Event::sound_deviation [protected]
Definition at line 523 of file event.h.
Referenced by getSoundDeviation(), setSoundDeviation(), and Bottom::Spectrum().
FileValue* Event::sound_modifiers [protected]
Definition at line 525 of file event.h.
Referenced by getSoundModifiers(), and setSoundModifiers().
FileValue* Event::sound_numPartials [protected]
Definition at line 522 of file event.h.
Referenced by getSoundNumPartials(), Bottom::NumPart(), and setSoundNumPartials().
FileValue* Event::sound_partEnvs [protected]
Definition at line 524 of file event.h.
Referenced by getSoundPartEnvs(), and setSoundPartEnvs().
FileValue* Event::sound_reverberation [protected]
Definition at line 526 of file event.h.
Referenced by Bottom::buildSound(), getSoundReverberation(), and setSoundReverberation().
FileValue* Event::sound_spatialization [protected]
Definition at line 527 of file event.h.
Referenced by Bottom::buildSound(), getSoundSpatialization(), and setSoundSpatialization().
int* Event::starTarray
Definition at line 406 of file event.h.
Referenced by Attacks(), clear(), Bottom::clear(), Event(), FindDur(), FindLen(), PointsProbs(), Stimes(), and TimeConvert().
int Event::stimeMatrix
Definition at line 487 of file event.h.
Referenced by Adjustments(), FindDur(), FindLen(), ObjCoordinates(), and TimeConvert().
float Event::stimeSec
Reimplemented in Note (p.).
Definition at line 488 of file event.h.
Referenced by EventFactory::Build(), Bottom::buildNote(), Bottom::buildSound(), BuildSubEvents(), Continuum(), Continuum3(), Bottom::PrintSound(), Sweep3(), and TimeConvert().
int Event::stimeUnits
Reimplemented in Note (p.).
Definition at line 487 of file event.h.
Referenced by TimeConvert().
list<Event*> Event::subevents
Definition at line 235 of file event.h.
Referenced by buildNote(), buildScore(), BuildSubEvents(), and Print().
int** Event::tempSieves
Definition at line 504 of file event.h.
double Event::theDensity
Definition at line 233 of file event.h.
Referenced by EventFactory::Build(), Event(), getDensity(), Top::SetDens(), and setDensity().
float Event::theDuration
Definition at line 228 of file event.h.
Referenced by Attacks(), EventFactory::Build(), BuildSubEvents(), Continuum(), Continuum3(), Event(), FindLen(), getDuration(), NewNumObjs(), NumObjs(), operator=(), PointsProbs(), Top::Print(), Low::Print(), High::Print(), Print(), Bottom::Print(), Top::SetDuration(), setDuration(), Stimes(), Sweep3(), and TimeConvert().
char* Event::theName
Definition at line 230 of file event.h.
Referenced by EventFactory::Build(), BuildSubEvents(), Bottom::clear(), Event(), getName(), operator=(), Top::Print(), Low::Print(), High::Print(), Print(), Bottom::Print(), and setName().
float Event::theStartTime
Definition at line 227 of file event.h.
Referenced by EventFactory::Build(), Event(), getStartTime(), operator=(), Top::Print(), Low::Print(), High::Print(), Print(), Bottom::Print(), Top::setStartTime(), setStartTime(), and TimeConvert().
int Event::theType
Definition at line 229 of file event.h.
Referenced by EventFactory::Build(), getType(), Print(), and setType().
int Event::type
Definition at line 491 of file event.h.
Referenced by Adjustments(), EventFactory::Build(), Bottom::buildNote(), BuildSubEvents(), Continuum(), Continuum3(), FindDur(), FindLen(), ObjCoordinates(), Bottom::OneStep(), Bottom::PrintSound(), and Sweep3().
int* Event::typesInLayer
Definition at line 403 of file event.h.
Referenced by Adjustments(), EventFactory::Build(), clear(), Bottom::clear(), Event(), LayerDef(), and NewLayerDef().
int Event::uPerSec
Reimplemented in Note (p.).
Definition at line 400 of file event.h.
Referenced by Attacks(), EventFactory::Build(), Bottom::buildNote(), BuildSubEvents(), Continuum(), Continuum3(), FindLen(), LayerDef(), NewLayerDef(), PointsProbs(), Top::Print(), Low::Print(), High::Print(), Bottom::Print(), Stimes(), Sweep3(), and TimeConvert().
The documentation for this class was generated from the following files:
event.h
event.cpp