Top Class Reference
#include <top.h>
Public Member Functions
Top (char *aName)
Top (float aStartTime, float aDuration, int aType, char *aName)
Top (const Top &origTop)
~Top ()
void clear ()
virtual void setStartTime (float aStartTime)
virtual void SetDuration (float aDuration)
float SetDens (double aDensity)
void Print ()
Private Member Functions
int Stimes ()
Private Attributes
char * fileName
int levels
int length
Constructor & Destructor Documentation
Top::Top (char * aName)
CONSTRUCTOR: Top. Empty, generic event; has only a name.
Definition at line 48 of file top.cpp.
References Event::aName, Event::keepName, Event::objID, and Event::setName().
Top::Top (float aStartTime, float aDuration, int aType, char * aName)
CONSTRUCTOR: Top (All fundamental information)
Definition at line 61 of file top.cpp.
References Event::aName, Event::keepName, Event::setDuration(), Event::setName(), and setStartTime().
Top::Top (const Top & origTop)
CONSTRUCTOR: Top (copy constructor)
Definition at line 75 of file top.cpp.
Top::~Top ()
DESTRUCTOR: ~Top
Definition at line 85 of file top.cpp.
Member Function Documentation
void Top::clear () [virtual]
Clears several internal structures in the Event(p.): nameType, maxTypes, layerDens, objsInLayer, remainObjs, typesInLayer, starTarray, probSieveArray, durArray, probDurArray
Reimplemented from Event (p.).
Definition at line 93 of file top.cpp.
void Top::Print () [virtual]
Print
Reimplemented from Event (p.).
Definition at line 136 of file top.cpp.
References outputFile, Event::theDuration, Event::theName, Event::theStartTime, and Event::uPerSec.
float Top::SetDens (double aDensity)
Set the density of the top level
Definition at line 107 of file top.cpp.
References Event::theDensity.
void Top::SetDuration (float aDuration) [virtual]
SetDuration
Definition at line 126 of file top.cpp.
References Event::theDuration.
void Top::setStartTime (float aStartTime) [virtual]
SetStartTime
Reimplemented from Event (p.).
Definition at line 117 of file top.cpp.
References Event::theStartTime.
Referenced by Top().
int Top::Stimes () [private]
Deprecated DO NOT USE (Used to be private... not sure why it isn't anymore)
Reimplemented from Event (p.).
Member Data Documentation
char* Top::fileName [private]
Definition at line 65 of file top.h.
int Top::length [private]
Reimplemented from Event (p.).
Definition at line 66 of file top.h.
int Top::levels [private]
Reimplemented from Event (p.).
Definition at line 66 of file top.h.
The documentation for this class was generated from the following files:
top.h
top.cpp