List< Etype > Class Template Reference
#include <linkList.h>
Public Member Functions
List ()
List (Etype aLow, Etype aHigh)
List (const List< Etype > &origList)
~List ()
void Clear ()
List< Etype > & operator= (const List< Etype > &origlist)
void InsertAfter (Etype newElem)
void InsertBefore (Etype newElem)
void InsertInOrder (Etype newElem)
void Remove ()
void Update (Etype updateElem)
void Head ()
void Tail ()
List< Etype > & operator++ (int)
List< Etype > & operator-- (int)
Etype Retrieve () const
int Includes (Etype queryElem)
int Length () const
void Print ()
void Sieve (List< Etype > &aSieve)
void PickFromList (Etype aLow, Etype aHigh)
Etype Sum ()
Etype Min ()
Etype Max ()
void Transpose (Etype aStart)
void Normalize ()
void Scale ()
void InsertionSort ()
Protected Attributes
Node * head
Node * current
int size
template<class Etype> class List< Etype >
Constructor & Destructor Documentation
template<class Etype> List< Etype >::List ()
Definition at line 185 of file linkList.h.
References List< Etype >::current, List< Etype >::head, and List< Etype >::size.
template<class Etype> List< Etype >::List (Etype aLow, Etype aHigh)
Definition at line 198 of file linkList.h.
References List< Etype >::current, List< Etype >::head, List< Etype >::InsertAfter(), and List< Etype >::size.
template<class Etype> List< Etype >::List (const List< Etype > & origList)
Definition at line 213 of file linkList.h.
References List< Etype >::current, List< Etype >::Node::element, List< Etype >::head, List< Etype >::Node::next, and List< Etype >::size.
template<class Etype> List< Etype >::~List ()
Definition at line 254 of file linkList.h.
References List< Etype >::Clear().
Member Function Documentation
template<class Etype> void List< Etype >::Clear ()
Definition at line 264 of file linkList.h.
References List< Etype >::current, List< Etype >::head, List< Etype >::Node::next, and List< Etype >::size.
Referenced by List< Etype >::InsertionSort(), List< Etype >::operator=(), and List< Etype >::~List().
template<class Etype> void List< Etype >::Head ()
Definition at line 475 of file linkList.h.
References List< Etype >::current, and List< Etype >::head.
Referenced by Random::AssignProb(), ChooseL(), CumulWeights(), GSection(), List< Etype >::Max(), List< Etype >::Min(), List< Etype >::Normalize(), List< Etype >::PickFromList(), List< Etype >::Print(), List< Etype >::Scale(), Event::Stimes(), List< Etype >::Sum(), and List< Etype >::Transpose().
template<class Etype> int List< Etype >::Includes (Etype queryElem)
Definition at line 547 of file linkList.h.
References List< Etype >::current, List< Etype >::Node::element, List< Etype >::head, and List< Etype >::Node::next.
Referenced by List< Etype >::Sieve().
template<class Etype> void List< Etype >::InsertAfter (Etype newElem)
Definition at line 337 of file linkList.h.
References List< Etype >::current, List< Etype >::Node::element, List< Etype >::head, List< Etype >::Node::next, and List< Etype >::size.
Referenced by List< Etype >::InsertInOrder(), and List< Etype >::List().
template<class Etype> void List< Etype >::InsertBefore (Etype newElem)
Definition at line 362 of file linkList.h.
References List< Etype >::current, List< Etype >::Node::element, List< Etype >::head, List< Etype >::Node::next, and List< Etype >::size.
Referenced by List< Etype >::InsertInOrder().
template<class Etype> void List< Etype >::InsertInOrder (Etype newElem)
Definition at line 389 of file linkList.h.
References List< Etype >::current, List< Etype >::Node::element, List< Etype >::head, List< Etype >::InsertAfter(), List< Etype >::InsertBefore(), List< Etype >::Node::next, and List< Etype >::size.
Referenced by Event::DurationMethods(), GSection(), List< Etype >::InsertionSort(), and Event::Stimes().
template<class Etype> void List< Etype >::InsertionSort ()
Definition at line 859 of file linkList.h.
References List< Etype >::Clear(), List< Etype >::current, List< Etype >::Node::element, List< Etype >::head, List< Etype >::InsertInOrder(), List< Etype >::Node::next, and List< Etype >::size.
template<class Etype> int List< Etype >::Length () const
Definition at line 568 of file linkList.h.
References List< Etype >::size.
Referenced by Random::AssignProb(), ChooseL(), CumulWeights(), List< Etype >::PickFromList(), and Event::Stimes().
template<class Etype> Etype List< Etype >::Max ()
Definition at line 729 of file linkList.h.
References List< Etype >::current, List< Etype >::Node::element, List< Etype >::Head(), and List< Etype >::size.
template<class Etype> Etype List< Etype >::Min ()
Definition at line 694 of file linkList.h.
References List< Etype >::current, List< Etype >::Node::element, List< Etype >::Head(), and List< Etype >::size.
Referenced by List< Etype >::Transpose().
template<class Etype> void List< Etype >::Normalize ()
Definition at line 792 of file linkList.h.
References List< Etype >::current, List< Etype >::Node::element, List< Etype >::Head(), List< Etype >::size, and List< Etype >::Sum().
Referenced by CumulWeights().
template<class Etype> List< Etype > & List< Etype >::operator++ (int)
Definition at line 500 of file linkList.h.
References List< Etype >::current, List< Etype >::Node::next, and List< Etype >::size.
template<class Etype> List< Etype > & List< Etype >::operator-- (int)
Definition at line 515 of file linkList.h.
References List< Etype >::current, List< Etype >::head, and List< Etype >::Node::next.
template<class Etype> List< Etype > & List< Etype >::operator= (const List< Etype > & origlist)
Definition at line 288 of file linkList.h.
References List< Etype >::Clear(), List< Etype >::current, List< Etype >::Node::element, List< Etype >::head, List< Etype >::Node::next, and List< Etype >::size.
template<class Etype> void List< Etype >::PickFromList (Etype aLow, Etype aHigh)
Definition at line 629 of file linkList.h.
References List< Etype >::Head(), List< Etype >::Length(), List< Etype >::Remove(), List< Etype >::Retrieve(), and List< Etype >::size.
template<class Etype> void List< Etype >::Print ()
Definition at line 580 of file linkList.h.
References List< Etype >::current, List< Etype >::Node::element, List< Etype >::Head(), and List< Etype >::size.
template<class Etype> void List< Etype >::Remove ()
Definition at line 417 of file linkList.h.
References List< Etype >::current, List< Etype >::Node::element, List< Etype >::head, List< Etype >::Node::next, and List< Etype >::size.
Referenced by List< Etype >::PickFromList(), and List< Etype >::Sieve().
template<class Etype> Etype List< Etype >::Retrieve () const
Definition at line 533 of file linkList.h.
References List< Etype >::current, and List< Etype >::Node::element.
Referenced by ChooseL(), CumulWeights(), GSection(), List< Etype >::PickFromList(), Event::Stimes(), and List< Etype >::Sum().
template<class Etype> void List< Etype >::Scale ()
Definition at line 823 of file linkList.h.
References List< Etype >::current, List< Etype >::Node::element, List< Etype >::Head(), and List< Etype >::size.
template<class Etype> void List< Etype >::Sieve (List< Etype > & aSieve)
Definition at line 604 of file linkList.h.
References List< Etype >::current, List< Etype >::Node::element, List< Etype >::head, List< Etype >::Includes(), List< Etype >::Remove(), and List< Etype >::size.
template<class Etype> Etype List< Etype >::Sum ()
Definition at line 659 of file linkList.h.
References List< Etype >::current, List< Etype >::Head(), List< Etype >::Retrieve(), and List< Etype >::size.
Referenced by List< Etype >::Normalize().
template<class Etype> void List< Etype >::Tail ()
Definition at line 486 of file linkList.h.
References List< Etype >::current, List< Etype >::Node::next, and List< Etype >::size.
template<class Etype> void List< Etype >::Transpose (Etype aStart)
Definition at line 764 of file linkList.h.
References List< Etype >::current, List< Etype >::Node::element, List< Etype >::Head(), List< Etype >::Min(), and List< Etype >::size.
template<class Etype> void List< Etype >::Update (Etype updateElem)
Definition at line 459 of file linkList.h.
References List< Etype >::current, List< Etype >::Node::element, and List< Etype >::size.
Referenced by Random::AssignProb(), and CumulWeights().
Member Data Documentation
template<class Etype> Node * List< Etype >::current [protected]
Definition at line 175 of file linkList.h.
Referenced by List< Etype >::Clear(), List< Etype >::Head(), List< Etype >::Includes(), List< Etype >::InsertAfter(), List< Etype >::InsertBefore(), List< Etype >::InsertInOrder(), List< Etype >::InsertionSort(), List< Etype >::List(), List< Etype >::Max(), List< Etype >::Min(), List< Etype >::Normalize(), List< Etype >::operator++(), List< Etype >::operator--(), List< Etype >::operator=(), List< Etype >::Print(), List< Etype >::Remove(), List< Etype >::Retrieve(), List< Etype >::Scale(), List< Etype >::Sieve(), List< Etype >::Sum(), List< Etype >::Tail(), List< Etype >::Transpose(), and List< Etype >::Update().
template<class Etype> Node* List< Etype >::head [protected]
Definition at line 175 of file linkList.h.
Referenced by List< Etype >::Clear(), List< Etype >::Head(), List< Etype >::Includes(), List< Etype >::InsertAfter(), List< Etype >::InsertBefore(), List< Etype >::InsertInOrder(), List< Etype >::InsertionSort(), List< Etype >::List(), List< Etype >::operator--(), List< Etype >::operator=(), List< Etype >::Remove(), and List< Etype >::Sieve().
template<class Etype> int List< Etype >::size [protected]
Definition at line 178 of file linkList.h.
Referenced by List< Etype >::Clear(), List< Etype >::InsertAfter(), List< Etype >::InsertBefore(), List< Etype >::InsertInOrder(), List< Etype >::InsertionSort(), List< Etype >::Length(), List< Etype >::List(), List< Etype >::Max(), List< Etype >::Min(), List< Etype >::Normalize(), List< Etype >::operator++(), List< Etype >::operator=(), List< Etype >::PickFromList(), List< Etype >::Print(), List< Etype >::Remove(), List< Etype >::Scale(), List< Etype >::Sieve(), List< Etype >::Sum(), List< Etype >::Tail(), List< Etype >::Transpose(), and List< Etype >::Update().
The documentation for this class was generated from the following file:
linkList.h