Low Class Reference
#include <low.h>
Public Member Functions
Low (float aStartTime, float aDuration, int aType, char *aName)
Low (const Low &origLow)
~Low ()
Low & operator= (const Low &origLow)
void clear ()
void Print ()
Protected Attributes
double lowDensity
Constructor & Destructor Documentation
Low::Low (float aStartTime, float aDuration, int aType, char * aName)
Definition at line 47 of file low.cpp.
References Event::aName, bottomID, lowID, Event::setDensity(), Event::setDuration(), Event::setName(), Event::setStartTime(), and Event::setType().
Low::Low (const Low & origLow)
Definition at line 79 of file low.cpp.
References bottomID, and lowID.
Low::~Low ()
Definition at line 91 of file low.cpp.
Member Function Documentation
void Low::clear () [virtual]
Clears several internal structures in the Event(p.): nameType, maxTypes, layerDens, objsInLayer, remainObjs, typesInLayer, starTarray, probSieveArray, durArray, probDurArray
Reimplemented from Event (p.).
Definition at line 100 of file low.cpp.
Low& Low::operator= (const Low & origLow)
void Low::Print () [virtual]
Reimplemented from Event (p.).
Definition at line 109 of file low.cpp.
References lowID, outputFile, Event::theDuration, Event::theName, Event::theStartTime, and Event::uPerSec.
Member Data Documentation
double Low::lowDensity [protected]
Definition at line 37 of file low.h.
The documentation for this class was generated from the following files:
low.h
low.cpp