Matrix Class Reference
#include <matrix.h>
Public Member Functions
Matrix (int x=5, int y=5, double init=0.0)
Matrix (const Matrix &origMatrix)
~Matrix ()
Matrix & operator= (Matrix &m)
double operator() (int a, int b)
void IncludeArray (double array[], int from, int to)
void GetVector (char *fileName)
void GetVector (vector< float > newVector)
void IncludeVector ()
void AdjustVector (int, int, int, int)
void AdjustMatrix (int, int, int, int, int, int)
void BuildMatrix (double[])
void BuildMatrix2 (List< int > &, int)
void TrimMatrix (int type, float density, int remain0, int durLoc)
void ChooseM ()
void ChooseM (int &r, int &c)
void Envelopes (char *fileName)
void Envelopes (vector< float > probs, vector< Envelope * > envList)
void Envelopes (vector< float > probs, vector< int > envNums, vector< float > coeffs)
void Envelopes (char *fileName, vector< Collection< xy_point > > xyCollection, vector< vector< string > > segmentTypes, vector< vector< string > > segmentFixed)
void Envelopes (vector< Collection< xy_point > > xyCollection, vector< vector< string > > segmentTypes, vector< vector< string > > segmentFixed)
void Interpol (int, double[])
void Mult (int remain0, float density, int type, int durLoc, int durArray[], int stimeMatrix, int starTarray[])
void Normalize ()
void SetDim (int x, int y)
double GetValueAt (int x, int y)
void Init (double init)
void Print ()
void PrintVector ()
void Clear ()
int GetX ()
int GetY ()
Public Attributes
int col
int row
double ** matrix
Private Member Functions
void Smooth (int, int, int, int, int)
Private Attributes
double * stProb
int sever
int x
int y
double * _vector
Friends
class Event
ostream & operator<< (ostream &s, Matrix &m)
Constructor & Destructor Documentation
Matrix::Matrix (int x = 5, int y = 5, double init = 0.0)
Matrix constructor
Definition at line 51 of file matrix.cpp.
References Init(), matrix, and SetDim().
Matrix::Matrix (const Matrix & m)
Matrix Copy Constructor
Definition at line 74 of file matrix.cpp.
References _vector, matrix, SetDim(), x, and y.
Matrix::~Matrix ()
Destructor: Matrix
Definition at line 95 of file matrix.cpp.
References Clear().
Member Function Documentation
void Matrix::AdjustMatrix (int type, int stimeMatrix, int endLocM, int slope, int from, int to)
PUBLIC: ADJUSTMATRIX. Blocks the locations covered by the duration (durMatrix). The edges are smoothed following a user define slope.
Definition at line 297 of file matrix.cpp.
References matrix, Smooth(), and y.
Referenced by Event::Adjustments().
void Matrix::AdjustVector (int type, int remainO, int from, int to)
PUBLIC: ADJUSTVECTOR.
If remainO is -1, sets each element of the vector in the range specified by from and to to 0. If remainO is 0, sets the vector element specified by type to 0. Otherwise, decreases the vector element specified by type by 1/(remain0 + 1) for each element in the matrix line specified by type that is greater than 0. Finally, normalizes the vector element range specified by from and to.
Definition at line 246 of file matrix.cpp.
References _vector, matrix, sever, and y.
Referenced by Event::Adjustments().
void Matrix::BuildMatrix (double array[])
BuildMatrix
Definition at line 413 of file matrix.cpp.
void Matrix::BuildMatrix2 (List< int > &, int)
void Matrix::ChooseM (int & r, int & c)
ChooseM
Same as ChooseM but returns the values directly to the caller through the reference params r and c.
Definition at line 462 of file matrix.cpp.
References ChooseM(), col, and row.
void Matrix::ChooseM ()
STATIC PUBLIC: CHOOSEM
Chooses an element out of the probability matrix, based on each element's associated probability and a randomly generated number
Definition at line 432 of file matrix.cpp.
References col, matrix, Print(), Random::Rand(), row, x, and y.
Referenced by ChooseM(), Event::FindDur(), and Event::ObjCoordinates().
void Matrix::Clear ()
PUBLIC: CLEAR. Deletes the matrix and sets its dimensions to 0.
Definition at line 177 of file matrix.cpp.
References _vector, matrix, x, and y.
Referenced by operator=(), SetDim(), and ~Matrix().
void Matrix::Envelopes (vector< Collection< xy_point > > xyCollection, vector< vector< string > > segmentTypes, vector< vector< string > > segmentFixed)
Definition at line 576 of file matrix.cpp.
References matrix, x, and y.
void Matrix::Envelopes (char * fileName, vector< Collection< xy_point > > xyCollection, vector< vector< string > > segmentTypes, vector< vector< string > > segmentFixed)
void Matrix::Envelopes (vector< float > probs, vector< int > envNums, vector< float > coeffs)
void Matrix::Envelopes (vector< float > probs, vector< Envelope * > envList)
PUBLIC: Envelopes. Creates an envelope and loads envelopes from the library and finds their values corresponding to each sieve location (attack point). NB. we deal here with sieve locations and not with actual time values.
Definition at line 557 of file matrix.cpp.
References matrix, x, and y.
void Matrix::Envelopes (char * fileName)
Referenced by Event::NewCreateMatrices().
double Matrix::GetValueAt (int x, int y)
void Matrix::GetVector (vector< float > newVector)
PUBLIC: GetVector. Read or Compute a vector from a file.
Definition at line 647 of file matrix.cpp.
References _vector, and x.
void Matrix::GetVector (char * fileName)
PUBLIC: GetVector. Read or Compute a vector from a file.
Referenced by Event::NewCreateMatrices().
int Matrix::GetX ()
PUBLIC: GetX. Gets the value of the first subscript of the matrix.
Definition at line 136 of file matrix.cpp.
References x.
int Matrix::GetY ()
PUBLIC: GetY. Gets the value of the second subscript of the matrix.
Definition at line 148 of file matrix.cpp.
References y.
void Matrix::IncludeArray (double array[], int from, int to)
IncludeArray. Multiplies the elements of an existing matrix with those of an array of doubles. Each matrix line between a lower limit (from) and an upper limit (to) is multiplied by the same array, each element of the array with an element of the matrix line.
Definition at line 379 of file matrix.cpp.
References matrix, and y.
Referenced by Mult(), Event::NewCreateMatrices(), and Event::ObjCoordinates().
void Matrix::IncludeVector ()
IncludeVector. Multiplies the elements of an existing matrix with those of avector of doubles. Each matrix line is multiplied by the same vector elemet, one vector element per line.
Definition at line 397 of file matrix.cpp.
References _vector, matrix, x, and y.
void Matrix::Init (double init)
PUBLIC: Init. Initialize the matrix with the same value (usually 0)
Definition at line 160 of file matrix.cpp.
References matrix, x, and y.
Referenced by Matrix().
void Matrix::Interpol (int arraySize, double array[])
PUBLIC: INTERPOL. Given the values for a few points interpolates the values for the rest of the array
Definition at line 757 of file matrix.cpp.
References y.
Referenced by Mult().
void Matrix::Mult (int remainO, float density, int type, int durLoc, int durArray[], int stimeMatrix, int starTarray[])
MULT. Finds the most desirable duration given the density and the number of unassigned yet objects. Creates an array centered around this `peak` then multiplies the line of the existing duration matrix which corresponds to the type already chosen with the array.
Definition at line 699 of file matrix.cpp.
References IncludeArray(), Interpol(), and y.
Referenced by Event::FindDur().
void Matrix::Normalize ()
Normalize. Takes a two-dimenssional array of doubles, divides each element by the sum of all elements, and adds the value to the preceding value (sum of values) so that the last element is always 1.
Definition at line 792 of file matrix.cpp.
References matrix, x, and y.
Referenced by Event::FindDur().
double Matrix::operator() (int a, int b)
Definition at line 100 of file matrix.cpp.
References matrix.
Matrix & Matrix::operator= (Matrix & m)
PUBLIC: OPERATOR=.
Definition at line 199 of file matrix.cpp.
References _vector, Clear(), matrix, SetDim(), x, and y.
void Matrix::Print ()
Print. Prints all the elements of the matrix. Useful in testing.
Definition at line 825 of file matrix.cpp.
References matrix, x, and y.
Referenced by ChooseM(), and Event::ObjCoordinates().
void Matrix::PrintVector ()
PrintVectors. Prints a vector/array on a 8 column format.
Definition at line 845 of file matrix.cpp.
References _vector, and x.
Referenced by Event::ObjCoordinates().
void Matrix::SetDim (int x, int y)
PUBLIC: SetDim Sets the dimensions of the matrix, vector, and the probability array.
Definition at line 112 of file matrix.cpp.
References _vector, Clear(), and matrix.
Referenced by Matrix(), and operator=().
void Matrix::Smooth (int line, int slope, int start, int finish, int flag) [private]
PRIVATE: SMOOTH
If flag is 1, smooths the the matrix locations leading up to or trailing away from a sound.
Definition at line 330 of file matrix.cpp.
References matrix, and y.
Referenced by AdjustMatrix().
void Matrix::TrimMatrix (int type, float density, int remainO, int durLoc)
TRIMMATRIX. Reads in individual arrays, builds another array(s) and multiplies it/them with the first set in order to obtain a weighted mean. Resulting matrix is normalized/scaled. **This function is used only for the duration matrix and performs similar tasks as the BuildMatrix function used only for the type/attacks matrix.**
Definition at line 664 of file matrix.cpp.
References matrix, x, and y.
Referenced by Event::FindDur().
Friends And Related Function Documentation
friend class Event [friend]
Definition at line 127 of file matrix.h.
ostream& operator<< (ostream & s, Matrix & m) [friend]
PUBLIC: OPERATOR<<.
Definition at line 220 of file matrix.cpp.
Member Data Documentation
double* Matrix::_vector [private]
Definition at line 138 of file matrix.h.
Referenced by AdjustVector(), Clear(), GetVector(), IncludeVector(), Matrix(), operator=(), PrintVector(), and SetDim().
int Matrix::col
Definition at line 129 of file matrix.h.
Referenced by ChooseM(), and Event::ObjCoordinates().
double** Matrix::matrix
Definition at line 130 of file matrix.h.
Referenced by AdjustMatrix(), AdjustVector(), ChooseM(), Clear(), Envelopes(), Event::FindLen(), IncludeArray(), IncludeVector(), Init(), Matrix(), Normalize(), operator()(), operator<<(), operator=(), Print(), SetDim(), Smooth(), and TrimMatrix().
int Matrix::row
Definition at line 129 of file matrix.h.
Referenced by ChooseM(), Event::FindDur(), and Event::ObjCoordinates().
int Matrix::sever [private]
Definition at line 136 of file matrix.h.
Referenced by AdjustVector().
double* Matrix::stProb [private]
Definition at line 134 of file matrix.h.
int Matrix::x [private]
Definition at line 137 of file matrix.h.
Referenced by ChooseM(), Clear(), Envelopes(), GetVector(), GetX(), IncludeVector(), Init(), Matrix(), Normalize(), operator<<(), operator=(), Print(), PrintVector(), and TrimMatrix().
int Matrix::y [private]
Definition at line 137 of file matrix.h.
Referenced by AdjustMatrix(), AdjustVector(), ChooseM(), Clear(), Envelopes(), GetY(), IncludeArray(), IncludeVector(), Init(), Interpol(), Matrix(), Mult(), Normalize(), operator<<(), operator=(), Print(), Smooth(), and TrimMatrix().
The documentation for this class was generated from the following files:
matrix.h
matrix.cpp