Patter Class Reference
#include <patter.h>
Public Member Functions
Patter (char *aFile)
Patter (double aCheckPoint, int anOffset, char *aFile)
Patter (void)
~Patter ()
void clear ()
void Nursery (int anOrigin)
void Nursery (std::list< FileValue > args)
int Delivery (double checkPoint, int offset)
void GetPatty ()
std::list< int > getPattern (void)
Private Member Functions
void InitPat ()
void InitPat (int size, int *data)
void SimplePat ()
void InitProb ()
void Expand ()
void Expand (std::list< FileValue > args)
void Equivalence ()
void Equivalence (int modulo, int low, int high)
void Symmetries ()
void Symmetries (int modulo, int low, int high)
void Distort ()
void Distort (int modulo, int low, int high)
void Adjust ()
void Adjust (int modulo, int low, int high)
bool CheckRange (int low, int high, int element)
int Chooser (double checkPoint, int offset)
void Recorder (int fileLength)
Private Attributes
int * interArray
int * patty
int size
int offset
int origin
double checkPoint
char * fileName
Detailed Description
This class generates a pattern of values using a user defined origin and a sequence of intervals and it delivers one value at a time. Same input may be used to generate various related paterns produced through mod m equivalences, symmetrical set forms (R, I, RI), and distortions. It uses input from user defined files describing the type of object and its parameters (box, sound, etc.) as well as the pattern itself (PAT file).
Author: Sever Tipei July 14, 2005
Definition at line 46 of file patter.h.
Constructor & Destructor Documentation
Patter::Patter (char * aFile)
Constructor for (almost) empty object. File name PAT/... is necessary.
Definition at line 49 of file patter.cpp.
References fileName, interArray, patty, and size.
Patter::Patter (double aCheckPoint, int anOffset, char * aFile)
Advanced constructor.
Definition at line 60 of file patter.cpp.
References checkPoint, fileName, interArray, offset, patty, and size.
Patter::Patter (void)
Constructor for empty object. This will be used by eventfactory system for evaluating patter objects.
Definition at line 72 of file patter.cpp.
References interArray, offset, origin, patty, and size.
Patter::~Patter ()
Destructor
Definition at line 85 of file patter.cpp.
References clear().
Member Function Documentation
void Patter::Adjust (int modulo, int low, int high) [private]
Definition at line 499 of file patter.cpp.
References sever.
void Patter::Adjust () [private]
Definition at line 491 of file patter.cpp.
References sever.
Referenced by Delivery(), and Nursery().
bool Patter::CheckRange (int low, int high, int element) [private]
Checks if the new element is within the defined range.
Definition at line 508 of file patter.cpp.
Referenced by Equivalence().
int Patter::Chooser (double checkPoint, int offset) [private]
Coordinates various ways of choosing a member of the _value_ array patty.
Definition at line 516 of file patter.cpp.
References DataIn::nameOf, patty, DataIn::ReadChars(), ReadComputeFloat(), and sever.
Referenced by Delivery().
void Patter::clear ()
Deletes pointer arrays.
Definition at line 92 of file patter.cpp.
References interArray, patty, and size.
Referenced by ~Patter().
int Patter::Delivery (double checkPoint, int offset)
Delivers the pattern array patty by calling various methods. Reads from the parent file.
Definition at line 554 of file patter.cpp.
References Adjust(), Chooser(), GetPatty(), DataIn::nameOf, DataIn::ReadChars(), DataIn::ReadDummies(), and sever.
void Patter::Distort (int modulo, int low, int high) [private]
Definition at line 480 of file patter.cpp.
References sever.
void Patter::Distort () [private]
Definition at line 471 of file patter.cpp.
References sever.
Referenced by Expand().
void Patter::Equivalence (int modulo, int low, int high) [private]
Definition at line 396 of file patter.cpp.
References CheckRange(), Random::ChooseFromProb(), CumulArray(), interArray, origin, patty, and size.
void Patter::Equivalence () [private]
Finds all intervals allowed by a given range which are equivalent mod m with the initial list. The `numTerms` equivalence should not be reduced since the terms are integers.
do devise other ways of assigning probabilities to equivalence clases.
Definition at line 333 of file patter.cpp.
References CheckRange(), Random::ChooseFromProb(), CumulArray(), interArray, DataIn::intVect, origin, patty, DataIn::ReadInts(), and size.
Referenced by Expand().
void Patter::Expand (std::list< FileValue > args) [private]
Definition at line 296 of file patter.cpp.
References Distort(), Equivalence(), sever, and Symmetries().
void Patter::Expand () [private]
Coordinates various methos of expanding and/or modifying the pattern: equivalence classes, transpositions, symmetric forms (I, R, RI), distortions (augmentation, diminution, etc,), etc.
Definition at line 266 of file patter.cpp.
References Distort(), Equivalence(), DataIn::nameOf, DataIn::ReadChars(), sever, and Symmetries().
Referenced by Nursery().
std::list< int > Patter::getPattern (void)
Return a pattern object created by `Nursery` via the eventfactory interface.
Definition at line 649 of file patter.cpp.
References patty, and size.
Referenced by FileValue::Evaluate().
void Patter::GetPatty ()
Reads an existing pattern from a PAT file (at the end of the file) created by a previous Patter object and stores it in an array (patty) to be used by the current Patter object. It is called only for objects (eg. sounds) whose numbers are > 0, not by the first object in a series.
Definition at line 587 of file patter.cpp.
References DataIn::GenInts(), DataIn::gIntVect, DataIn::intVect, patty, DataIn::ReadDummies(), DataIn::ReadInts(), size, and DataIn::Skip().
Referenced by Delivery().
void Patter::InitPat (int size, int * data) [private]
Definition at line 212 of file patter.cpp.
References interArray, patty, and size.
void Patter::InitPat () [private]
Creates an empty array patty. Reads in an _interval_ pattern from a PAT file and copies it into an array of intervals which can be manipulated further.
Definition at line 191 of file patter.cpp.
References DataIn::GenInts(), DataIn::gIntVect, interArray, DataIn::intVect, patty, DataIn::ReadInts(), and size.
Referenced by Nursery().
void Patter::InitProb () [private]
Definition at line 246 of file patter.cpp.
Referenced by Nursery().
void Patter::Nursery (std::list< FileValue > args)
Definition at line 143 of file patter.cpp.
References Adjust(), Expand(), InitPat(), InitProb(), sever, SimplePat(), and size.
void Patter::Nursery (int anOrigin)
Coordinates the creation of a new pattern from data in a PAT file by calling various methods. Records the new pattern at the end of the PAT file. It is called only for the first object in a series of similar objects.
Definition at line 101 of file patter.cpp.
References Adjust(), Expand(), InitPat(), InitProb(), DataIn::intVect, DataIn::nameOf, origin, DataIn::ReadChars(), DataIn::ReadDummies(), DataIn::ReadInts(), Recorder(), sever, and SimplePat().
Referenced by FileValue::Evaluate().
void Patter::Recorder (int fileLength) [private]
Records a pattern created by `Nursery` at the end of a PAT file. It copies the content of the PAT file up to the pattern into a buffer array, opens an output file with the same name as the original (input) file and writes first the content of the original file and then the pattern array patty. This way, if the same pattern file is used multiple times to generate similar patterns, only the record of the current patty array is kept.
Definition at line 610 of file patter.cpp.
References DataIn::buffer, fileName, patty, DataIn::ReadBuffer(), DataIn::rewindFile(), and size.
Referenced by Nursery().
void Patter::SimplePat () [private]
Creates a patty array by starting with the origin and adding to each location the next member of the interval array interArray
Definition at line 229 of file patter.cpp.
References interArray, origin, patty, and size.
Referenced by Nursery().
void Patter::Symmetries (int modulo, int low, int high) [private]
Definition at line 462 of file patter.cpp.
References sever.
void Patter::Symmetries () [private]
Definition at line 454 of file patter.cpp.
References sever.
Referenced by Expand().
Member Data Documentation
double Patter::checkPoint [private]
Definition at line 200 of file patter.h.
Referenced by Patter().
char* Patter::fileName [private]
Definition at line 202 of file patter.h.
Referenced by Patter(), and Recorder().
int* Patter::interArray [private]
Definition at line 194 of file patter.h.
Referenced by clear(), Equivalence(), InitPat(), Patter(), and SimplePat().
int Patter::offset [private]
Definition at line 198 of file patter.h.
Referenced by Patter().
int Patter::origin [private]
Definition at line 199 of file patter.h.
Referenced by Equivalence(), Nursery(), Patter(), and SimplePat().
int* Patter::patty [private]
Definition at line 195 of file patter.h.
Referenced by Chooser(), clear(), Equivalence(), getPattern(), GetPatty(), InitPat(), Patter(), Recorder(), and SimplePat().
int Patter::size [private]
Definition at line 197 of file patter.h.
Referenced by clear(), Equivalence(), getPattern(), GetPatty(), InitPat(), Nursery(), Patter(), Recorder(), and SimplePat().
The documentation for this class was generated from the following files:
patter.h
patter.cpp