utility.h File Reference
#include <iostream>
#include <fstream>
#include `../../LASS/src/Envelope.h`
#include `linkList.h`
#include `filevalue.h`
Functions
int ValuePick (double checkPoint, float absRange)
int valuePick (double checkpoint, float absRange, Envelope *envLow, Envelope *envHigh, Envelope *envDist, const char *eMethod, vector< int > eArgVect, const char *wMethod, vector< int > wArgVect, const char *modifyMethod)
float ValueFloat (double checkPoint, int envNum[], float coef[])
float ValueFloat (double checkPoint, vector< int > envNum, vector< float > coef)
double Choose (double from, double to)
void CumulArray (double array[], int size)
void CumulWeights (List< double > &aList)
int ChooseL (List< double > &aList, List< int > &bList)
float Stochos (double checkPoint, int offset)
float Stochos (double checkPoint, int offset, const char *method, vector< int > envNums, vector< float > scale)
float Stochos (double checkPoint, int offset, const char *method, vector< Envelope * > envNums)
int ReadComputeInt (double checkPoint, int offset)
float ReadComputeFloat (double checkPoint, int offset)
void NonReadCompute ()
string ReadComputeChars (double checkPoint, int offset)
int FrequencyStep (double checkPoint, int newObj, int type, char *keepName)
Envelope * EnvelopeBuilder (char *method, Collection< xy_point > *xy_pts, Collection< envelope_segment > *segs, double checkPoint, int offset, double check, int envNum)
Envelope * EnvelopeBuilder (char *method, Collection< xy_point > *xy_pts, Collection< envelope_segment > *segs, double checkPoint, int offset, double check, int envNum, int numSegs)
float envValue (double checkPoint, int envNum, float coef)
Envelope * FitEnvelope (double checkPoint, int offset)
Envelope * SelectEnvType (double checkPoint, int newObj, int type, double check, int offset, char *fileName)
Envelope * MakeEnvelope (double checkPoint, int offset, double check)
Envelope * SegmentBuilder (double check)
void NonEnv ()
int ChooseOffset (int first, int second)
float Sequence (int offset)
string CharSequence (int offset)
float SoundsPerSec (float dens)
float SoundsPerSec (float dens, int areas, int underOne)
void GSection (List< int > &aList, int levels)
double RandomSource ()
double RandRange (float low, float high)
double RandomTri (float low, float high)
float PreferedValueDistribution (float value, double checkPoint)
bool Chance (int goFlag, double checkPoint, int offset)
bool Chance (double checkPoint, Envelope *chanceEnv)
double Randomizer ()
int ChooseA (double probs[], int size)
float ChooseFromList (float array[], int size)
void FlatDistribution (List< double > &aProbList)
int RandomNumber (int lowNum, int highNum)
void Weights (double probArray[], int listLen)
void Clear (double probArray[], int arraySize)
double Exponential (int step, double extra)
float Sum (double array[], int size)
void Normalize (double array[], int size)
void TestLibrary ()
void * Evaluate (FileValue *value)
FileValue Select (std::list< FileValue > l, int n)
Variables
double * probArray
int sever
Function Documentation
bool Chance (double checkPoint, Envelope * chanceEnv)
Definition at line 1558 of file utility.cpp.
References Random::Rand().
Referenced by Bottom::Modifiers(), Bottom::Reverberation(), and Bottom::Spatialization().
bool Chance (int goFlag, double checkPoint, int offset)
Returns a value of TRUE or FALSE for the comparison: randomNumber <= probability and it is used to force one of these values. The goFlag is initialized to 0 for the first time Chance is called. If the probability (which is read in) has the value of -1 (< 0), it is assigned the value of the goFlag (either 0 or 1) thus influencing the outcome of the next call. The value of 1 is assigned (in the calling function, not in here) if the comparison was successful (TRUE). If 0 < probability < 1 the outcome depends of the comparison with randomNumber. If the probability > 1 it becomes 0 if goFlag = 1, i.e. if a similar param has already been assigned.
In the case of parameters which are dependent of one another, the first (influencing) parameter should have a probability assigned while the subsequent (dependent) parameters should be assigned a value < 0.
In the case of competing aspects of the same parameter (e.g. glissando and detuning) the second one is selected ONLY if the first one was not.
Parameters:
goFlag
checkPoint
offset
Returns: The result of the comparison
Definition at line 1517 of file utility.cpp.
References EnvelopeBuilder(), and Random::Rand().
string CharSequence (int offset)
This function returns the value of the (n)th element in a sequence of chars
Parameters:
The offset to use
Returns: The value of the (n)th element
Definition at line 1350 of file utility.cpp.
References DataIn::GenChars(), DataIn::intVect, DataIn::nameOf, and DataIn::ReadInts().
double Choose (double from, double to)
This function chooses a random number in the given range (from-to)
Parameters:
from Bottom(p.) of the range
to Top(p.) of the range
Definition at line 209 of file utility.cpp.
References Random::Rand().
int ChooseA (double probs[], int size)
This function chooses a value out of an array of probabilites
Parameters:
probs The array of probabilites
size The size of the array
Returns: The chosen value
Definition at line 1607 of file utility.cpp.
References Random::Rand().
float ChooseFromList (float array[], int size)
This function chooses a value from a list of floats.
Parameters:
array The array of floats
size The size of the array
Returns: The chosen value
Definition at line 1629 of file utility.cpp.
References Random::Rand().
int ChooseL (List< double > & aList, List< int > & bList)
This function chooses an element from a list of integers by matching its probability of occurence stored in a corresponding list of doubles with a random number.
Parameters:
bList The list of integers
aList The list of doubles
Definition at line 272 of file utility.cpp.
References List< Etype >::Head(), List< Etype >::Length(), Random::Rand(), and List< Etype >::Retrieve().
int ChooseOffset (int first, int second)
This function chooses an appropriate offset based on what is read in.
Parameters:
first This argument is newObj in most cases
second This argument is type in most cases
Returns: The offset
Definition at line 1295 of file utility.cpp.
Referenced by Event::Continuum3(), Event::NumObjs(), Bottom::OneStep(), and Event::Sweep3().
void Clear (double probArray[], int arraySize)
This function clears the probability array.
Parameters:
probArray The array of probabilites
arraySize The size of the array
Definition at line 1734 of file utility.cpp.
References probArray.
void CumulArray (double array[], int size)
This function takes an array of doubles, divides each element by the sum of all elements, and adds the value to the preceding value (sum of values) so that the values range from 0 to 1.
Parameters:
array An array of doubles
size
Definition at line 226 of file utility.cpp.
References Normalize().
Referenced by Patter::Equivalence().
void CumulWeights (List< double > & aList)
This function takes each weight on the list, divides it by the sum and then adds it to a cumulative weight or probability.
Parameters:
aList A list of weights
Definition at line 247 of file utility.cpp.
References List< Etype >::Head(), List< Etype >::Length(), List< Etype >::Normalize(), List< Etype >::Retrieve(), and List< Etype >::Update().
Envelope* EnvelopeBuilder (char * method, Collection< xy_point > * xy_pts, Collection< envelope_segment > * segs, double checkPoint, int offset, double check, int envNum, int numSegs)
This function serves as a wrapper for the constructors of Envelope from LASS. This combines the previous utility methods of FitEnvelope, SelectEnvType, MakeEnvelope, and SegmentBuilder
Parameters:
method A string to determine which method of creating the envelope will be usedPossible values are: SEG_BUILDER, SEGS_AND_POINTS, FROM_LIB_SCALE, FROM_LIB_NUM
xy_pts A collection of xy_points
segs A collection of envelope segements
checkPoint
offset
check
envNum The number of the envelope to load from the library
numSegs The number of segments
Returns: An Envelope
Author: Chris Ham
Referenced by Chance(), Bottom::Modifiers(), Bottom::OneStep(), and ValueFloat().
Envelope* EnvelopeBuilder (char * method, Collection< xy_point > * xy_pts, Collection< envelope_segment > * segs, double checkPoint, int offset, double check, int envNum)
METHOD: SEGMENT BUILDER /////////////////////////////
METHOD: SEGMENTS AND POINTS /////////////////////////////////
METHOD: LOAD FROM LIBRARY ///////////////////////////////////
Definition at line 672 of file utility.cpp.
References envlib, DataIn::fileLoc(), DataIn::GenInts(), DataIn::gIntVect, ReadComputeChars(), ReadComputeFloat(), ReadComputeInt(), and DataIn::rewindFile().
float envValue (double checkPoint, int envNum, float coef)
This function finds the value of an envelope at a given point. The envelope is loaded first (from an Envelope library) and then scaled according to a given coefficient.
Parameters:
checkPoint The point at which to check the envelope
envNum The number of the envelope to load from the library
coef The coefficient by which to scale the envelope
Returns: The value of the envelope at the specified point
Note: THIS METHOD WILL SOON BE DEPRECATED. USE Envelope::GetScaledValue INSTEAD.
Definition at line 1024 of file utility.cpp.
References envlib.
void* Evaluate (FileValue * value)
Definition at line 1828 of file utility.cpp.
References FileValue::getNumber(), FileValue::getString(), FileValue::isList(), FileValue::isNumber(), and FileValue::isString().
double Exponential (int step, double extra)
This function is the inverse exponential function to allow for an extra term (random) deviation.
Parameters:
step
extra
Definition at line 1746 of file utility.cpp.
Referenced by Bottom::Rules().
Envelope* FitEnvelope (double checkPoint, int offset)
This function fits (scales) an envelope by a computed coefficient.
Parameters:
checkPoint
offset
Returns: An Envelope
Note: THIS METHOD WILL SOON BE DEPRECATED. USE Envelope::FitEnvelope(p.) INSTEAD.
void FlatDistribution (List< double > & aProbList)
This function assigns even probabilities to a list.
Parameters:
aProblist A list of probabilities
int FrequencyStep (double checkPoint, int newObj, int type, char * keepName)
This function is used to find discrete values of a defined tuning
Parameters:
checkPoint
newObj
type
keepName
void GSection (List< int > & aList, int levels)
This function partitions a segment into golden mean ratios at multiple levels.
Parameters:
aList
levels
Definition at line 1420 of file utility.cpp.
References List< Etype >::Head(), List< Etype >::InsertInOrder(), and List< Etype >::Retrieve().
Referenced by Event::Stimes().
Envelope* MakeEnvelope (double checkPoint, int offset, double check)
This function makes an envelope.
Parameters:
checkPoint
offset
check
Returns: A pointer to an Envelope
Note: THIS METHOD WILL SOON BE DEPRECATED. USE Utility::EnvelopeBuilder(p.) INSTEAD. Use method = SEG_BUILDER with same parameters as here.
void NonEnv ()
This function skips a certain number of lines based on the method in the file.
void NonReadCompute ()
This function finds out by which method something is determined: by following a sequence, by choosing it from a list, by computing it or by picking a random value.
Definition at line 534 of file utility.cpp.
void Normalize (double array[], int size)
This function normalizes each element of the array by dividing it by the sum of the array.
Parameters:
array The array
size The size of the array
Definition at line 1782 of file utility.cpp.
References Sum().
Referenced by CumulArray(), and Sieve::CumulArray().
float PreferedValueDistribution (float value, double checkPoint)
This function generates a probability
Parameters:
value
checkPoint
Returns: A probability
Definition at line 1496 of file utility.cpp.
Referenced by Sieve::AddEnvelope().
double Randomizer ()
This function computes a positive or negative percentage to be added to a value calculated through some other method.
Returns: The positive or negative percentage
int RandomNumber (int lowNum, int highNum) [static]
This function returns a random integer between lowNum and highNum.
Parameters:
lowNum The lower number
highNum The higher number
Returns: A random integer between lowNum and highNum
double RandomSource ()
This function is a generic method for generating random numbers between 0 and 1 using a flat distribution.
Returns: A random number between 0 and 1
double RandomTri (float low, float high)
This function generates a random number with a triangular distribution
Parameters:
low The minimum of the range
high The maximum of the range
Returns: A random number within the specified range
double RandRange (float low, float high)
This function generates a random number within a range (low to high) using a flat distribution.
Parameters:
low The minimum of the range
high The maximum of the range
Returns: A random number within the specified range
string ReadComputeChars (double checkPoint, int offset)
This function finds out by which method a character value is determined: by reading it, by following a equence, by computing it using ValuePick, or by picking a random value within a given range.
Parameters:
checkPoint
offset
Definition at line 563 of file utility.cpp.
Referenced by EnvelopeBuilder().
float ReadComputeFloat (double checkPoint, int offset)
This function finds out by which method a float value is determined: by following a sequence, by computing it using Stochos, or by picking a random value within a given range.
Parameters:
checkPoint
offset
Definition at line 496 of file utility.cpp.
Referenced by Patter::Chooser(), Event::Continuum3(), EnvelopeBuilder(), Event::NumObjs(), and Event::Sweep3().
int ReadComputeInt (double checkPoint, int offset)
This function finds out by which method an integer value is determined: by reading it, by following a sequence, by computing it using ValuePick, or by picking a random value within a given range.
Parameters:
checkPoint
offset
Definition at line 458 of file utility.cpp.
Referenced by Event::Continuum3(), EnvelopeBuilder(), Bottom::Modifiers(), Event::NumObjs(), and Event::Sweep3().
Envelope* SegmentBuilder (double check)
This function builds an envelope from scratch by creating a colllection of points (x,y) and a collection of segments. The xy collection is created with ReadComputeFloat calling Sequence; instead of the usual double checkPoint showing the point in time when the selection is made, the variable check (double) is used to indicate the position of this particular envelope between the rest of the enveloopes (as a); the second parameter is the segment number. The file location is remembered and we return to it at the end of the loop to take care of the next segment, build from the same data.
Parameters:
check
Returns: A pointer to an Envelope
Note: THIS METHOD WILL SOON BE DEPRECATED. USE Utility::EnvelopeBuilder(p.) INSTEAD. Use method = SEG_BUILDER with same parameters as here.
FileValue Select (std::list< FileValue > l, int n)
Definition at line 1856 of file utility.cpp.
Referenced by Note::AssignLoudness(), Note::AssignPitch(), and FileValue::Evaluate().
Envelope* SelectEnvType (double checkPoint, int newObj, int type, double check, int offset, char * fileName)
This function creates an envelope based on the given method.
Parameters:
checkPoint
newObj
type
check
offset
fileName
Returns: A pointer to an Envelope
Note: THIS METHOD WILL SOON BE DEPRECATED. USE Utility::EnvelopeBuilder(p.) INSTEAD. Use method = SEG_BUILDER -OR- FROM_LIBRARY
float Sequence (int offset)
This function returns the value of the (n)th element in a sequence of floats
Parameters:
The offset to use
Returns: The value of the (n)th element
Definition at line 1330 of file utility.cpp.
References DataIn::GenFloats(), DataIn::gFloatVect, DataIn::intVect, and DataIn::ReadInts().
Referenced by Bottom::ThreeStep().
float SoundsPerSec (float dens, int areas, int underOne)
Definition at line 1401 of file utility.cpp.
Referenced by Event::NewNumObjs(), and Event::NumObjs().
float SoundsPerSec (float dens)
This function maps an `abstract` density of 0 - 1 onto a number of sounds per second by defining a total number of regions (areas) and the number of such areas with less than 1 sound/sec. (underOne). A common example:
areas 0 1 2 3 4 5 6 7 dens. 0.00 0.125 0.250 0.375 0.500 0.625 0.750 0.875 1.00 s/sec 1/16 1/8 1/4 1/2 1 2 4 8 16
Here, there are 8 areas (0-7) and 4 of them (0-3) include values of less than 1 sound/sec. By subtracting underOne, a dens = 0 is mapped onto a value of 1 sound every 16 sec. and not onto 0.
In most cases areas = 8 and underOne = 4 like in the above example.
Parameters:
dens The density
Returns: Number of sounds per second
Definition at line 1372 of file utility.cpp.
float Stochos (double checkPoint, int offset, const char * method, vector< Envelope * > envNums)
Definition at line 385 of file utility.cpp.
References Random::Rand().
Referenced by FileValue::Evaluate().
float Stochos (double checkPoint, int offset, const char * method, vector< int > envNums, vector< float > scale)
float Stochos (double checkPoint, int offset)
Stochos. Reads 3 envelope numbers and 3 scaling factors and chooses a value using utility methods ValueFloat and envValue. The `offset` points to the triplet needed at this moment given that there might be more than one type of elemets to be considered (such as 2,3,5 etc. types in a layer).
Parameters:
checkPoint
offset
float Sum (double array[], int size)
This function calculates the sum of the elements of the array.
Parameters:
array The array
size The size of the array
Definition at line 1763 of file utility.cpp.
Referenced by Normalize().
void TestLibrary ()
This function is used for testing purposes.
Definition at line 1798 of file utility.cpp.
References envlib, and sever.
float ValueFloat (double checkPoint, vector< int > envNum, vector< float > coef)
Definition at line 169 of file utility.cpp.
References EnvelopeBuilder(), and Random::Rand().
float ValueFloat (double checkPoint, int envNum[], float coef[])
This function assigns a float value to a parameter. It uses three envelopes and three scale factors: two to find the min and max values at a given time (checkPoint) and the third ones to define a distribution over this range.
Parameters:
checkPoint The given time
envNum An array of envelope numbers
coef An array of coefficients by which to scale the envelope
Definition at line 133 of file utility.cpp.
References EnvelopeBuilder(), and Random::Rand().
int valuePick (double checkpoint, float absRange, Envelope * envLow, Envelope * envHigh, Envelope * envDist, const char * eMethod, vector< int > eArgVect, const char * wMethod, vector< int > wArgVect, const char * modifyMethod)
Definition at line 103 of file utility.cpp.
References Sieve::Build(), and Sieve::Modify().
Referenced by FileValue::Evaluate().
int ValuePick (double checkPoint, float absRange)
This function finds the lower and upper limits for a set of values at a given time (checkPoint). This is done by finding the values of envelopes for the min and max limits at the checkPoint. Builds a list of possible values within this range and assigns probabilities to them according to both a sieve and another envelope. Picks a value off a list of possible values (elements) by matching its weight or probability to a random number.
Parameters:
checkPoint The given time
absRange
Returns: A value from the list of possible values
Definition at line 58 of file utility.cpp.
Referenced by Event::Sweep3(), and Bottom::ThreeStep().
void Weights (double probArray[], int listLen)
This function assigns probabilities according to a list provided by the user.
The HIERARCHIC option adds the weights associated with individual moduli to the same sieve element. Thus, the same element (eg. attack point) can have a weight which is the sum of a number of moduli, each with its own weight (probability).
The PERIODIC option cycles through the available weights creating a meter- like pattern.
Parameters:
probArray An array of probabilities
listLen The length of the list
Variable Documentation
double* probArray
Definition at line 450 of file utility.h.
Referenced by Clear().
int sever
Definition at line 490 of file utility.h.
Referenced by Patter::Adjust(), Event::BuildSubEvents(), Patter::Chooser(), Patter::Delivery(), Patter::Distort(), Event::DurationMethods(), Sieve::Elements(), FileValue::Evaluate(), Patter::Expand(), Event::NewAttackMethods(), Event::NewDurationMethods(), Event::NewNumObjs(), Event::NumObjs(), Bottom::NumPart(), Patter::Nursery(), Event::PointsProbs(), Bottom::Rules(), Bottom::Spatialization(), Bottom::Spectrum(), Event::Sweep3(), Patter::Symmetries(), TestLibrary(), Event::TestNameType(), Bottom::ThreeStep(), and Sieve::Weights().