.TH "define.h" 3 "12 Feb 2007" "CMOD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
define.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <cmath>\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBDEBUG\fP   cout"
.br
.ti -1c
.RI "#define \fBNYQUIST\fP   22050.0L"
.br
.ti -1c
.RI "#define \fBCEILING\fP   15000.0L"
.br
.ti -1c
.RI "#define \fBMINFREQ\fP   20.0L"
.br
.ti -1c
.RI "#define \fBTRUE\fP   1"
.br
.ti -1c
.RI "#define \fBFALSE\fP   0"
.br
.ti -1c
.RI "#define \fBPI\fP   4.0*atan(1.0)"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef int \fBBOOL\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const  double \fBGOLDENMEAN\fP = 0.618"
.br
.ti -1c
.RI "const  float \fBMIN_AUD_FREQ\fP = 20."
.br
.ti -1c
.RI "const  float \fBMAX_AUD_FREQ\fP = 20000."
.br
.ti -1c
.RI "const  float \fBFUNDAMENTAL\fP = 13.75"
.br
.ti -1c
.RI "const  double \fBC0\fP = 16.351597"
.br
.ti -1c
.RI "const  double \fBWELL_TEMP_INCR\fP = pow(2, 1./12.)"
.br
.ti -1c
.RI "const  float \fBMAX_SONES\fP = 256."
.br
.ti -1c
.RI "const  float \fBFIRST_CONST\fP = -5.54"
.br
.ti -1c
.RI "const  float \fBSECOND_CONST\fP = -1.84"
.br
.ti -1c
.RI "const  int \fBSAMPLING_RATE\fP = 44100"
.br
.ti -1c
.RI "const  int \fBDEFAULT_START_TIME\fP = 0"
.br
.ti -1c
.RI "const  int \fBDEFAULT_DURATION\fP = 1"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define CEILING   15000.0L"
.PP
Definition at line 46 of file define.h.
.PP
Referenced by Bottom::buildSound(), FileValue::Evaluate(), Bottom::NumPart(), and Bottom::SetFrequency().
.SS "#define DEBUG   cout"
.PP
Definition at line 40 of file define.h.
.SS "#define FALSE   0"
.PP
Definition at line 49 of file define.h.
.SS "#define MINFREQ   20.0L"
.PP
Definition at line 47 of file define.h.
.PP
Referenced by Bottom::buildSound(), FileValue::Evaluate(), and Bottom::SetFrequency().
.SS "#define NYQUIST   22050.0L"
.PP
Definition at line 45 of file define.h.
.SS "#define PI   4.0*atan(1.0)"
.PP
Definition at line 50 of file define.h.
.SS "#define TRUE   1"
.PP
Definition at line 48 of file define.h.
.SH "Typedef Documentation"
.PP 
.SS "typedef int \fBBOOL\fP"
.PP
Definition at line 36 of file define.h.
.SH "Variable Documentation"
.PP 
.SS "const double \fBC0\fP = 16.351597\fC [static]\fP"
.PP
Definition at line 65 of file define.h.
.SS "const int \fBDEFAULT_DURATION\fP = 1\fC [static]\fP"
.PP
Definition at line 75 of file define.h.
.SS "const int \fBDEFAULT_START_TIME\fP = 0\fC [static]\fP"
.PP
Definition at line 74 of file define.h.
.SS "const float \fBFIRST_CONST\fP = -5.54\fC [static]\fP"
.PP
Definition at line 69 of file define.h.
.SS "const float \fBFUNDAMENTAL\fP = 13.75\fC [static]\fP"
.PP
Definition at line 64 of file define.h.
.SS "const double \fBGOLDENMEAN\fP = 0.618\fC [static]\fP"
.PP
Definition at line 61 of file define.h.
.SS "const float \fBMAX_AUD_FREQ\fP = 20000.\fC [static]\fP"
.PP
Definition at line 63 of file define.h.
.SS "const float \fBMAX_SONES\fP = 256.\fC [static]\fP"
.PP
Definition at line 68 of file define.h.
.SS "const float \fBMIN_AUD_FREQ\fP = 20.\fC [static]\fP"
.PP
Definition at line 62 of file define.h.
.SS "const int \fBSAMPLING_RATE\fP = 44100\fC [static]\fP"
.PP
Definition at line 71 of file define.h.
.SS "const float \fBSECOND_CONST\fP = -1.84\fC [static]\fP"
.PP
Definition at line 70 of file define.h.
.SS "const double \fBWELL_TEMP_INCR\fP = pow(2, 1./12.)\fC [static]\fP"
.PP
Definition at line 66 of file define.h.
.SH "Author"
.PP 
Generated automatically by Doxygen for CMOD from the source code.
