.TH "high.cpp" 3 "12 Feb 2007" "CMOD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
high.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <iomanip>\fP
.br
\fC#include 'dataIn.h'\fP
.br
\fC#include 'high.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "ofstream * \fBoutputFile\fP"
.br
.ti -1c
.RI "int \fBlowID\fP"
.br
.ti -1c
.RI "int \fBhighID\fP"
.br
.ti -1c
.RI "int \fBbottomID\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "int \fBbottomID\fP"
.PP
Definition at line 36 of file high.cpp.
.SS "int \fBhighID\fP"
.PP
Definition at line 35 of file high.cpp.
.PP
Referenced by High::High(), and High::Print().
.SS "int \fBlowID\fP"
.PP
Definition at line 34 of file high.cpp.
.PP
Referenced by High::High(), Low::Low(), and Low::Print().
.SS "ofstream* \fBoutputFile\fP"
.PP
Definition at line 32 of file high.cpp.
.SH "Author"
.PP 
Generated automatically by Doxygen for CMOD from the source code.
