.TH "List::Node" 3 "12 Feb 2007" "CMOD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
List::Node \- 
.SH SYNOPSIS
.br
.PP
\fC#include <linkList.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNode\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Etype \fBelement\fP"
.br
.ti -1c
.RI "\fBNode\fP * \fBnext\fP"
.br
.in -1c

.SS "template<class Etype> class List< Etype >::Node"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class Etype> \fBList\fP< Etype >::Node::Node ()\fC [inline]\fP"
.PP
Definition at line 169 of file linkList.h.
.PP
References List< Etype >::Node::next.
.SH "Member Data Documentation"
.PP 
.SS "template<class Etype> Etype \fBList\fP< Etype >::\fBNode::element\fP"
.PP
Definition at line 171 of file linkList.h.
.PP
Referenced by List< Etype >::Includes(), List< Etype >::InsertAfter(), List< Etype >::InsertBefore(), List< Etype >::InsertInOrder(), List< Etype >::InsertionSort(), List< Etype >::List(), List< Etype >::Max(), List< Etype >::Min(), List< Etype >::Normalize(), List< Etype >::operator=(), List< Etype >::Print(), List< Etype >::Remove(), List< Etype >::Retrieve(), List< Etype >::Scale(), List< Etype >::Sieve(), List< Etype >::Transpose(), and List< Etype >::Update().
.SS "template<class Etype> \fBNode\fP* \fBList\fP< Etype >::\fBNode::next\fP"
.PP
Definition at line 172 of file linkList.h.
.PP
Referenced by List< Etype >::Clear(), List< Etype >::Includes(), List< Etype >::InsertAfter(), List< Etype >::InsertBefore(), List< Etype >::InsertInOrder(), List< Etype >::InsertionSort(), List< Etype >::List(), List< Etype >::Node::Node(), List< Etype >::operator++(), List< Etype >::operator--(), List< Etype >::operator=(), List< Etype >::Remove(), and List< Etype >::Tail().

.SH "Author"
.PP 
Generated automatically by Doxygen for CMOD from the source code.
