.TH "low.cpp" 3 "12 Feb 2007" "CMOD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
low.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <iomanip>\fP
.br
\fC#include 'dataIn.h'\fP
.br
\fC#include 'low.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "ofstream * \fBoutputFile\fP"
.br
.ti -1c
.RI "int \fBbottomID\fP"
.br
.ti -1c
.RI "int \fBlowID\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "int \fBbottomID\fP"
.PP
Definition at line 39 of file low.cpp.
.SS "int \fBlowID\fP"
.PP
Definition at line 40 of file low.cpp.
.SS "ofstream* \fBoutputFile\fP"
.PP
Definition at line 38 of file low.cpp.
.SH "Author"
.PP 
Generated automatically by Doxygen for CMOD from the source code.
