.TH "top.cpp" 3 "12 Feb 2007" "CMOD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
top.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <iomanip>\fP
.br
\fC#include 'top.h'\fP
.br
\fC#include 'utility.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "ofstream * \fBoutputFile\fP"
.br
.ti -1c
.RI "int \fBhighID\fP = 0"
.br
.ti -1c
.RI "int \fBlowID\fP"
.br
.ti -1c
.RI "int \fBbottomID\fP"
.br
.ti -1c
.RI "int \fBsoundID\fP = 0"
.br
.ti -1c
.RI "int \fBnoteID\fP = 0"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "int \fBbottomID\fP"
.PP
Definition at line 37 of file top.cpp.
.SS "int \fBhighID\fP = 0"
.PP
Definition at line 35 of file top.cpp.
.PP
Referenced by High::High(), and High::Print().
.SS "int \fBlowID\fP"
.PP
Definition at line 36 of file top.cpp.
.SS "int \fBnoteID\fP = 0"
.PP
Definition at line 39 of file top.cpp.
.SS "ofstream* \fBoutputFile\fP"
.PP
Definition at line 33 of file top.cpp.
.SS "int \fBsoundID\fP = 0"
.PP
Definition at line 38 of file top.cpp.
.SH "Author"
.PP 
Generated automatically by Doxygen for CMOD from the source code.
