DynamicVariableSequence Class Reference
#include <DynamicVariableSequence.h>
Public Member Functions
DynamicVariableSequence ()
Constructor - no parameters...assumes data will be given later.
DynamicVariableSequence (DynamicVariableSequence &dvs)
Constructor - no parameters...assumes data will be given later.
DynamicVariableSequence (Collection< xy_point > xyPoints, Collection< envelope_segment > segments)
~DynamicVariableSequence ()
DynamicVariableSequence * clone ()
m_value_type getValue (m_time_type time, m_time_type totalTime)
void Print ()
void DefineShape (Collection< xy_point > xyPoints, Collection< envelope_segment > segments)
void AddToShape (Collection< xy_point > xyPoints, Collection< envelope_segment > segments)
void AddToShape (DynamicVariableSequence *shape)
Collection< xy_point > * getPoints ()
Collection< envelope_segment > * getSegments ()
void setSegment (int index, envelope_segment segment)
envelope_segment getSegment (int index)
void setPoint (int index, xy_point point)
xy_point getPoint (int index)
void addPoint (xy_point point)
void addSegment (envelope_segment segment)
m_time_type getSegmentTime (int index)
void setSegmentTime (int index, m_time_type time)
stretch_type getSegmentTimeType (int index)
void setSegmentTimeType (int index, stretch_type timeType)
interpolation_type getSegmentInterpolationType (int index)
void setSegmentInterpolationType (int index, interpolation_type interType)
Iterator< m_value_type > valueIterator ()
void scale (m_value_type factor)
m_value_type getMaxValue ()
void xml_print (ofstream &xmlOutput, list< DynamicVariable * > &dynObjs)
void xml_print (ofstream &xmlOutput)
void xml_read (XmlReader *xml, char *tagname)
Private Member Functions
void addInterpolators (m_rate_type rate)
void generateTimes (m_time_type totalTime)
bool checkValidSegmentIndex (int index)
bool checkValidPointIndex (int index)
Private Attributes
Collection< xy_point > * xyPoints_
Collection< envelope_segment > * segments_
Collection< Interpolator * > * interpolators_
Collection< m_time_type > * generatedSegmentTimes_
m_time_type totalTime_
m_rate_type currentInterpolatorRate_
Detailed Description
This class is designed to `put together` several DynamicVariables that then act as a single DynamicVariable. This allows easy combining of shapes for sounds defined by DynamicVariables to make bigger shapes. It also adds the ability to specify whether a particular DynamicVariable plays for a fixed amount of time or for a percentage of time available. For each DynamicVariableSequenceEntry that is stored in the DynamicVariableSequence, the user specifies how long the Entry will play for. Checking is done to ensure that if invalid input is given, the values are adjusted accordingly. The sampledvs*.cpp files in the samples directory demonstrate how checking is done.
As demonstrated in the sample files, the values for a fixed amount of time are the amount of time that this DynamicVariableSequenceEntry will play for, and the only reason that it would not play for this much time is if the sound that it is a shape for does not play for that much time. In this case, the amount of time will get scaled to fill up the whole time available.
Also demonstrated in the sample files are the ways that flexible time is assigned. Basically, all values for flexible time are relative to one another. This is easiest explained by examples:
DynamicVariableSequence A will play for 10 seconds and has 3 Entries:
Entry 1 uses flexible time with a value of 0.1 as a `percentage.`
Entry 2 uses flexible time with a value of 0.4 as a `percentage.`
Entry 3 uses flexible time with a value of 0.5 as a `percentage.`
DynamicVariableSequence B will play for 10 seconds and has 3 Entries:
Entry 1 uses flexible time with a value of 10 as a `percentage.`
Entry 2 uses flexible time with a value of 40 as a `percentage.`
Entry 3 uses flexible time with a value of 50 as a `percentage.`
DynamicVariableSequence C will play for 10 seconds and has 3 Entries:
Entry 1 uses flexible time with a value of 20 as a `percentage.`
Entry 2 uses flexible time with a value of 80 as a `percentage.`
Entry 3 uses flexible time with a value of 100 as a `percentage.`
Since all the `percentage` values are relative to one another, these will all define the same shape. Thus, the value of every `percentage` is normalized to whatever value all the flexible times add up to.
Author: Jon Kishkunas
Definition at line 84 of file DynamicVariableSequence.h.
Constructor & Destructor Documentation
DynamicVariableSequence::DynamicVariableSequence ()
Constructor - no parameters...assumes data will be given later.
Definition at line 43 of file DynamicVariableSequence.cpp.
References currentInterpolatorRate_, generatedSegmentTimes_, interpolators_, segments_, totalTime_, and xyPoints_.
Referenced by clone().
DynamicVariableSequence::DynamicVariableSequence (DynamicVariableSequence & dvs)
Constructor - no parameters...assumes data will be given later.
Definition at line 54 of file DynamicVariableSequence.cpp.
References currentInterpolatorRate_, generatedSegmentTimes_, getPoints(), getSegments(), interpolators_, segments_, totalTime_, and xyPoints_.
DynamicVariableSequence::DynamicVariableSequence (Collection< xy_point > xyPoints, Collection< envelope_segment > segments)
Constructor
Parameters:
xyPoints A Collection of points
segments A Collection of information for the segments between the points
Definition at line 70 of file DynamicVariableSequence.cpp.
References currentInterpolatorRate_, DefineShape(), generatedSegmentTimes_, interpolators_, segments_, totalTime_, and xyPoints_.
DynamicVariableSequence::~DynamicVariableSequence ()
Destructor
Definition at line 87 of file DynamicVariableSequence.cpp.
References generatedSegmentTimes_, interpolators_, Collection< Interpolator * >::remove(), segments_, Collection< Interpolator * >::size(), and xyPoints_.
Member Function Documentation
void DynamicVariableSequence::addInterpolators (m_rate_type rate) [private]
This populates the private member variable with actual interpolators.
Parameters:
rate The sampling rate
Definition at line 722 of file DynamicVariableSequence.cpp.
References Collection< Interpolator * >::add(), Interpolator::addEntry(), CUBIC_SPLINE, EXPONENTIAL, generatedSegmentTimes_, Collection< xy_point >::get(), Collection< m_time_type >::get(), Collection< Interpolator * >::get(), getSegmentInterpolationType(), interpolators_, m_rate_type, m_time_type, segments_, DynamicVariable::setDuration(), DynamicVariable::setSamplingRate(), Collection< xy_point >::size(), Collection< envelope_segment >::size(), xyPoints_, and xy_point::y.
Referenced by valueIterator().
void DynamicVariableSequence::addPoint (xy_point point)
This appends a point to the end of the DVS.
Parameters:
point The point to append
Definition at line 474 of file DynamicVariableSequence.cpp.
References Collection< xy_point >::add(), and xyPoints_.
void DynamicVariableSequence::addSegment (envelope_segment segment)
This appends a segment to the end of the DVS.
Parameters:
segment The segment to append
Definition at line 481 of file DynamicVariableSequence.cpp.
References Collection< envelope_segment >::add(), and segments_.
void DynamicVariableSequence::AddToShape (DynamicVariableSequence * shape)
This appends one DVS to another.
Parameters:
shape The DVS to append to this one
Definition at line 414 of file DynamicVariableSequence.cpp.
void DynamicVariableSequence::AddToShape (Collection< xy_point > xyPoints, Collection< envelope_segment > segments)
This adds to the DVS the given point and segment descriptions.
Parameters:
xyPoints A Collection of points
segments A Collection of information about the segments between points
Definition at line 375 of file DynamicVariableSequence.cpp.
References m_time_type, and xy_point::x.
bool DynamicVariableSequence::checkValidPointIndex (int index) [inline, private]
This checks if a number is a valid index for a point.
Parameters:
index The index to check
Return values:
true Is valid
false Is not valid
Definition at line 558 of file DynamicVariableSequence.cpp.
References Collection< xy_point >::size(), and xyPoints_.
bool DynamicVariableSequence::checkValidSegmentIndex (int index) [inline, private]
This checks if a number is a valid index for a segment.
Parameters:
index The index to check
Return values:
true Is valid
false Is not valid
Definition at line 550 of file DynamicVariableSequence.cpp.
References segments_, and Collection< envelope_segment >::size().
DynamicVariableSequence * DynamicVariableSequence::clone () [virtual]
This makes a copy of this object.
Returns: A pointer to a DynamicVariableSequence
Implements DynamicVariable.
Definition at line 190 of file DynamicVariableSequence.cpp.
References DynamicVariableSequence(), segments_, and xyPoints_.
void DynamicVariableSequence::DefineShape (Collection< xy_point > xyPoints, Collection< envelope_segment > segments) [inline]
This (re)defines the DVS point and segment descriptions.
Parameters:
xyPoints A Collection of points
segments A Collection of information about the segments between points
Definition at line 349 of file DynamicVariableSequence.cpp.
Referenced by DynamicVariableSequence().
void DynamicVariableSequence::generateTimes (m_time_type totalTime) [private]
This populates the private member variable with actual times.
Parameters:
totalTime The time
Definition at line 592 of file DynamicVariableSequence.cpp.
References Collection< m_time_type >::add(), FIXED, FLEXIBLE, generatedSegmentTimes_, Collection< m_time_type >::get(), getSegmentTime(), getSegmentTimeType(), m_time_type, segments_, Collection< m_time_type >::set(), Collection< envelope_segment >::size(), and totalTime_.
Referenced by getValue(), and valueIterator().
m_value_type DynamicVariableSequence::getMaxValue () [virtual]
This returns the maximum value of all the entries.
Returns: The max value
Implements DynamicVariable.
Definition at line 802 of file DynamicVariableSequence.cpp.
References Collection< xy_point >::get(), m_value_type, Collection< xy_point >::size(), xyPoints_, and xy_point::y.
xy_point DynamicVariableSequence::getPoint (int index)
This gets a point by index.
Parameters:
index Which point to get
Returns: A point
Definition at line 466 of file DynamicVariableSequence.cpp.
References Collection< xy_point >::get(), and xyPoints_.
Referenced by getValue().
Collection< xy_point > * DynamicVariableSequence::getPoints ()
This returns the Collection of points that make up the shape.
Returns: A Collection of points
Definition at line 426 of file DynamicVariableSequence.cpp.
Referenced by DynamicVariableSequence().
envelope_segment DynamicVariableSequence::getSegment (int index)
This gets a segment by index.
Parameters:
index Which segment to get
Returns: An envelope_segment
Definition at line 450 of file DynamicVariableSequence.cpp.
References Collection< envelope_segment >::get(), and segments_.
interpolation_type DynamicVariableSequence::getSegmentInterpolationType (int index)
This gets the interpolation type for the segment with the given index. (LINEAR, EXPONENTIAL, etc).
Parameters:
index Which segment to get
Returns: The interpolation type
Definition at line 531 of file DynamicVariableSequence.cpp.
Referenced by addInterpolators(), getValue(), and Print().
Collection< envelope_segment > * DynamicVariableSequence::getSegments ()
This returns the collection of segments that make up the shape.
Returns: A Collection of segments
Definition at line 434 of file DynamicVariableSequence.cpp.
Referenced by DynamicVariableSequence().
m_time_type DynamicVariableSequence::getSegmentTime (int index)
This gets the indexed segment's time, that is, it's actual playing time (if using FIXED time) or percentage of time available (if using FLEXIBLE time).
Parameters:
index Which segment to get
Returns: the playing time
Definition at line 488 of file DynamicVariableSequence.cpp.
References Collection< envelope_segment >::get(), m_time_type, segments_, and envelope_segment::timeValue.
Referenced by generateTimes(), and Print().
stretch_type DynamicVariableSequence::getSegmentTimeType (int index)
This gets the time type for the segment with the given index
Parameters:
index Which segment to examine
Return values:
FIXED
FLEXIBLE
Definition at line 511 of file DynamicVariableSequence.cpp.
References Collection< envelope_segment >::get(), segments_, stretch_type, and envelope_segment::timeType.
Referenced by generateTimes(), and Print().
m_value_type DynamicVariableSequence::getValue (m_time_type time, m_time_type totalTime)
This gets an approximation of the value at the specified time.
Parameters:
time The time to begin looking at the value
totalTime The elapsed time to look at the value
Returns: The approximate value during that time
Definition at line 199 of file DynamicVariableSequence.cpp.
References Interpolator::addEntry(), CUBIC_SPLINE, EXPONENTIAL, generatedSegmentTimes_, generateTimes(), Collection< m_time_type >::get(), Collection< xy_point >::get(), getPoint(), getSegmentInterpolationType(), m_time_type, m_value_type, Iterator< T >::next(), DynamicVariable::setDuration(), DynamicVariable::setSamplingRate(), Collection< xy_point >::size(), Interpolator::valueIterator(), xyPoints_, and xy_point::y.
void DynamicVariableSequence::Print ()
This will give a text output for what is stored in the DVS.
Note: mainly for debugging
Definition at line 120 of file DynamicVariableSequence.cpp.
References CUBIC_SPLINE, EXPONENTIAL, FLEXIBLE, Collection< xy_point >::get(), getSegmentInterpolationType(), getSegmentTime(), getSegmentTimeType(), LINEAR, segments_, Collection< envelope_segment >::size(), xy_point::x, xyPoints_, and xy_point::y.
void DynamicVariableSequence::scale (m_value_type factor) [virtual]
This scales all Entries' values by this factor.
Parameters:
factor The factor to scale by
Implements DynamicVariable.
Definition at line 785 of file DynamicVariableSequence.cpp.
References Collection< xy_point >::get(), m_value_type, Collection< xy_point >::set(), Collection< xy_point >::size(), xy_point::x, xyPoints_, and xy_point::y.
void DynamicVariableSequence::setPoint (int index, xy_point point)
This sets a point by index.
Parameters:
index Which point to set
point The new point
Definition at line 458 of file DynamicVariableSequence.cpp.
References Collection< xy_point >::set(), and xyPoints_.
void DynamicVariableSequence::setSegment (int index, envelope_segment segment)
This sets a segment by index.
Parameters:
index Which segment to set
segment The new segment
Definition at line 442 of file DynamicVariableSequence.cpp.
References segments_, and Collection< envelope_segment >::set().
void DynamicVariableSequence::setSegmentInterpolationType (int index, interpolation_type interType)
This sets the interpolation type for the segment with the given index.
Parameters:
index Which segment to set
interType The interpolation type
Definition at line 540 of file DynamicVariableSequence.cpp.
References interpolation_type, and envelope_segment::interType.
void DynamicVariableSequence::setSegmentTime (int index, m_time_type time)
This sets the indexed segment's time.
Parameters:
index Which segment to set
time The duration of the segment
Definition at line 496 of file DynamicVariableSequence.cpp.
References Collection< envelope_segment >::get(), m_time_type, segments_, Collection< envelope_segment >::set(), and envelope_segment::timeValue.
void DynamicVariableSequence::setSegmentTimeType (int index, stretch_type timeType)
This sets the indexed segment's time type.
Parameters:
index Which segment to set
timeType The type of time to set (FIXED/FLEXIBLE)
Definition at line 519 of file DynamicVariableSequence.cpp.
References Collection< envelope_segment >::get(), segments_, Collection< envelope_segment >::set(), and envelope_segment::timeType.
Iterator< m_value_type > DynamicVariableSequence::valueIterator () [virtual]
An iterator through all the values.
Returns: An iterator
Implements DynamicVariable.
Definition at line 566 of file DynamicVariableSequence.cpp.
References addInterpolators(), currentInterpolatorRate_, generateTimes(), DynamicVariable::getDuration(), DynamicVariable::getSamplingRate(), interpolators_, and totalTime_.
void DynamicVariableSequence::xml_print (ofstream & xmlOutput) [virtual]
Deprecated This outputs an XML representation of the object to STDOUT
Implements DynamicVariable.
Definition at line 821 of file DynamicVariableSequence.cpp.
References currentInterpolatorRate_, DynamicVariable::getDuration(), DynamicVariable::getSamplingRate(), Iterator< T >::hasNext(), envelope_segment::interType, Collection< envelope_segment >::iterator(), Collection< xy_point >::iterator(), Iterator< T >::next(), segments_, envelope_segment::timeType, envelope_segment::timeValue, totalTime_, xy_point::x, xyPoints_, and xy_point::y.
void DynamicVariableSequence::xml_print (ofstream & xmlOutput, list< DynamicVariable * > & dynObjs) [virtual]
Deprecated This outputs an XML representation of the object to STDOUT
Implements DynamicVariable.
Definition at line 858 of file DynamicVariableSequence.cpp.
void DynamicVariableSequence::xml_read (XmlReader * xml, char * tagname)
Deprecated This reads the DVS from xml
Definition at line 879 of file DynamicVariableSequence.cpp.
References XmlReader::xmltag::getParamValue(), XmlReader::xmltag::isClosing, XmlReader::xmltag::name, and XmlReader::readTag().
Member Data Documentation
m_rate_type DynamicVariableSequence::currentInterpolatorRate_ [private]
This is the sampling rate with which interpolators were generated
Definition at line 307 of file DynamicVariableSequence.h.
Referenced by DynamicVariableSequence(), valueIterator(), and xml_print().
Collection<m_time_type>* DynamicVariableSequence::generatedSegmentTimes_ [private]
Time values for segments that were generated based on the stored value
Definition at line 297 of file DynamicVariableSequence.h.
Referenced by addInterpolators(), DynamicVariableSequence(), generateTimes(), getValue(), and ~DynamicVariableSequence().
Collection<Interpolator*>* DynamicVariableSequence::interpolators_ [private]
This is a Collection to hold interpolators
Definition at line 292 of file DynamicVariableSequence.h.
Referenced by addInterpolators(), DynamicVariableSequence(), valueIterator(), and ~DynamicVariableSequence().
Collection<envelope_segment>* DynamicVariableSequence::segments_ [private]
This is a Collection to hold the segment data for this DVS
Definition at line 287 of file DynamicVariableSequence.h.
Referenced by addInterpolators(), addSegment(), checkValidSegmentIndex(), clone(), DynamicVariableSequence(), generateTimes(), getSegment(), getSegmentTime(), getSegmentTimeType(), Print(), setSegment(), setSegmentTime(), setSegmentTimeType(), xml_print(), and ~DynamicVariableSequence().
m_time_type DynamicVariableSequence::totalTime_ [private]
This is the value with which the segment times were generated
Definition at line 302 of file DynamicVariableSequence.h.
Referenced by DynamicVariableSequence(), generateTimes(), valueIterator(), and xml_print().
Collection<xy_point>* DynamicVariableSequence::xyPoints_ [private]
This is a Collection to hold the x-y points that define this DVS
Definition at line 282 of file DynamicVariableSequence.h.
Referenced by addInterpolators(), addPoint(), checkValidPointIndex(), clone(), DynamicVariableSequence(), getMaxValue(), getPoint(), getValue(), Print(), scale(), setPoint(), xml_print(), and ~DynamicVariableSequence().
The documentation for this class was generated from the following files:
DynamicVariableSequence.h
DynamicVariableSequence.cpp