Track Class Reference
#include <Track.h>
Public Member Functions
Track (SoundSample *wave, SoundSample *amp=0)
Track (m_sample_count_type sampleCount, m_rate_type samplingRate=DEFAULT_SAMPLING_RATE, bool zeroData=false)
Track (const Track &t)
Track & operator= (const Track &t)
~Track ()
SoundSample & getWave ()
bool hasAmp ()
SoundSample & getAmp ()
void composite (Track &t, m_time_type startTime=0.0)
void scale (m_value_type factor)
Private Attributes
SoundSample * wave_
SoundSample * amp_
Detailed Description
A track contains a SoundSample object with sound and an optional SoundSample member that contains Amplitude data. When the track object is deleted, it also deletes the wave and amp objects.
Author: Braden Kowitz
Definition at line 42 of file Track.h.
Constructor & Destructor Documentation
Track::Track (SoundSample * wave, SoundSample * amp = 0)
This is a constructor that creates a new Track object. The passed in wave and amp objects will be deleted when the Track object is deleted. Take care.
Parameters:
wave The SoundSample that represents the wave
amp The SoundSample that represents the amplitude
Definition at line 37 of file Track.cpp.
Track::Track (m_sample_count_type sampleCount, m_rate_type samplingRate = DEFAULT_SAMPLING_RATE, bool zeroData = false)
This is a constructor that creates a empty track with a set number of samples. It optionally sets a preferred sample rate, and zeros out the data if needed.
Parameters:
sampleCount The number of samples to create
samplingRate The sampling rate
zeroData Whether to zero the data (default is false)
Definition at line 43 of file Track.cpp.
References m_rate_type, and m_sample_count_type.
Track::Track (const Track & t)
This is a copy constructor.
Parameters:
t The track to copy
Definition at line 52 of file Track.cpp.
References amp_, and wave_.
Track::~Track ()
This is the destructor.
Definition at line 84 of file Track.cpp.
References amp_, and wave_.
Member Function Documentation
void Track::composite (Track & t, m_time_type startTime = 0.0)
This function composites another wave on top of this wave. It also composites the amp values if both tracks contain amp. Specifing startTime (seconds) will shift the passed in track before composition.
Parameters:
t The Track to composite
startTime the time offset to start compositing (default is 0.0)
Definition at line 120 of file Track.cpp.
References amp_, SoundSample::composite(), hasAmp(), m_time_type, and wave_.
Referenced by Sound::render().
SoundSample & Track::getAmp ()
This function returns the amplitude SoundSample for this track. If this object does not have an amplitude track the function will return a new SoundSample object with zero entries.
Returns: The SoundSample that represents the amplitude
Note: Always call hasAmp() first!
Todo This causes a memory leak!
Definition at line 106 of file Track.cpp.
References amp_.
Referenced by Score::anticlip(), Score::channelAnticlip(), Score::channelScale(), Score::clip(), Score::scale(), Pan::spatialize(), and MultiPan::spatialize().
SoundSample & Track::getWave ()
This function returns a reference to the wave object in this track.
Returns: A SoundSample that describes the wave
Definition at line 94 of file Track.cpp.
References wave_.
Referenced by Score::anticlip(), Score::channelAnticlip(), Score::channelScale(), Score::clip(), Filter::do_filter_Track(), Reverb::do_reverb_MultiTrack(), Reverb::do_reverb_Track(), Score::scale(), Pan::spatialize(), MultiPan::spatialize(), and AuWriter::write().
bool Track::hasAmp ()
This function indicates whether this track has an amplitude SoundSample.
Return values:
true There is an amplitude SoundSample
false There is not an amplitue SoundSample
Definition at line 100 of file Track.cpp.
References amp_.
Referenced by composite().
Track & Track::operator= (const Track & t)
This is an overloaded assignment operator.
Parameters:
t The Track to assign
Definition at line 66 of file Track.cpp.
References amp_, and wave_.
void Track::scale (m_value_type factor)
This function scales an entire track by a factor.
Parameters:
factor The scaling factor
Definition at line 130 of file Track.cpp.
References amp_, m_value_type, SoundSample::scale(), and wave_.
Referenced by Spatializer::spatialize().
Member Data Documentation
SoundSample* Track::amp_ [private]
Definition at line 133 of file Track.h.
Referenced by composite(), getAmp(), hasAmp(), operator=(), scale(), Track(), and ~Track().
SoundSample* Track::wave_ [private]
Definition at line 132 of file Track.h.
Referenced by composite(), getWave(), operator=(), scale(), Track(), and ~Track().
The documentation for this class was generated from the following files:
Track.h
Track.cpp