Loudness Class Reference
#include <Loudness.h>
Static Public Member Functions
void calculate (Sound &snd, m_rate_type rate=DEFAULT_LOUDNESS_RATE)
Static Private Member Functions
int criticalBandIndex (m_value_type frequency)
Static Private Attributes
const int LOWER_BOUND = 0
const int UPPER_BOUND = 1
const int CENTROID = 2
const int BANDWIDTH = 3
const int F_FACTOR = 4
const int OFFSET = 5
const int SLOPE = 6
const double BANDS [24][7]
const int NUM_BANDS = 24
Detailed Description
This performs loudness calculations on sound objects:
STEPS:
Separate all partials into groups of critical bands.
This division is done by the partial's frequency
Find the loudest partial by virtue of it's WaveShape variable.
And thus, find the highest WaveShape value.
Calculate the Band Gamma for each critical band. [eq 2.34]
The max WaveShape from step 2 becomes the maxWaveShape here.
bandGamma = 0
for each partial
bandGamma += pow((thisWaveShape / maxWaveShape), (1.0 / log10(2.0) * this_band_b_value));
bandGamma = pow(bandGamma, (log10(2.0) * this_band_b_value));
Find the maximum band-gamma: maxGamma
Calculate the numerator needed for [eq 2.37]
gammaTotal = 0;
for each band
gammaTotal += bandGamma * this_band_f_value;
numerator = desiredSonesValue / (maxGamma + gammaTotal);
Calculate scaling factor for each partial in each of the bands.
(uses maxWaveShape & numerator)
[eq 2.37] Ls = (thisWaveShape / maxWaveShape) * numerator;
[eq 2.4] Lp = log(ls) / log(2.0) * 10.0 + 40.0;
[eq 2.13] L = (-a/b) + (1/b) * Lp
[eq 2.5] A = pow(10.0, (-1.0 * ((120.0 - L) / 20.0)));
ScalingFactor = A / thisWaveShape Phew - done!
Author: Braden Kowitz
Definition at line 79 of file Loudness.h.
Member Function Documentation
void Loudness::calculate (Sound & snd, m_rate_type rate = DEFAULT_LOUDNESS_RATE) [static]
This performs the Loudness calculation on a sound object. Basically, it looks at each partial's WAVE_SHPE, FREQUENCY, and RELATIVE_AMPLITUDE parameters. It looks at the sounds LOUDNESS parameter, and sets the LOUDNES_SCALER DynamicVariable for each partial.
Definition at line 45 of file Loudness.cpp.
References BANDS, criticalBandIndex(), DURATION, F_FACTOR, FREQUENCY, Collection< Partial >::get(), DynamicVariable::getMaxValue(), ParameterLib< PartialStaticParam, PartialDynamicParam >::getParam(), ParameterLib< SoundStaticParam, SoundDynamicParam >::getParam(), LOUDNESS, LOUDNESS_SCALAR, m_rate_type, m_sample_count_type, m_time_type, m_value_type, NUM_BANDS, RELATIVE_AMPLITUDE, DynamicVariable::setDuration(), ParameterLib< PartialStaticParam, PartialDynamicParam >::setParam(), DynamicVariable::setSamplingRate(), Collection< Partial >::size(), DynamicVariable::valueIterator(), and WAVE_SHAPE.
Referenced by Sound::render().
int Loudness::criticalBandIndex (m_value_type frequency) [static, private]
This function returns the critical band index that matches the specified frequency.
Parameters:
frequency The freqency of the band to return
Returns: The index of a CriticalBand
Definition at line 161 of file Loudness.cpp.
References BANDS, LOWER_BOUND, m_value_type, NUM_BANDS, and UPPER_BOUND.
Referenced by calculate().
Member Data Documentation
const double Loudness::BANDS [static, private]
Initial value:
 
  {
    {2.000000E+01,1.000000E+02,5.000000E+01,8.000000E+01,7.500099E-02,3.434098E+01,7.426288E-01},
    {1.000000E+02,2.000000E+02,1.500000E+02,1.000000E+02,3.000000E-01,1.102623E+01,8.863131E-01},
    {2.000000E+02,3.000000E+02,2.500000E+02,1.000000E+02,1.800000E-01,3.658798E+00,9.307306E-01},
    {3.000000E+02,4.000000E+02,3.500000E+02,1.000000E+02,1.300000E-01,6.079359E-01,9.552449E-01},
    {4.000000E+02,5.100000E+02,4.500000E+02,1.100000E+02,1.113188E-01,-1.050592E+00,9.798435E-01},
    {5.100000E+02,6.300000E+02,5.700000E+02,1.200000E+02,9.825261E-02,-1.768491E+00,9.962857E-01},
    {6.300000E+02,7.700000E+02,7.000000E+02,1.400000E+02,9.388891E-02,-1.488782E+00,9.993805E-01},
    {7.700000E+02,9.200000E+02,8.400000E+02,1.500000E+02,8.463656E-02,-7.874900E-01,1.001088E+00},
    {9.200000E+02,1.080000E+03,1.000000E+03,1.600000E+02,7.749530E-02,-2.397041E-02,9.996908E-01},
    {1.080000E+03,1.270000E+03,1.170000E+03,1.900000E+02,7.818675E-02,3.330517E-01,9.926001E-01},
    {1.270000E+03,1.480000E+03,1.370000E+03,2.100000E+02,7.454711E-02,2.924882E-01,9.866766E-01},
    {1.480000E+03,1.720000E+03,1.600000E+03,2.400000E+02,7.344415E-02,-9.319628E-02,9.820759E-01},
    {1.720000E+03,2.000000E+03,1.850000E+03,2.800000E+02,7.366146E-02,-7.555149E-01,9.725524E-01},
    {2.000000E+03,2.320000E+03,2.150000E+03,3.200000E+02,7.269603E-02,-1.368559E+00,9.559184E-01},
    {2.320000E+03,2.700000E+03,2.500000E+03,3.800000E+02,7.400790E-02,-2.310496E+00,9.405730E-01},
    {2.700000E+03,3.150000E+03,2.900000E+03,4.500000E+02,7.500003E-02,-4.106658E+00,9.374723E-01},
    {3.150000E+03,3.700000E+03,3.400000E+03,5.500000E+02,7.773245E-02,-5.443059E+00,9.383848E-01},
    {3.700000E+03,4.400000E+03,4.000000E+03,7.000000E+02,8.272464E-02,-5.612481E+00,9.440814E-01},
    {4.400000E+03,5.300000E+03,4.800000E+03,9.000000E+02,8.793907E-02,-4.374397E+00,9.618959E-01},
    {5.300000E+03,6.400000E+03,5.800000E+03,1.100000E+03,8.895339E-02,1.201688E-01,9.705871E-01},
     {6.400000E+03,7.700000E+03,7.000000E+03,1.300000E+03,8.745852E-02,6.446360E+00,9.652756E-01},
    {7.700000E+03,9.500000E+03,8.500000E+03,1.800000E+03,9.774416E-02,1.050712E+01,9.499248E-01},
    {9.500000E+03,1.200000E+04,1.050000E+04,2.500000E+03,1.074515E-01,8.187814E+00,9.339424E-01},
    {1.200000E+04,1.550000E+04,1.350000E+04,3.500000E+03,1.167188E-01,-1.822547E+00,9.533570E-01},
  }
This holds the CriticalBand data.
Definition at line 262 of file Loudness.cpp.
Referenced by calculate(), and criticalBandIndex().
const int Loudness::BANDWIDTH = 3 [static, private]
Definition at line 166 of file Loudness.h.
const int Loudness::CENTROID = 2 [static, private]
Definition at line 165 of file Loudness.h.
const int Loudness::F_FACTOR = 4 [static, private]
Definition at line 167 of file Loudness.h.
Referenced by calculate().
const int Loudness::LOWER_BOUND = 0 [static, private]
These are the indices of the Critical Band Field.
Definition at line 163 of file Loudness.h.
Referenced by criticalBandIndex().
const int Loudness::NUM_BANDS = 24 [static, private]
There are 24 critical bands *
Definition at line 175 of file Loudness.h.
Referenced by calculate(), and criticalBandIndex().
const int Loudness::OFFSET = 5 [static, private]
Definition at line 168 of file Loudness.h.
const int Loudness::SLOPE = 6 [static, private]
Definition at line 169 of file Loudness.h.
const int Loudness::UPPER_BOUND = 1 [static, private]
Definition at line 164 of file Loudness.h.
Referenced by criticalBandIndex().
The documentation for this class was generated from the following files:
Loudness.h
Loudness.cpp