LinearInterpolator Class Reference
#include <InterpolatorTypes.h>
Public Member Functions
LinearInterpolator ()
LinearInterpolator * clone ()
Iterator< m_value_type > valueIterator ()
virtual interpolation_type getType ()
Detailed Description
This is a DynamicVariable that changes over time. This linearly interpolates between a set of points ordered in time. (LinearInterpolatorEntry)
Author: Braden Kowitz
Philipp Fraund
Definition at line 45 of file InterpolatorTypes.h.
Constructor & Destructor Documentation
LinearInterpolator::LinearInterpolator ()
This is the default constructor.
Definition at line 39 of file InterpolatorTypes.cpp.
Referenced by clone().
Member Function Documentation
LinearInterpolator * LinearInterpolator::clone () [virtual]
This makes a clone of a LinearInterpolator.
Returns: A new LinearInterpolator
Implements Interpolator.
Definition at line 44 of file InterpolatorTypes.cpp.
References LinearInterpolator().
interpolation_type LinearInterpolator::getType () [virtual]
This provides an implementation to get the type of interpolator.
Returns: The interpolation type
Implements Interpolator.
Definition at line 111 of file InterpolatorTypes.cpp.
References interpolation_type, and LINEAR.
Iterator< m_value_type > LinearInterpolator::valueIterator () [virtual]
This creates an iterator over LinearInterpolators.
Returns: An iterator
Implements Interpolator.
Definition at line 53 of file InterpolatorTypes.cpp.
References InterpolatorIterator::append(), Collection< InterpolatorEntry >::get(), DynamicVariable::getDuration(), DynamicVariable::getSamplingRate(), Iterator< T >::hasNext(), Collection< InterpolatorEntry >::iterator(), m_sample_count_type, m_time_type, m_value_type, Iterator< T >::next(), Collection< InterpolatorEntry >::size(), Collection< InterpolatorEntry >::sortCollection(), InterpolatorEntry::time_, and InterpolatorEntry::value_.
The documentation for this class was generated from the following files:
InterpolatorTypes.h
InterpolatorTypes.cpp