XmlReader Class Reference
#include <XmlReader.h>
Public Member Functions
XmlReader ()
~XmlReader ()
bool openFile (char *file)
bool closeFile ()
bool readTag (xmltag *tag)
xmltagset * readXMLDocument ()
void readXMLDocument (xmltag *)
Protected Member Functions
bool fillTagBuffer ()
void dewhitespace (char *c)
Protected Attributes
FILE * fp
char * inputbuffer
char * tagbuffer
int nibuf
Constructor & Destructor Documentation
XmlReader::XmlReader ()
Definition at line 237 of file XmlReader.cpp.
References fp, inputbuffer, nibuf, tagbuffer, and XML_BUFFER_SIZE.
XmlReader::~XmlReader ()
Definition at line 248 of file XmlReader.cpp.
References closeFile(), inputbuffer, and tagbuffer.
Member Function Documentation
bool XmlReader::closeFile ()
Closes the XML file
Definition at line 270 of file XmlReader.cpp.
References fp.
Referenced by ~XmlReader().
void XmlReader::dewhitespace (char * c) [protected]
Internal function to remove excess whitespace
Definition at line 283 of file XmlReader.cpp.
Referenced by fillTagBuffer().
bool XmlReader::fillTagBuffer () [protected]
Called by readTag, this fill acutally get the tag out of the file
Definition at line 313 of file XmlReader.cpp.
References dewhitespace(), fp, inputbuffer, nibuf, tagbuffer, and XML_BUFFER_SIZE.
Referenced by readTag().
bool XmlReader::openFile (char * file)
Opens an XML file for reading
Definition at line 257 of file XmlReader.cpp.
References fp.
bool XmlReader::readTag (xmltag * tag)
The guts of the object, this gets the next tag from the file.
Definition at line 392 of file XmlReader.cpp.
References XmlReader::xmltag::destroyTag(), fillTagBuffer(), XmlReader::xmltag::isClosing, XmlReader::tagparam::next, XmlReader::xmltag::params, XmlReader::xmltag::setName(), and tagbuffer.
Referenced by readXMLDocument(), and DynamicVariableSequence::xml_read().
void XmlReader::readXMLDocument (xmltag *)
Definition at line 484 of file XmlReader.cpp.
References XmlReader::xmltagset::add(), XmlReader::xmltag::children, XmlReader::xmltag::isClosing, XmlReader::xmltag::name, readTag(), and readXMLDocument().
XmlReader::xmltagset * XmlReader::readXMLDocument ()
Definition at line 473 of file XmlReader.cpp.
References XmlReader::xmltag::children, and XmlReader::xmltag::name.
Referenced by readXMLDocument().
Member Data Documentation
FILE* XmlReader::fp [protected]
Definition at line 178 of file XmlReader.h.
Referenced by closeFile(), fillTagBuffer(), openFile(), and XmlReader().
char* XmlReader::inputbuffer [protected]
Definition at line 179 of file XmlReader.h.
Referenced by fillTagBuffer(), XmlReader(), and ~XmlReader().
int XmlReader::nibuf [protected]
Definition at line 181 of file XmlReader.h.
Referenced by fillTagBuffer(), and XmlReader().
char* XmlReader::tagbuffer [protected]
Definition at line 180 of file XmlReader.h.
Referenced by fillTagBuffer(), readTag(), XmlReader(), and ~XmlReader().
The documentation for this class was generated from the following files:
XmlReader.h
XmlReader.cpp