MultiPan Class Reference
#include <MultiPan.h>
Public Member Functions
MultiPan (int nChans)
MultiPan (int nChans, vector< Envelope * > &List)
~MultiPan ()
MultiPan * clone ()
void addEntry (float t,...)
void addEntryLocation (float t, float theta, float radius)
MultiTrack * spatialize (Track &t, int numTracks)
void xml_print (ofstream &xmlOutput)
Private Member Functions
void addEntryHelperFn (int envIdx, float t, float amp)
Private Attributes
bool useEnvDirectly
vector< Envelope * > EnvList
vector< Collection< xy_point > * > xyCollectionsList
vector< Collection< envelope_segment > * > segCollectionsList
vector< int > nPoints
int n_channels
Detailed Description
MultiPan is a Spatializer. It is to be used instead of Pan when you need to spatialize a sound over more than 2 speakers. To spatialize the sound over time you call addEntry or addEntryLocation one or more times and give a timestamp for each call.
Author: Jim Lindstrom
Definition at line 48 of file MultiPan.h.
Constructor & Destructor Documentation
MultiPan::MultiPan (int nChans)
This is a constructor. To use this constructor, you must call addEntry or addEntryLocation one or more times to set the spatialization data. Use the other constructor if you want to instead pass in a list of Interpolators (one per channel).
Parameters:
nChans The number of channels (speakers) to pan across
Definition at line 49 of file MultiPan.cpp.
References EnvList, n_channels, segCollectionsList, useEnvDirectly, and xyCollectionsList.
Referenced by clone().
MultiPan::MultiPan (int nChans, vector< Envelope * > & List)
This is a constructor. To use this constructor, pass in a list of envs (one per channel). If you want to call addEntry or addEntryLocation to set the spatialization data, use the other constructor.
Parameters:
nChans The number of channels (speakers) to pan across
List A vector of envs (nChan number of envs, to be precise). Each env will control the percent that the corresponding speaker will respond to input sound.
Definition at line 77 of file MultiPan.cpp.
References clone(), EnvList, n_channels, and useEnvDirectly.
MultiPan::~MultiPan ()
This is the destructor.
Definition at line 90 of file MultiPan.cpp.
References EnvList, segCollectionsList, and xyCollectionsList.
Member Function Documentation
void MultiPan::addEntry (float t, ...)
Add another spatialization point to the dynamic variables (using the parameters as ratios of speaker volumes). Pass in the time value, t, and a list of numbers (0.0 to 1.0 for each) that gives each speaker's response (as a percentage) to a given sound.
Parameters:
t The time stamp (as a percent of total sound length, from 0.0 to 1.0)
Definition at line 145 of file MultiPan.cpp.
References addEntryHelperFn(), n_channels, and useEnvDirectly.
void MultiPan::addEntryHelperFn (int envIdx, float t, float amp) [private]
This is a helper function used by addEntry and addEntryLocation to add a point to an env.
Definition at line 321 of file MultiPan.cpp.
References EnvList, FIXED, envelope_segment::interType, envelope_segment::lengthType, LINEAR, segCollectionsList, envelope_segment::timeValue, xy_point::x, xyCollectionsList, and xy_point::y.
Referenced by addEntry(), and addEntryLocation().
void MultiPan::addEntryLocation (float t, float theta, float radius)
Add another spatialization point to the dynamic variables using the parameters as a location within a circular array of speakers. The value theta=0 means straight ahead, positive thetas to the left, negatives to the right. The radius ranges from 0 to 1.
Parameters:
t The time stamp (as a percent of total sound length, from 0.0 to 1.0)
theta The rotation angle (in radians) where the sound will appear to originate from. An angle of zero is directly in front of you. Positive angles rotate to your left, with positive pi (3.14...) being directly behind you. Negative angles rotate to your left and negative pi (-3.14) is another name for the angle directly behind you. For reference, pi/2 is straight left and -pi/2 is straight right. To use pi, math.h defines the constant for you as 'M_PI'. For instance, you could use 'M_PI/2' to refer to the angle at your left.
radius The distance from which the sound will appear to originate from. These should range from 0.0 to 1.0.
Definition at line 190 of file MultiPan.cpp.
References addEntryHelperFn(), n_channels, and useEnvDirectly.
MultiPan * MultiPan::clone () [virtual]
This returns an exact duplicate of this MultiPan object.
Returns: An exact copy of this MultiPan object, with its own env
Reimplemented from Spatializer.
Definition at line 127 of file MultiPan.cpp.
References EnvList, MultiPan(), and n_channels.
Referenced by MultiPan().
MultiTrack * MultiPan::spatialize (Track & t, int numTracks) [virtual]
This spatializes a track and returns a new MultiTrack object with numTracks. The track will be panned accross the channels by the passed in DynamicVariable.
Parameters:
t A track to spatialize
numTracks The number of tracks to spatialize to. (This is redundant, but is kept for similarity of interface with the regular pan object. MultiPan already knows because you have to pass in nChans in the constructor)
Returns: the track, spatialized to 'numTracks' number of tracks
Reimplemented from Spatializer.
Definition at line 273 of file MultiPan.cpp.
References EnvList, Collection< Track * >::get(), Track::getAmp(), SoundSample::getSampleCount(), SoundSample::getSamplingRate(), Track::getWave(), m_rate_type, m_sample_count_type, m_value_type, n_channels, and Iterator< T >::next().
void MultiPan::xml_print (ofstream & xmlOutput) [virtual]
Deprecated
Reimplemented from Spatializer.
Definition at line 344 of file MultiPan.cpp.
Member Data Documentation
vector<Envelope*> MultiPan::EnvList [private]
Definition at line 152 of file MultiPan.h.
Referenced by addEntryHelperFn(), clone(), MultiPan(), spatialize(), and ~MultiPan().
int MultiPan::n_channels [private]
Definition at line 156 of file MultiPan.h.
Referenced by addEntry(), addEntryLocation(), clone(), MultiPan(), and spatialize().
vector<int> MultiPan::nPoints [private]
Definition at line 155 of file MultiPan.h.
vector<Collection<envelope_segment>*> MultiPan::segCollectionsList [private]
Definition at line 154 of file MultiPan.h.
Referenced by addEntryHelperFn(), MultiPan(), and ~MultiPan().
bool MultiPan::useEnvDirectly [private]
Definition at line 151 of file MultiPan.h.
Referenced by addEntry(), addEntryLocation(), and MultiPan().
vector<Collection<xy_point>*> MultiPan::xyCollectionsList [private]
Definition at line 153 of file MultiPan.h.
Referenced by addEntryHelperFn(), MultiPan(), and ~MultiPan().
The documentation for this class was generated from the following files:
MultiPan.h
MultiPan.cpp