Iterator< T > Class Template Reference
#include <Iterator.h>
Public Member Functions
Iterator (AbstractIterator< T > *it)
Iterator (const Iterator &I)
~Iterator ()
Iterator & operator= (const Iterator &I)
bool hasNext ()
T & next ()
Private Attributes
AbstractIterator< T > * it_
Detailed Description
template<class T> class Iterator< T >
This is a wrapper around an AbstractIterator pointer. This gets around C++'s polymorphic limitations. It allows for simple management of this AbstractClass.
Author: Braden Kowitz
Definition at line 42 of file Iterator.h.
Constructor & Destructor Documentation
template<class T> Iterator< T >::Iterator (AbstractIterator< T > * it) [inline]
This is a constructor.
Parameters:
it A pointer to an AbstractIterator
Definition at line 53 of file Iterator.h.
template<class T> Iterator< T >::Iterator (const Iterator< T > & I) [inline]
This is a copy constructor
Parameters:
I The iterator to make a copy of
Definition at line 61 of file Iterator.h.
template<class T> Iterator< T >::~Iterator () [inline]
This is the destructor which deletes the underlying object.
Definition at line 69 of file Iterator.h.
Member Function Documentation
template<class T> bool Iterator< T >::hasNext () [inline]
This checks whether there is another element in the iterator.
Return values:
true If there is another element
false If there is not another element
Definition at line 96 of file Iterator.h.
Referenced by MultiTrack::composite(), Filter::do_filter_MultiTrack(), Reverb::do_reverb_MultiTrack(), Interpolator::getMaxValue(), Sound::getTotalDuration(), MultiTrack::MultiTrack(), MultiTrack::operator=(), Sound::render(), Score::render(), Interpolator::scale(), Sound::setPartialParam(), CubicSplineInterpolator::valueIterator(), ExponentialInterpolator::valueIterator(), LinearInterpolator::valueIterator(), AuWriter::write(), AuWriter::write_one_per_track(), Sound::xml_print(), Score::xml_print(), Interpolator::xml_print(), Envelope::xml_print(), DynamicVariableSequence::xml_print(), and MultiTrack::~MultiTrack().
template<class T> T& Iterator< T >::next () [inline]
This returns the next iterator.
Returns: The next iterator.
Definition at line 105 of file Iterator.h.
Referenced by MultiTrack::composite(), Filter::do_filter_MultiTrack(), Reverb::do_reverb_MultiTrack(), Interpolator::getMaxValue(), Sound::getTotalDuration(), Envelope::getValue(), DynamicVariableSequence::getValue(), MultiTrack::MultiTrack(), MultiTrack::operator=(), Sound::render(), Score::render(), Interpolator::scale(), Sound::setPartialParam(), Pan::spatialize(), MultiPan::spatialize(), CubicSplineInterpolator::valueIterator(), ExponentialInterpolator::valueIterator(), LinearInterpolator::valueIterator(), AuWriter::write(), AuWriter::write_one_per_track(), Sound::xml_print(), Score::xml_print(), Interpolator::xml_print(), Envelope::xml_print(), DynamicVariableSequence::xml_print(), and MultiTrack::~MultiTrack().
template<class T> Iterator& Iterator< T >::operator= (const Iterator< T > & I) [inline]
This is an overloaded assignment operator.
Parameters:
I An iterator to assign
Definition at line 78 of file Iterator.h.
Member Data Documentation
template<class T> AbstractIterator<T>* Iterator< T >::it_ [private]
Definition at line 45 of file Iterator.h.
Referenced by Iterator< m_value_type >::hasNext(), Iterator< m_value_type >::Iterator(), Iterator< m_value_type >::next(), Iterator< m_value_type >::operator=(), and Iterator< m_value_type >::~Iterator().
The documentation for this class was generated from the following file:
Iterator.h