ExponentialInterpolator Class Reference
#include <InterpolatorTypes.h>
Public Member Functions
ExponentialInterpolator ()
ExponentialInterpolator * clone ()
Iterator< m_value_type > valueIterator ()
virtual interpolation_type getType ()
Detailed Description
This is a DynamicVariable that changes over time. This exponentially interpolates between a set of points ordered in time.
Author: Braden Kowitz
Philipp Fraund
Definition at line 81 of file InterpolatorTypes.h.
Constructor & Destructor Documentation
ExponentialInterpolator::ExponentialInterpolator ()
This is the default constructor
Definition at line 117 of file InterpolatorTypes.cpp.
Referenced by clone().
Member Function Documentation
ExponentialInterpolator * ExponentialInterpolator::clone () [virtual]
This makes a clone of a ExponentialInterpolator.
Returns: A new ExponentialInterpolator
Implements Interpolator.
Definition at line 122 of file InterpolatorTypes.cpp.
References ExponentialInterpolator().
interpolation_type ExponentialInterpolator::getType () [virtual]
This provides an implementation to get the type of interpolator.
Returns: The interpolation type
Implements Interpolator.
Definition at line 189 of file InterpolatorTypes.cpp.
References EXPONENTIAL, and interpolation_type.
Iterator< m_value_type > ExponentialInterpolator::valueIterator () [virtual]
This creates an iterator over ExponentialInterpolators.
Returns: An iterator
Implements Interpolator.
Definition at line 131 of file InterpolatorTypes.cpp.
References InterpolatorIterator::append(), Collection< InterpolatorEntry >::get(), DynamicVariable::getDuration(), DynamicVariable::getSamplingRate(), Iterator< T >::hasNext(), Collection< InterpolatorEntry >::iterator(), m_sample_count_type, m_time_type, m_value_type, Iterator< T >::next(), Collection< InterpolatorEntry >::size(), Collection< InterpolatorEntry >::sortCollection(), InterpolatorEntry::time_, and InterpolatorEntry::value_.
The documentation for this class was generated from the following files:
InterpolatorTypes.h
InterpolatorTypes.cpp