SoundSample Class Reference
#include <SoundSample.h>
Public Member Functions
SoundSample (m_sample_count_type sampleCount, m_rate_type samplingRate=DEFAULT_SAMPLING_RATE, bool zeroData=false)
SoundSample (const SoundSample &ss)
SoundSample & operator= (const SoundSample &ss)
~SoundSample ()
void setSamplingRate (m_rate_type samplingRate)
m_rate_type getSamplingRate ()
m_sample_count_type getSampleCount ()
m_sample_type & operator[] (m_sample_count_type index)
void composite (SoundSample &ss, m_time_type startTime)
void scale (m_value_type factor)
Private Attributes
m_rate_type samplingRate_
vector< m_sample_type > data_
Detailed Description
This is a sample of sound with a fixed number of individual samples. For the sake of speed, this class has no range checking. Be careful when using it as it may cause a bus error.
Author: Braden Kowitz
Definition at line 46 of file SoundSample.h.
Constructor & Destructor Documentation
SoundSample::SoundSample (m_sample_count_type sampleCount, m_rate_type samplingRate = DEFAULT_SAMPLING_RATE, bool zeroData = false)
This is a constructor which takes the number of samples and the sampling rate. It will optionally zero all the data if requested.
Parameters:
sampleCount The number of samples
samplingRate The sampling rate
zeroData Whether to zero the data (default is false)
Definition at line 52 of file SoundSample.cpp.
References data_, m_rate_type, and m_sample_count_type.
SoundSample::SoundSample (const SoundSample & ss)
This is a copy constructor.
Parameters:
ss The SoundSample to copy
Definition at line 67 of file SoundSample.cpp.
SoundSample::~SoundSample ()
This is the destructor.
Definition at line 84 of file SoundSample.cpp.
Member Function Documentation
void SoundSample::composite (SoundSample & ss, m_time_type startTime)
This function composites another SoundSample on top of this object. Both must have the same samplingRate.
Parameters:
ss The SoundSample to composite
startTime When to start applying the SoundSample
Definition at line 116 of file SoundSample.cpp.
References data_, m_sample_count_type, m_time_type, MIN_CLIP_WARNING, and samplingRate_.
Referenced by Track::composite().
m_sample_count_type SoundSample::getSampleCount ()
Each SoundSample object is created with a specified number of samples. This function returns that number.
Returns: The current number of samples
Definition at line 105 of file SoundSample.cpp.
References data_, and m_sample_count_type.
Referenced by Score::channelAnticlip(), Score::channelScale(), Score::clip(), Reverb::constructAmp(), Filter::do_filter_SoundSample(), Reverb::do_reverb_SoundSample(), Score::scale(), Pan::spatialize(), and MultiPan::spatialize().
m_rate_type SoundSample::getSamplingRate ()
This function returns the sampling rate for this SoundSample.
Returns: The current sampling rate
Definition at line 99 of file SoundSample.cpp.
References m_rate_type, and samplingRate_.
Referenced by Reverb::constructAmp(), Filter::do_filter_SoundSample(), Reverb::do_reverb_SoundSample(), Pan::spatialize(), and MultiPan::spatialize().
SoundSample & SoundSample::operator= (const SoundSample & ss)
This is an overloaded assignment operator.
Parameters:
ss The SoundSample to assign
Definition at line 73 of file SoundSample.cpp.
References data_, and samplingRate_.
]m_sample_type & SoundSample::operator[] (m_sample_count_type index)
This overloaded operator provides element access to this structure. Valid ranges are from 0 to (sampleCount-1). For efficency, this performs no range checking: be careful!
Parameters:
index Which sample to access
Note: This should be inline, but I'm having problems making it work.
Definition at line 111 of file SoundSample.cpp.
References data_, m_sample_count_type, and m_sample_type.
void SoundSample::scale (m_value_type factor)
This function scales every value in this SoundSample by a given factor.
Parameters:
factor The scaling factor
Definition at line 162 of file SoundSample.cpp.
References data_, and m_value_type.
Referenced by Track::scale().
void SoundSample::setSamplingRate (m_rate_type samplingRate)
Each sound sample stores its sampling rate. This is good information to know for composition and writing out to file. This function sets the sampling rate.
Parameters:
samplingRate The new sampling rate
Definition at line 93 of file SoundSample.cpp.
References m_rate_type, and samplingRate_.
Member Data Documentation
vector<m_sample_type> SoundSample::data_ [private]
Definition at line 132 of file SoundSample.h.
Referenced by composite(), getSampleCount(), operator=(), operator[](), scale(), and SoundSample().
m_rate_type SoundSample::samplingRate_ [private]
Definition at line 130 of file SoundSample.h.
Referenced by composite(), getSamplingRate(), operator=(), and setSamplingRate().
The documentation for this class was generated from the following files:
SoundSample.h
SoundSample.cpp