LPCombFilter Class Reference
#include <LPCombFilter.h>
Public Member Functions
LPCombFilter (float gain, long delay, float lpf_gain)
~LPCombFilter ()
m_sample_type do_filter (m_sample_type x_t)
void reset (void)
void xml_print (ofstream &xmlOutput)
LPCombFilter ()
void set_g (float new_g)
void set_D (long D)
void set_lpf_g (float new_lpf_g)
void xml_read (XmlReader::xmltag *lptag)
Private Attributes
float g
long D
float lpf_g
LowPassFilter * lpf
Filter::hist_queue< m_sample_type > * x_hist
Detailed Description
This is a comb filter with a lowpass feedback element. The comb filter class implements a comb filter with a lowpass feedback loop as described on page 385 of 'Elements of Computer Music':
y(t) = x[t-D] + g * lowpass(x(t-D))
 where lowpass(s[t]) = s[t] + coef*lowpass(s[t-1])
Note that for stability, we must make sure that: -1 < g/(1 - coef) < +1
                       ______________________
                      | |
  x(t) --->(+)------->| D-sample Delay |--------------------> y(t)
            ^ |______________________| |
            | |
            | ______________________ |
            | | | |
            |-(*g)----| IIR Lowpass Feedback |<--(+)-----|
                   | |______________________| ^
                   | |
                   |________(*coef)_______________|
Note: : This filter (and all other 'class Filter's) are stateful machines with internal feedback mechanisms. Thus this filter should be reset() each time you begin a new channel and should not be mixed between channels.
Author: Jim Lindstrom
Definition at line 74 of file LPCombFilter.h.
Constructor & Destructor Documentation
LPCombFilter::LPCombFilter (float gain, long delay, float lpf_gain)
This is a constructor.
Parameters:
gain The feedback gain (0.0 to 1.0) applied to the IIR lowpass feedback unit
delay The comb delay, in units of samples.
lpf_gain The internal gain of the lowpass feedback unit
Definition at line 43 of file LPCombFilter.cpp.
References D, Filter::hist_queue< m_sample_type >::enqueue(), g, lpf, lpf_g, and x_hist.
LPCombFilter::~LPCombFilter ()
This is the destructor.
Definition at line 59 of file LPCombFilter.cpp.
References lpf, and x_hist.
LPCombFilter::LPCombFilter ()
This constructor is used when recreating the object from an XML file when you don't know all the parameters until you've read them in. Don't use this constructor unless you intend to use the proper calls to set the gain, delay, and lpf.
Definition at line 108 of file LPCombFilter.cpp.
Member Function Documentation
m_sample_type LPCombFilter::do_filter (m_sample_type x_t) [virtual]
This method applies a lpcomb filter to a single sample
Parameters:
x_t The input sample
Returns: The filtered sample
Implements Filter.
Definition at line 66 of file LPCombFilter.cpp.
References Filter::hist_queue< m_sample_type >::dequeue(), LowPassFilter::do_filter(), Filter::hist_queue< m_sample_type >::enqueue(), g, lpf, m_sample_type, and x_hist.
Referenced by Reverb::do_reverb().
void LPCombFilter::reset (void) [virtual]
This method should be redefined by each class derived from Filter to reset the filter to an initial state. It should have the same effect as deleting the filter and creating a new one.
Implements Filter.
Definition at line 77 of file LPCombFilter.cpp.
References D, Filter::hist_queue< m_sample_type >::enqueue(), lpf, lpf_g, and x_hist.
Referenced by Reverb::reset().
void LPCombFilter::set_D (long D)
This sets the delay.
Parameters:
D The delay
Definition at line 115 of file LPCombFilter.cpp.
References D, Filter::hist_queue< m_sample_type >::enqueue(), and x_hist.
Referenced by xml_read().
void LPCombFilter::set_g (float new_g)
This sets the gain.
Parameters:
new_g The gain
Definition at line 111 of file LPCombFilter.cpp.
References g.
Referenced by xml_read().
void LPCombFilter::set_lpf_g (float new_lpf_g)
This sets the low-pass feedback.
Parameters:
new_lpf_g
Definition at line 124 of file LPCombFilter.cpp.
References lpf, and lpf_g.
Referenced by xml_read().
void LPCombFilter::xml_print (ofstream & xmlOutput)
Deprecated This outputs an XML representation of the object to STDOUT
Definition at line 93 of file LPCombFilter.cpp.
References D, g, and lpf_g.
Referenced by Reverb::xml_print().
void LPCombFilter::xml_read (XmlReader::xmltag * lptag)
Deprecated
Definition at line 132 of file LPCombFilter.cpp.
References XmlReader::xmltag::findChildParamValue(), set_D(), set_g(), and set_lpf_g().
Referenced by Reverb::xml_read().
Member Data Documentation
long LPCombFilter::D [private]
The delay for the comb component of the filter
Definition at line 152 of file LPCombFilter.h.
Referenced by LPCombFilter(), reset(), set_D(), and xml_print().
float LPCombFilter::g [private]
The gain for the comb component of the filter
Definition at line 147 of file LPCombFilter.h.
Referenced by do_filter(), LPCombFilter(), set_g(), and xml_print().
LowPassFilter* LPCombFilter::lpf [private]
This implements the lowpass-feedback portion of the filter
Definition at line 162 of file LPCombFilter.h.
Referenced by do_filter(), LPCombFilter(), reset(), set_lpf_g(), and ~LPCombFilter().
float LPCombFilter::lpf_g [private]
The gain for the lowpass-feedback component of the filter
Definition at line 157 of file LPCombFilter.h.
Referenced by LPCombFilter(), reset(), set_lpf_g(), and xml_print().
Filter::hist_queue<m_sample_type>* LPCombFilter::x_hist [private]
This queue holds past samples to implement the delay
Definition at line 167 of file LPCombFilter.h.
Referenced by do_filter(), LPCombFilter(), reset(), set_D(), and ~LPCombFilter().
The documentation for this class was generated from the following files:
LPCombFilter.h
LPCombFilter.cpp