Spatializer Class Reference
#include <Spatializer.h>
Public Member Functions
virtual MultiTrack * spatialize (Track &t, int numTracks)
virtual Spatializer * clone ()
virtual void xml_print (ofstream &xmlOutput)
Detailed Description
A Spatializer is a definition of an object that will spatalize (move around in space; this is a generalization of panning) a single sound over multiple channels. The default action of this spatializer will evenly distribute the sound over the requested number of channels. Each Spatializer must be dynamic enough to allow spatialization to a number of different channels specified at run-time.
Author: Braden Kowitz
Definition at line 48 of file Spatializer.h.
Member Function Documentation
Spatializer * Spatializer::clone () [virtual]
This function creates an exact duplicate of this Spatializer.
Reimplemented in MultiPan, and Pan.
Definition at line 61 of file Spatializer.cpp.
Referenced by Sound::setSpatializer().
MultiTrack * Spatializer::spatialize (Track & t, int numTracks) [virtual]
This will take a single Track object, and spatialize it to a MultiTrack object with numTracks tracks. The default behevior is to average the sound evenly accross all tracks.
Parameters:
t The Track to spatialize
numTracks The number of Tracks to create
Returns: a MultiTrack
Reimplemented in MultiPan, and Pan.
Definition at line 37 of file Spatializer.cpp.
References Collection< Track * >::add(), and Track::scale().
Referenced by Sound::render().
void Spatializer::xml_print (ofstream & xmlOutput) [virtual]
Deprecated
Reimplemented in MultiPan, and Pan.
Definition at line 66 of file Spatializer.cpp.
Referenced by Sound::xml_print().
The documentation for this class was generated from the following files:
Spatializer.h
Spatializer.cpp