DynamicVariableSequenceIterator Class Reference
#include <DynamicVariableSequenceIterator.h>
Public Member Functions
DynamicVariableSequenceIterator (Collection< Interpolator * > interpolators)
~DynamicVariableSequenceIterator ()
DynamicVariableSequenceIterator * clone ()
bool hasNext ()
m_value_type & next ()
Private Attributes
Collection< Interpolator * > * interpolators_
int iSegmentIndex_
Iterator< m_value_type > * currentIterator_
m_value_type currentValue_
bool moreValues_
long tempCounter_
Detailed Description
This is an iterator that interpolates over a DynamicVariableSequence. Since a DynamicVariableSequence acts like a single DynamicVariable, when we want to use it as such, we need a way to iterate through its values. That's what this does.
Author: Jon Kishkunas
Definition at line 50 of file DynamicVariableSequenceIterator.h.
Constructor & Destructor Documentation
DynamicVariableSequenceIterator::DynamicVariableSequenceIterator (Collection< Interpolator * > interpolators)
This is a constructor which initalizes some basic values.
Parameters:
interpolators
Definition at line 37 of file DynamicVariableSequenceIterator.cpp.
References currentIterator_, currentValue_, Collection< InterpolatorEntry >::get(), Collection< Interpolator * >::get(), interpolators_, iSegmentIndex_, moreValues_, Collection< InterpolatorEntry >::size(), Collection< Interpolator * >::size(), Collection< T >::size(), InterpolatorEntry::time_, and InterpolatorEntry::value_.
Referenced by clone().
DynamicVariableSequenceIterator::~DynamicVariableSequenceIterator ()
This is the destructor.
Definition at line 81 of file DynamicVariableSequenceIterator.cpp.
References currentIterator_, and interpolators_.
Member Function Documentation
DynamicVariableSequenceIterator * DynamicVariableSequenceIterator::clone () [virtual]
This makes a copy of this iterator.
Returns: A DynamicVariableSequenceIterator that is a clone of this one
Implements AbstractIterator< m_value_type >.
Definition at line 100 of file DynamicVariableSequenceIterator.cpp.
References DynamicVariableSequenceIterator().
bool DynamicVariableSequenceIterator::hasNext () [virtual]
Indicates whether the iterator has another value to return
Return values:
true If there is another value to return
false If there is not another value to return
Implements AbstractIterator< m_value_type >.
Definition at line 107 of file DynamicVariableSequenceIterator.cpp.
References moreValues_.
m_value_type & DynamicVariableSequenceIterator::next () [virtual]
Returns the next value in the iteration.
Note: Because this returns a reference type, value_ can be changed by the caller. Steps should be taken to prevent this (with a pass-to-caller member variable perhaps).
Returns: A reference to the next value in the iteration
Implements AbstractIterator< m_value_type >.
Definition at line 115 of file DynamicVariableSequenceIterator.cpp.
References currentIterator_, currentValue_, Collection< Interpolator * >::get(), Iterator< m_value_type >::hasNext(), interpolators_, iSegmentIndex_, m_value_type, moreValues_, Iterator< m_value_type >::next(), Collection< Interpolator * >::size(), tempCounter_, and Interpolator::valueIterator().
Member Data Documentation
Iterator<m_value_type>* DynamicVariableSequenceIterator::currentIterator_ [private]
This is the current DV iterator.
Definition at line 102 of file DynamicVariableSequenceIterator.h.
Referenced by DynamicVariableSequenceIterator(), next(), and ~DynamicVariableSequenceIterator().
m_value_type DynamicVariableSequenceIterator::currentValue_ [private]
This is the current value.
Definition at line 107 of file DynamicVariableSequenceIterator.h.
Referenced by DynamicVariableSequenceIterator(), and next().
Collection<Interpolator*>* DynamicVariableSequenceIterator::interpolators_ [private]
This is a Collection that holds the interpolators for all the segments.
Definition at line 92 of file DynamicVariableSequenceIterator.h.
Referenced by DynamicVariableSequenceIterator(), next(), and ~DynamicVariableSequenceIterator().
int DynamicVariableSequenceIterator::iSegmentIndex_ [private]
This is the current segment's index.
Definition at line 97 of file DynamicVariableSequenceIterator.h.
Referenced by DynamicVariableSequenceIterator(), and next().
bool DynamicVariableSequenceIterator::moreValues_ [private]
This indicates whether we have more values.
Definition at line 112 of file DynamicVariableSequenceIterator.h.
Referenced by DynamicVariableSequenceIterator(), hasNext(), and next().
long DynamicVariableSequenceIterator::tempCounter_ [private]
Definition at line 114 of file DynamicVariableSequenceIterator.h.
Referenced by next().
The documentation for this class was generated from the following files:
DynamicVariableSequenceIterator.h
DynamicVariableSequenceIterator.cpp