Interpolator Class Reference
#include <Interpolator.h>
Public Member Functions
Interpolator ()
virtual Interpolator * clone ()=0
void addEntry (m_time_type time, m_value_type value)
virtual Iterator< m_value_type > valueIterator ()=0
void scale (m_value_type scale)
m_value_type getMaxValue ()
virtual interpolation_type getType ()=0
void xml_print (ofstream &xmlOutput, list< DynamicVariable * > &dynObjs)
void xml_print (ofstream &xmlOutput)
void xml_read (XmlReader::xmltag *soundtag)
Detailed Description
This is an abstract interpolator class from which more specific interpolators (DynamicVariables used for interpolating between points) can be derived.
See InterpolatorTypes.h for interpolators.
Author: Zeke McKinney
Braden Kowitz
Philipp Fraund
Definition at line 108 of file Interpolator.h.
Constructor & Destructor Documentation
Interpolator::Interpolator ()
This is the default constructor.
Definition at line 36 of file Interpolator.cpp.
Member Function Documentation
void Interpolator::addEntry (m_time_type time, m_value_type value)
This Adds an entry to this variable. This is added for convenience - this way, a user does not have to deal with InterpolatorEntry objects when simply creating an Interpolator.
Parameters:
time The time of the new entry
value The value of the new entry
Definition at line 42 of file Interpolator.cpp.
References Collection< InterpolatorEntry >::add(), m_time_type, and m_value_type.
Referenced by Envelope::addInterpolators(), DynamicVariableSequence::addInterpolators(), Envelope::getValue(), DynamicVariableSequence::getValue(), and Sound::setup_detuning_env().
virtual Interpolator* Interpolator::clone () [pure virtual]
This function creates an exact copy of this object.
Returns: A new Interpolator
Implements DynamicVariable.
Implemented in LinearInterpolator, ExponentialInterpolator, and CubicSplineInterpolator.
m_value_type Interpolator::getMaxValue () [virtual]
This function returns the maximum value of all the entries.
Returns: The maximum value
Implements DynamicVariable.
Definition at line 63 of file Interpolator.cpp.
References Iterator< T >::hasNext(), Collection< InterpolatorEntry >::iterator(), m_value_type, and Iterator< T >::next().
virtual interpolation_type Interpolator::getType () [pure virtual]
This function returns the type of interpolator for use in reconstructing envelope parameters for EnvelopeLibrary from a DynamicVariableSequence. Virtual function implemented in InterpolatorTypes.
Returns: Interpolator type
Implemented in LinearInterpolator, ExponentialInterpolator, and CubicSplineInterpolator.
Referenced by xml_print().
void Interpolator::scale (m_value_type scale) [virtual]
This function scales every entry's value by this factor.
Parameters:
scale The factor by which to scale
Implements DynamicVariable.
Definition at line 51 of file Interpolator.cpp.
References Iterator< T >::hasNext(), Collection< InterpolatorEntry >::iterator(), m_value_type, and Iterator< T >::next().
virtual Iterator<m_value_type> Interpolator::valueIterator () [pure virtual]
This function returns an InterpolatorIterator.
Returns: An iterator
Implements DynamicVariable.
Implemented in LinearInterpolator, ExponentialInterpolator, and CubicSplineInterpolator.
Referenced by Envelope::getValue(), DynamicVariableSequence::getValue(), EnvelopeIterator::next(), and DynamicVariableSequenceIterator::next().
void Interpolator::xml_print (ofstream & xmlOutput) [virtual]
Deprecated
Implements DynamicVariable.
Definition at line 79 of file Interpolator.cpp.
References DynamicVariable::getDuration(), DynamicVariable::getSamplingRate(), getType(), Iterator< T >::hasNext(), Collection< InterpolatorEntry >::iterator(), Iterator< T >::next(), InterpolatorEntry::time_, and InterpolatorEntry::value_.
void Interpolator::xml_print (ofstream & xmlOutput, list< DynamicVariable * > & dynObjs) [virtual]
Deprecated This outputs an XML representation of the object to STDOUT
Implements DynamicVariable.
Definition at line 104 of file Interpolator.cpp.
void Interpolator::xml_read (XmlReader::xmltag * soundtag)
Deprecated
Definition at line 126 of file Interpolator.cpp.
References Collection< InterpolatorEntry >::add(), XmlReader::xmltag::children, XmlReader::xmltag::findChildParamValue(), XmlReader::xmltag::getParamValue(), DynamicVariable::setDuration(), and DynamicVariable::setSamplingRate().
Referenced by DynamicVariable::create_dv_from_xml().
The documentation for this class was generated from the following files:
Interpolator.h
Interpolator.cpp