LowPassFilter Class Reference
#include <LowPassFilter.h>
Public Member Functions
LowPassFilter (float gain)
~LowPassFilter ()
m_sample_type do_filter (m_sample_type x_t)
void reset (void)
void xml_print ()
Private Attributes
float g
Filter::hist_queue< m_sample_type > * y_hist
Detailed Description
This is a simple 1st order IIR low-pass filter:
y(t) = x(t) + g*y(t-1)
                       ______________________
                      | |
  x(t) --->(+)------->| IIR LPF |--------------------> y(t)
            ^ |______________________| |
            | |
            |_________________(*g)_______________________|
Note: This filter (and all other filters) are stateful machines with internal feedback mechanisms. Thus this filter should be allocated anew each time you begin a new channel and should not be mixed between channels.
Author: Jim LIndstrom
Definition at line 60 of file LowPassFilter.h.
Constructor & Destructor Documentation
LowPassFilter::LowPassFilter (float gain)
This is a constructor.
Parameters:
gain The low-pass feedback gain
Definition at line 41 of file LowPassFilter.cpp.
References Filter::hist_queue< m_sample_type >::enqueue(), g, and y_hist.
LowPassFilter::~LowPassFilter ()
This is a destructor.
Definition at line 52 of file LowPassFilter.cpp.
References y_hist.
Member Function Documentation
m_sample_type LowPassFilter::do_filter (m_sample_type x_t) [virtual]
This method applies a low-pass filter to a single sample
Parameters:
x_t The input sample
Returns: The filtered sample
Implements Filter.
Definition at line 58 of file LowPassFilter.cpp.
References Filter::hist_queue< m_sample_type >::dequeue(), Filter::hist_queue< m_sample_type >::enqueue(), g, m_sample_type, and y_hist.
Referenced by LPCombFilter::do_filter().
void LowPassFilter::reset (void) [virtual]
This method should be redefined by each class derived from Filter to reset the filter to an initial state. It should have the same effect as deleting the filter and creating a new one.
Implements Filter.
Definition at line 70 of file LowPassFilter.cpp.
References Filter::hist_queue< m_sample_type >::enqueue(), and y_hist.
void LowPassFilter::xml_print ()
Deprecated This outputs an XML representation of the object to STDOUT
Definition at line 79 of file LowPassFilter.cpp.
References g.
Member Data Documentation
float LowPassFilter::g [private]
The gain for the filter
Definition at line 100 of file LowPassFilter.h.
Referenced by do_filter(), LowPassFilter(), and xml_print().
Filter::hist_queue<m_sample_type>* LowPassFilter::y_hist [private]
This queue holds past samples to implement the delay
Definition at line 105 of file LowPassFilter.h.
Referenced by do_filter(), LowPassFilter(), reset(), and ~LowPassFilter().
The documentation for this class was generated from the following files:
LowPassFilter.h
LowPassFilter.cpp