.TH "bottom.cpp" 3 "12 Feb 2007" "CMOD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bottom.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'bottom.h'\fP
.br
\fC#include 'utility.h'\fP
.br
\fC#include 'note.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBstd\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "ofstream * \fBoutputFile\fP"
.br
.ti -1c
.RI "EnvelopeLibrary \fBenvlib\fP"
.br
.ti -1c
.RI "int \fBbottomID\fP"
.br
.ti -1c
.RI "int \fBnoteID\fP"
.br
.ti -1c
.RI "Score \fBscore\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "int \fBbottomID\fP"
.PP
Definition at line 32 of file bottom.cpp.
.PP
Referenced by Bottom::Bottom(), High::High(), Low::Low(), and Bottom::Print().
.SS "EnvelopeLibrary \fBenvlib\fP"
.PP
Definition at line 31 of file bottom.cpp.
.PP
Referenced by EnvelopeBuilder(), envValue(), Bottom::Modifiers(), TestLibrary(), and Bottom::ThreeStep().
.SS "int \fBnoteID\fP"
.PP
Definition at line 33 of file bottom.cpp.
.PP
Referenced by Note::Note(), and Note::Print().
.SS "ofstream* \fBoutputFile\fP"
.PP
Definition at line 30 of file bottom.cpp.
.PP
Referenced by main(), Top::Print(), Note::Print(), Low::Print(), High::Print(), Bottom::Print(), and Bottom::PrintSound().
.SS "Score \fBscore\fP"
.PP
Definition at line 34 of file bottom.cpp.
.PP
Referenced by Bottom::buildSound(), Event::BuildSubEvents(), and main().
.SH "Author"
.PP 
Generated automatically by Doxygen for CMOD from the source code.
