.TH "dataIn.cpp" 3 "12 Feb 2007" "CMOD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dataIn.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <iomanip>\fP
.br
\fC#include <cstdlib>\fP
.br
\fC#include <cmath>\fP
.br
\fC#include 'dataIn.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for CMOD from the source code.
