.TH "matrix.cpp" 3 "12 Feb 2007" "CMOD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
matrix.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <sstream>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <cmath>\fP
.br
\fC#include <cstdlib>\fP
.br
\fC#include <limits.h>\fP
.br
\fC#include <sys/types.h>\fP
.br
\fC#include 'dataIn.h'\fP
.br
\fC#include 'matrix.h'\fP
.br
\fC#include 'utility.h'\fP
.br
\fC#include 'random.h'\fP
.br
\fC#include '../../LASS/src/lib.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "ostream & \fBoperator<<\fP (ostream &s, \fBMatrix\fP &m)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "EnvelopeLibrary \fBenvlib\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "ostream& operator<< (ostream & s, \fBMatrix\fP & m)"
.PP
PUBLIC: OPERATOR<<. Definition at line 220 of file matrix.cpp.
.PP
References Matrix::matrix, Matrix::x, and Matrix::y.
.SH "Variable Documentation"
.PP 
.SS "EnvelopeLibrary \fBenvlib\fP"
.PP
Definition at line 43 of file matrix.cpp.
.SH "Author"
.PP 
Generated automatically by Doxygen for CMOD from the source code.
