.TH "patter.cpp" 3 "12 Feb 2007" "CMOD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
patter.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include '../../LASS/src/lib.h'\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <iomanip>\fP
.br
\fC#include <cstdlib>\fP
.br
\fC#include 'patter.h'\fP
.br
\fC#include 'dataIn.h'\fP
.br
\fC#include 'linkList.h'\fP
.br
\fC#include 'utility.h'\fP
.br
\fC#include 'random.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "EnvelopeLibrary \fBenvlib\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "EnvelopeLibrary \fBenvlib\fP"
.PP
Definition at line 45 of file patter.cpp.
.SH "Author"
.PP 
Generated automatically by Doxygen for CMOD from the source code.
