.TH "test.cpp" 3 "5 Dec 2005" "CMOD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include 'dataIn.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main ()"
.PP
Definition at line 7 of file test.cpp.
.PP
References DataIn::nameOf, DataIn::ReadChars(), and DataIn::Skip().
.SH "Author"
.PP 
Generated automatically by Doxygen for CMOD from the source code.
