Sound Class Reference
#include <Sound.h>
Public Member Functions
Sound ()
Sound (int numPartials, m_value_type baseFreq)
void setPartialParam (PartialStaticParam p, m_value_type v)
void setPartialParam (PartialDynamicParam p, DynamicVariable &v)
void setPartialParam (PartialDynamicParam p, m_value_type v)
void getPartialParamEnv (PartialDynamicParam p)
MultiTrack * render (int numChannels, m_rate_type samplingRate=DEFAULT_SAMPLING_RATE)
void setSpatializer (Spatializer &s)
void use_reverb (Reverb *newReverbObj)
void xml_print (ofstream &xmlOutput, list< Reverb * > &revObjs, list< DynamicVariable * > &dynObjs)
void xml_read (XmlReader::xmltag *soundtag, hash_map< long, Reverb * > *reverbHash, hash_map< long, DynamicVariable * > *dvHash)
m_time_type getTotalDuration (void)
Private Member Functions
void setup_detuning_env (ExponentialInterpolator *env)
Private Attributes
Spatializer * spatializer_
Reverb * reverbObj
Detailed Description
Conceptually, A Sound is made up from a set of partials.
Author: Braden Kowitz
Definition at line 142 of file Sound.h.
Constructor & Destructor Documentation
Sound::Sound ()
This is a default constructor that sets a few basic parameters
DURATION = 1.0
START_TIME = 0.0
LOUDNESS = 100 (out of 255) Sones
LOUDNESS_RATE = 10 Hz
Definition at line 36 of file Sound.cpp.
References DETUNE_DIRECTION, DETUNE_FUNDAMENTAL, DETUNE_SPREAD, DETUNE_VELOCITY, DURATION, LOUDNESS, LOUDNESS_RATE, reverbObj, ParameterLib< SoundStaticParam, SoundDynamicParam >::setParam(), spatializer_, and START_TIME.
Sound::Sound (int numPartials, m_value_type baseFreq)
This is a constructor that creates a Sound object with proper partials already created.
Parameters:
numPartials The number of partials in the Sound
baseFreq The base freqency of the Sound
Definition at line 54 of file Sound.cpp.
References Collection< Partial >::add(), DETUNE_DIRECTION, DETUNE_FUNDAMENTAL, DETUNE_SPREAD, DETUNE_VELOCITY, DURATION, FREQUENCY, LOUDNESS, LOUDNESS_RATE, m_value_type, PARTIAL_NUM, RELATIVE_AMPLITUDE, reverbObj, ParameterLib< SoundStaticParam, SoundDynamicParam >::setParam(), ParameterLib< PartialStaticParam, PartialDynamicParam >::setParam(), spatializer_, and START_TIME.
Member Function Documentation
void Sound::getPartialParamEnv (PartialDynamicParam p)
This function iterates through the partials, calling getParam on them.
Parameters:
p The PartialDynamicParam to get the envelope which was used on it
m_time_type Sound::getTotalDuration (void)
This returns the total duration of the sound. If there is no reverb on this sound or any of its partials, this will return exactly the value of getParam(DURATION). If any partial has reverb, though, that partial will need extra time for the reverb to die out. Likewise, if the sound has reverb, that will also take time to die out.
Returns: The total duration of the sound including reverb
Definition at line 363 of file Sound.cpp.
References DURATION, Reverb::getDecay(), ParameterLib< SoundStaticParam, SoundDynamicParam >::getParam(), Iterator< T >::hasNext(), Collection< Partial >::iterator(), m_time_type, Iterator< T >::next(), and reverbObj.
Referenced by render(), and Score::render().
MultiTrack * Sound::render (int numChannels, m_rate_type samplingRate = DEFAULT_SAMPLING_RATE)
This returns a MultiTrack object of the rendered partial.
Parameters:
numChannels The number of channels in the MultiTrack
samplingRate The sampling rate
Returns: A MultiTrack
Note: The object must be deleted by the user calling the function.
Definition at line 149 of file Sound.cpp.
References Loudness::calculate(), Track::composite(), DETUNE_FUNDAMENTAL, DETUNING_ENV, Reverb::do_reverb_Track(), DURATION, ParameterLib< SoundStaticParam, SoundDynamicParam >::getParam(), getTotalDuration(), Iterator< T >::hasNext(), Collection< Partial >::iterator(), LOUDNESS, LOUDNESS_RATE, m_rate_type, m_sample_count_type, m_time_type, Iterator< T >::next(), reverbObj, setup_detuning_env(), Collection< Partial >::size(), Spatializer::spatialize(), and spatializer_.
Referenced by multithreaded_render_worker(), and Score::render().
void Sound::setPartialParam (PartialDynamicParam p, m_value_type v)
This function iterates through the partials, calling setParam on them.
Parameters:
p The PartialDynamicParam to set
v The value to set the parameter to
Definition at line 109 of file Sound.cpp.
References FREQUENCY, Iterator< T >::hasNext(), Collection< Partial >::iterator(), m_value_type, and Iterator< T >::next().
void Sound::setPartialParam (PartialDynamicParam p, DynamicVariable & v)
This function iterates through the partials, calling setParam on them.
Parameters:
p The PartialDynamicParam to set
v The value to set the parameter to
Todo Change FREQUENCY param like old MOSS
Definition at line 101 of file Sound.cpp.
References Iterator< T >::hasNext(), Collection< Partial >::iterator(), and Iterator< T >::next().
void Sound::setPartialParam (PartialStaticParam p, m_value_type v)
This function iterates through the partials, calling setParam on them.
Parameters:
p The PartialStaticParam to set
v The value to set the parameter to
Definition at line 93 of file Sound.cpp.
References Iterator< T >::hasNext(), Collection< Partial >::iterator(), m_value_type, and Iterator< T >::next().
void Sound::setSpatializer (Spatializer & s)
This function sets the Spatializer used for this sound. The given parameter is copied into this object's memory.
Parameters:
s The Spatializer to use
Definition at line 306 of file Sound.cpp.
References Spatializer::clone(), and spatializer_.
void Sound::setup_detuning_env (ExponentialInterpolator * env) [private]
This function creates a detuning envelope.
Parameters:
env The envelope
Definition at line 319 of file Sound.cpp.
References Interpolator::addEntry(), DETUNE_DIRECTION, DETUNE_SPREAD, DETUNE_VELOCITY, and ParameterLib< SoundStaticParam, SoundDynamicParam >::getParam().
Referenced by render().
void Sound::use_reverb (Reverb * newReverbObj)
This function performs reverb in the render() method
Parameters:
newReverbObj The Reverb object
Definition at line 313 of file Sound.cpp.
References reverbObj.
Referenced by xml_read().
void Sound::xml_print (ofstream & xmlOutput, list< Reverb * > & revObjs, list< DynamicVariable * > & dynObjs)
Deprecated This outputs an XML representation of the object to STDOUT
Definition at line 382 of file Sound.cpp.
References DETUNE_DIRECTION, DETUNE_FUNDAMENTAL, DETUNE_SPREAD, DETUNE_VELOCITY, DURATION, ParameterLib< SoundStaticParam, SoundDynamicParam >::getParam(), Iterator< T >::hasNext(), Collection< Partial >::iterator(), LOUDNESS, LOUDNESS_RATE, Iterator< T >::next(), reverbObj, spatializer_, START_TIME, and Spatializer::xml_print().
Referenced by Score::xml_print().
void Sound::xml_read (XmlReader::xmltag * soundtag, hash_map< long, Reverb * > * reverbHash, hash_map< long, DynamicVariable * > * dvHash)
Deprecated
Definition at line 422 of file Sound.cpp.
References Collection< Partial >::add(), XmlReader::xmltag::children, DETUNE_DIRECTION, DETUNE_FUNDAMENTAL, DETUNE_SPREAD, DETUNE_VELOCITY, DURATION, XmlReader::xmltag::findChildParamValue(), LOUDNESS, LOUDNESS_RATE, XmlReader::xmltag::name, ParameterLib< SoundStaticParam, SoundDynamicParam >::setParam(), START_TIME, use_reverb(), and Partial::xml_read().
Referenced by Score::xml_read().
Member Data Documentation
Reverb* Sound::reverbObj [private]
Pointer to a reverb object that will apply reverb to this sound
Definition at line 254 of file Sound.h.
Referenced by getTotalDuration(), render(), Sound(), use_reverb(), and xml_print().
Spatializer* Sound::spatializer_ [private]
Definition at line 147 of file Sound.h.
Referenced by render(), setSpatializer(), Sound(), and xml_print().
The documentation for this class was generated from the following files:
Sound.h
Sound.cpp