Pan Class Reference
#include <Pan.h>
Public Member Functions
Pan (DynamicVariable &v)
Pan * clone ()
void set (DynamicVariable &v)
MultiTrack * spatialize (Track &t, int numTracks)
void xml_print (ofstream &xmlOutput)
Private Attributes
DynamicVariable * panVar_
Detailed Description
Pan is a simple Spatializer. It implements simple panning accross a number of channels.
Todo Add destructor to Spatializer.
Author: Braden Kowitz
Definition at line 45 of file Pan.h.
Constructor & Destructor Documentation
Pan::Pan (DynamicVariable & v)
This is a simple constructor which creates a pan object around a dynamic variable. The range should be [0,1] (else undefined).
Parameters:
v The DynamicVariable
Definition at line 38 of file Pan.cpp.
Referenced by clone().
Member Function Documentation
Pan * Pan::clone () [virtual]
This returns an exact duplicate of this Pan object.
Returns: The new Pan object
Reimplemented from Spatializer.
Definition at line 47 of file Pan.cpp.
References Pan(), and panVar_.
void Pan::set (DynamicVariable & v)
This sets the dynamic variable for a Pan object to something different than specified in the constructor.
Parameters:
v The new DynamicVariable
Definition at line 41 of file Pan.cpp.
References DynamicVariable::clone(), and panVar_.
MultiTrack * Pan::spatialize (Track & t, int numTracks) [virtual]
This will return a new MultiTrack object with numTracks. The given track will be panned accross the channels.
Parameters:
t The Track to pan
numTracks The number of tracks
Returns: A pointer to a new MultiTrack
Reimplemented from Spatializer.
Definition at line 52 of file Pan.cpp.
References Collection< Track * >::get(), Track::getAmp(), SoundSample::getSampleCount(), SoundSample::getSamplingRate(), Track::getWave(), m_rate_type, m_sample_count_type, m_value_type, Iterator< T >::next(), panVar_, DynamicVariable::setDuration(), DynamicVariable::setSamplingRate(), and DynamicVariable::valueIterator().
void Pan::xml_print (ofstream & xmlOutput) [virtual]
Deprecated
Reimplemented from Spatializer.
Definition at line 101 of file Pan.cpp.
Member Data Documentation
DynamicVariable* Pan::panVar_ [private]
Definition at line 48 of file Pan.h.
Referenced by clone(), set(), and spatialize().
The documentation for this class was generated from the following files:
Pan.h
Pan.cpp