AllPassFilter Class Reference
#include <AllPassFilter.h>
Public Member Functions
AllPassFilter (float gain, long delay)
~AllPassFilter ()
m_sample_type do_filter (m_sample_type x_t)
void reset (void)
void xml_print (ofstream &xmlOutput)
AllPassFilter ()
void set_g (float gain)
void set_D (long delay)
void xml_read (XmlReader::xmltag *apftag)
Private Attributes
float g
float g_sqrd
long D
Filter::hist_queue< m_sample_type > * y_hist
Filter::hist_queue< m_sample_type > * x_hist
Detailed Description
The comb filter class implements an allpass filter as described on page 385 of 'Elements of Computer Music:
y(t) = -gx(t) + (1-g^2)*(x(t-D) + g*y(t-D))
Note: This filter (and all other 'class Filter's) are stateful machines with internal feedback mechanisms. Thus this filter should be reset() each time you begin a new channel and should not be mixed between channels.
Author: Andrew Kurtz
Jim Lindstrom
Definition at line 51 of file AllPassFilter.h.
Constructor & Destructor Documentation
AllPassFilter::AllPassFilter (float gain, long delay)
This is the constructor.
Parameters:
gain The feedback gain (should be in the range 0.0 to 1.0)
delay The allpass delay (in units of samples)
Definition at line 43 of file AllPassFilter.cpp.
References D, Filter::hist_queue< m_sample_type >::enqueue(), g, g_sqrd, x_hist, and y_hist.
AllPassFilter::~AllPassFilter ()
This is the destructor
Definition at line 62 of file AllPassFilter.cpp.
References x_hist, and y_hist.
AllPassFilter::AllPassFilter ()
This is a constructor.
Definition at line 112 of file AllPassFilter.cpp.
Member Function Documentation
m_sample_type AllPassFilter::do_filter (m_sample_type x_t) [virtual]
This method applies an allpass filter to a single sample
Parameters:
x_t The input sample
Returns: The sampled filter
Implements Filter.
Definition at line 70 of file AllPassFilter.cpp.
References Filter::hist_queue< m_sample_type >::dequeue(), Filter::hist_queue< m_sample_type >::enqueue(), g, g_sqrd, m_sample_type, x_hist, and y_hist.
Referenced by Reverb::do_reverb().
void AllPassFilter::reset (void) [virtual]
This method should be redefined by each class derived from Filter to reset the filter to an initial state. It should have the same effect as deleting the filter and creating a new one.
Implements Filter.
Definition at line 82 of file AllPassFilter.cpp.
References D, Filter::hist_queue< m_sample_type >::enqueue(), x_hist, and y_hist.
Referenced by Reverb::reset().
void AllPassFilter::set_D (long delay)
This sets the delay.
Parameters:
delay The delay as a long
Definition at line 121 of file AllPassFilter.cpp.
References D, Filter::hist_queue< m_sample_type >::enqueue(), x_hist, and y_hist.
Referenced by xml_read().
void AllPassFilter::set_g (float gain)
This sets the gain.
Parameters:
gain The gain as a float
Definition at line 116 of file AllPassFilter.cpp.
References g, and g_sqrd.
Referenced by xml_read().
void AllPassFilter::xml_print (ofstream & xmlOutput)
Deprecated This outputs an XML representation of the object to STDOUT.
Parameters:
xmlOutput The output channel
Definition at line 100 of file AllPassFilter.cpp.
References D, and g.
Referenced by Reverb::xml_print().
void AllPassFilter::xml_read (XmlReader::xmltag * apftag)
Deprecated Reads some xml and sets the gain and delay.
Parameters:
apftag A pointer to the xml to read
Definition at line 136 of file AllPassFilter.cpp.
References XmlReader::xmltag::findChildParamValue(), set_D(), and set_g().
Referenced by Reverb::xml_read().
Member Data Documentation
long AllPassFilter::D [private]
The delay for the comb component of the filter
Definition at line 124 of file AllPassFilter.h.
Referenced by AllPassFilter(), reset(), set_D(), and xml_print().
float AllPassFilter::g [private]
The gain for the comb component of the filter
Definition at line 114 of file AllPassFilter.h.
Referenced by AllPassFilter(), do_filter(), set_g(), and xml_print().
float AllPassFilter::g_sqrd [private]
The square of the gain
Definition at line 119 of file AllPassFilter.h.
Referenced by AllPassFilter(), do_filter(), and set_g().
Filter::hist_queue<m_sample_type>* AllPassFilter::x_hist [private]
This queue holds past samples to implement the delay
Definition at line 134 of file AllPassFilter.h.
Referenced by AllPassFilter(), do_filter(), reset(), set_D(), and ~AllPassFilter().
Filter::hist_queue<m_sample_type>* AllPassFilter::y_hist [private]
This queue holds past samples to implement the delay
Definition at line 129 of file AllPassFilter.h.
Referenced by AllPassFilter(), do_filter(), reset(), set_D(), and ~AllPassFilter().
The documentation for this class was generated from the following files:
AllPassFilter.h
AllPassFilter.cpp