Partial Class Reference
#include <Partial.h>
Public Member Functions
Partial ()
Track * render (m_sample_count_type sampleCount, m_time_type duration, m_rate_type samplingRate=DEFAULT_SAMPLING_RATE)
void use_reverb (Reverb *newReverbObj)
void xml_print (ofstream &xmlOutput, list< Reverb * > &revObjs, list< DynamicVariable * > &dynObjs)
void xml_read (XmlReader::xmltag *partialtag, hash_map< long, Reverb * > *reverbHash, hash_map< long, DynamicVariable * > *dvHash)
m_time_type getTotalDuration (m_time_type dryDuration)
Private Member Functions
void auxLoadParam (enum PartialDynamicParam param, XmlReader::xmltag *tag, hash_map< long, DynamicVariable * > *dvHash)
m_value_type pmod (m_value_type num)
Private Attributes
Reverb * reverbObj
Detailed Description
A partial is a building block of all sounds. It is a simple Sin wave that is manipulated by several dynamic and static parameters.
Definition at line 163 of file Partial.h.
Constructor & Destructor Documentation
Partial::Partial ()
Default constructor that sets a few basic parameters
RELATIVE_AMPLITUDE = 1.0
PARTIAL_NUM = 1.0
WAVE_SHAPE = 1.0
FREQUENCY = 440
LOUDNESS_SCALAR = 1.0
All trans envelopes = 0
Both TRANS_WIDTH = 1103
Definition at line 41 of file Partial.cpp.
References AMPTRANS_AMP_ENV, AMPTRANS_RATE_ENV, AMPTRANS_WIDTH, FREQ_ENV, FREQTRANS_AMP_ENV, FREQTRANS_RATE_ENV, FREQTRANS_WIDTH, FREQUENCY, LOUDNESS_SCALAR, PARTIAL_NUM, RELATIVE_AMPLITUDE, reverbObj, ParameterLib< PartialStaticParam, PartialDynamicParam >::setParam(), WAVE_SHAPE, and WAVE_TYPE.
Member Function Documentation
void Partial::auxLoadParam (enum PartialDynamicParam param, XmlReader::xmltag * tag, hash_map< long, DynamicVariable * > * dvHash) [private]
Deprecated Auxillary function to assist in loading dv's from XML
Definition at line 556 of file Partial.cpp.
References DynamicVariable::create_dv_from_xml(), XmlReader::xmltag::findChildParamValue(), and ParameterLib< PartialStaticParam, PartialDynamicParam >::setParam().
Referenced by xml_read().
m_time_type Partial::getTotalDuration (m_time_type dryDuration)
This returns the total length (in seconds) of the partial.
Parameters:
dryDuration The input 'dryDuration' is the duration of the sound without any effects added on.
Returns: The total length of time returned includes time for the reverb to die out.
Definition at line 401 of file Partial.cpp.
References Reverb::getDecay(), m_time_type, and reverbObj.
m_value_type Partial::pmod (m_value_type num) [inline, private]
This is phase-modulation. It basically does an inline modulus 1 on a float value.
Definition at line 386 of file Partial.cpp.
References m_value_type.
Referenced by render().
Track * Partial::render (m_sample_count_type sampleCount, m_time_type duration, m_rate_type samplingRate = DEFAULT_SAMPLING_RATE)
This returns a Track object of the rendered partial. The object must be deleted by the user calling the function.
Parameters:
sampleCount The number of samples
duration The duration
samplingRate The sampling rate
Returns: A Track
Definition at line 64 of file Partial.cpp.
References AMPTRANS_AMP_ENV, AMPTRANS_RATE_ENV, AMPTRANS_WIDTH, DynamicVariable::clone(), Reverb::do_reverb_Track(), FREQ_ENV, FREQTRANS_AMP_ENV, FREQTRANS_RATE_ENV, FREQTRANS_WIDTH, FREQUENCY, Reverb::getDecay(), ParameterLib< PartialStaticParam, PartialDynamicParam >::getParam(), LOUDNESS_SCALAR, m_rate_type, m_sample_count_type, m_time_type, m_value_type, Iterator< m_value_type >::next(), PARTIAL_NUM, PHASE, pmod(), reverbObj, DynamicVariable::setDuration(), DynamicVariable::setSamplingRate(), TREMOLO_AMP, TREMOLO_RATE, DynamicVariable::valueIterator(), VIBRATO_AMP, VIBRATO_RATE, WAVE_SHAPE, and WAVE_TYPE.
void Partial::use_reverb (Reverb * newReverbObj)
Use this object to perform reverb in the render() method
Parameters:
newReverbObj A pointer to a Reverb object
Definition at line 395 of file Partial.cpp.
References reverbObj.
Referenced by xml_read().
void Partial::xml_print (ofstream & xmlOutput, list< Reverb * > & revObjs, list< DynamicVariable * > & dynObjs)
Deprecated This outputs an XML representation of the object to STDOUT
Definition at line 407 of file Partial.cpp.
References FREQ_ENV, FREQUENCY, ParameterLib< PartialStaticParam, PartialDynamicParam >::getParam(), LOUDNESS_SCALAR, PARTIAL_NUM, PHASE, RELATIVE_AMPLITUDE, reverbObj, TREMOLO_AMP, TREMOLO_RATE, VIBRATO_AMP, VIBRATO_RATE, WAVE_SHAPE, and DynamicVariable::xml_print().
void Partial::xml_read (XmlReader::xmltag * partialtag, hash_map< long, Reverb * > * reverbHash, hash_map< long, DynamicVariable * > * dvHash)
Deprecated
Definition at line 486 of file Partial.cpp.
References auxLoadParam(), XmlReader::xmltag::children, XmlReader::xmltag::findChildParamValue(), FREQ_ENV, FREQUENCY, LOUDNESS_SCALAR, XmlReader::xmltag::name, XmlReader::xmltagset::next, PARTIAL_NUM, PHASE, RELATIVE_AMPLITUDE, ParameterLib< PartialStaticParam, PartialDynamicParam >::setParam(), XmlReader::xmltagset::tag, TREMOLO_AMP, TREMOLO_RATE, use_reverb(), VIBRATO_AMP, VIBRATO_RATE, and WAVE_SHAPE.
Referenced by Sound::xml_read().
Member Data Documentation
Reverb* Partial::reverbObj [private]
A Reverb object *
Definition at line 231 of file Partial.h.
Referenced by getTotalDuration(), Partial(), render(), use_reverb(), and xml_print().
The documentation for this class was generated from the following files:
Partial.h
Partial.cpp