Constant Class Reference
#include <Constant.h>
Public Member Functions
Constant (m_value_type value=0)
Constant * clone ()
void setValue (m_value_type value)
m_value_type getValue ()
Iterator< m_value_type > valueIterator ()
void scale (m_value_type factor)
m_value_type getMaxValue ()
void xml_print (ofstream &xmlOutput, list< DynamicVariable * > &dynObjs)
void xml_print (ofstream &xmlOutput)
void xml_read (XmlReader::xmltag *xml)
Private Attributes
m_value_type value_
Detailed Description
A constant Dynamic variable. Kind of an oxymoron, but it's needed.
Author: Braden Kowitz
Definition at line 46 of file Constant.h.
Constructor & Destructor Documentation
Constant::Constant (m_value_type value = 0)
Constructor that creates a constant at a specified value.
Definition at line 38 of file Constant.cpp.
References m_value_type.
Referenced by clone().
Member Function Documentation
Constant * Constant::clone () [virtual]
Creates an exact copy of this object.
Returns: pointer to the copy
Implements DynamicVariable.
Definition at line 44 of file Constant.cpp.
References Constant().
m_value_type Constant::getMaxValue () [virtual]
Simply return the constant value.
Returns: an m_value_type
Implements DynamicVariable.
Definition at line 75 of file Constant.cpp.
References m_value_type, and value_.
m_value_type Constant::getValue ()
Returns the value of this constant.
Returns: An m_value_type
Definition at line 56 of file Constant.cpp.
References m_value_type, and value_.
void Constant::scale (m_value_type factor) [virtual]
Scales the constant by this value.
Parameters:
factor an m_value_type
Implements DynamicVariable.
Definition at line 68 of file Constant.cpp.
References m_value_type, and value_.
void Constant::setValue (m_value_type value)
Sets the value of this constant.
Parameters:
value An m_value_type
Definition at line 50 of file Constant.cpp.
References m_value_type, and value_.
Referenced by xml_read().
Iterator< m_value_type > Constant::valueIterator () [virtual]
Returns a Iterator(ConstantIterator) (private sub-class)
Returns: an Iterator<m_value_type>
Implements DynamicVariable.
Definition at line 62 of file Constant.cpp.
References DynamicVariable::getSampleCount(), and value_.
void Constant::xml_print (ofstream & xmlOutput) [virtual]
Deprecated
Implements DynamicVariable.
Definition at line 120 of file Constant.cpp.
References DynamicVariable::getDuration(), DynamicVariable::getSamplingRate(), and value_.
void Constant::xml_print (ofstream & xmlOutput, list< DynamicVariable * > & dynObjs) [virtual]
Deprecated This outputs an XML representation of the object to STDOUT
Implements DynamicVariable.
Definition at line 148 of file Constant.cpp.
void Constant::xml_read (XmlReader::xmltag * xml)
Deprecated This sets the duration, sampling rate, and value if they they are contained in the xml.
Parameters:
xml The xml to read
Definition at line 133 of file Constant.cpp.
References XmlReader::xmltag::findChildParamValue(), DynamicVariable::setDuration(), DynamicVariable::setSamplingRate(), and setValue().
Referenced by DynamicVariable::create_dv_from_xml().
Member Data Documentation
m_value_type Constant::value_ [private]
Definition at line 110 of file Constant.h.
Referenced by getMaxValue(), getValue(), scale(), setValue(), valueIterator(), and xml_print().
The documentation for this class was generated from the following files:
Constant.h
Constant.cpp