XmlReader::xmltag Class Reference
#include <XmlReader.h>
Public Member Functions
xmltag ()
~xmltag ()
void setName (char *in)
char * getParamValue (char *pname)
bool isParamDefined (char *pname)
char * findChildParamValue (char *childName, char *paramName)
Public Attributes
char * name
tagparam * params
bool isClosing
xmltagset * children
Protected Member Functions
tagparam * findParam (char *pname)
void destroyTag ()
Friends
class XmlReader
Detailed Description
xmltag class This is the object generated by the xml reader to represent tags that are read in from the file.
Definition at line 76 of file XmlReader.h.
Constructor & Destructor Documentation
XmlReader::xmltag::xmltag ()
Definition at line 70 of file XmlReader.cpp.
References children, isClosing, name, and params.
XmlReader::xmltag::~xmltag ()
Definition at line 79 of file XmlReader.cpp.
References destroyTag().
Member Function Documentation
void XmlReader::xmltag::destroyTag () [protected]
This frees memeory and clears values inside the tag object
Definition at line 119 of file XmlReader.cpp.
References children, isClosing, name, XmlReader::tagparam::next, and params.
Referenced by XmlReader::readTag(), and ~xmltag().
char * XmlReader::xmltag::findChildParamValue (char * childName, char * paramName)
first does a find for an immediate child tag of given name, then searches that tag for a parameter value. Repeatable if no other find calls are made on children list of this tag in between.
Definition at line 143 of file XmlReader.cpp.
References children, XmlReader::xmltagset::find(), and getParamValue().
Referenced by Partial::auxLoadParam(), DynamicVariable::create_dv_from_xml(), Sound::xml_read(), Score::xml_read(), Reverb::xml_read(), Partial::xml_read(), LPCombFilter::xml_read(), Interpolator::xml_read(), Envelope::xml_read(), Constant::xml_read(), and AllPassFilter::xml_read().
XmlReader::tagparam * XmlReader::xmltag::findParam (char * pname) [protected]
Definition at line 85 of file XmlReader.cpp.
References XmlReader::tagparam::name, XmlReader::tagparam::next, and params.
Referenced by getParamValue(), and isParamDefined().
char * XmlReader::xmltag::getParamValue (char * pname)
gets the value of a parameter by name returns NULL if not defined.
Definition at line 99 of file XmlReader.cpp.
References findParam(), and XmlReader::tagparam::value.
Referenced by findChildParamValue(), Score::xml_read(), Interpolator::xml_read(), Envelope::xml_read(), and DynamicVariableSequence::xml_read().
bool XmlReader::xmltag::isParamDefined (char * pname)
checks to see if a certian parameter is defined in the XML.
Definition at line 109 of file XmlReader.cpp.
References findParam().
void XmlReader::xmltag::setName (char * in)
Sets the name of the tag
Definition at line 63 of file XmlReader.cpp.
References name.
Referenced by XmlReader::readTag().
Friends And Related Function Documentation
friend class XmlReader [friend]
Definition at line 78 of file XmlReader.h.
Member Data Documentation
xmltagset* XmlReader::xmltag::children
Definition at line 86 of file XmlReader.h.
Referenced by destroyTag(), findChildParamValue(), XmlReader::readXMLDocument(), Sound::xml_read(), Score::xml_read(), Reverb::xml_read(), Partial::xml_read(), Interpolator::xml_read(), Envelope::xml_read(), and xmltag().
bool XmlReader::xmltag::isClosing
Definition at line 82 of file XmlReader.h.
Referenced by destroyTag(), XmlReader::readTag(), XmlReader::readXMLDocument(), DynamicVariableSequence::xml_read(), and xmltag().
char* XmlReader::xmltag::name
Definition at line 80 of file XmlReader.h.
Referenced by XmlReader::xmltagset::auxfind(), destroyTag(), XmlReader::readXMLDocument(), setName(), Sound::xml_read(), Score::xml_read(), Reverb::xml_read(), Partial::xml_read(), DynamicVariableSequence::xml_read(), and xmltag().
tagparam* XmlReader::xmltag::params
Definition at line 81 of file XmlReader.h.
Referenced by destroyTag(), findParam(), XmlReader::readTag(), and xmltag().
The documentation for this class was generated from the following files:
XmlReader.h
XmlReader.cpp