Envelope Class Reference
#include <Envelope.h>
Public Member Functions
Envelope ()
Envelope (Envelope &env)
Envelope (Collection< xy_point > xy_points, Collection< envelope_segment > segs)
Envelope (Collection< envelope_segment > segs)
~Envelope ()
Envelope * clone ()
m_value_type getValue (m_value_type x, m_value_type totalLength)
void Print ()
void DefineShape (Collection< envelope_segment > segs)
void AddToShape (Collection< envelope_segment > segs)
void AddToShape (Envelope *shape)
Envelope * multiply (Envelope &env1, Envelope &env2)
Collection< xy_point > * getPoints ()
Collection< envelope_segment > * getSegments ()
void setSegment (int index, envelope_segment segment)
envelope_segment getSegment (int index)
void setPoint (int index, xy_point point)
xy_point getPoint (int index)
void addPoint (xy_point point)
void addSegment (envelope_segment segment)
m_value_type getSegmentLength (int index)
void setSegmentLength (int index, m_value_type length)
stretch_type getSegmentLengthType (int index)
void setSegmentLengthType (int index, stretch_type lengthType)
interpolation_type getSegmentInterpolationType (int index)
void setSegmentInterpolationType (int index, interpolation_type interType)
Iterator< m_value_type > valueIterator ()
void scale (m_value_type factor)
m_value_type getMaxValue ()
void xml_print (ofstream &xmlOutput, list< DynamicVariable * > &dynObjs)
void xml_print (ofstream &xmlOutput)
void xml_read (XmlReader::xmltag *soundtag)
Private Member Functions
void addInterpolators (m_rate_type rate)
void generateLengths (m_time_type totalLength)
bool checkValidSegmentIndex (int index)
Private Attributes
Collection< envelope_segment > * segments_
Collection< Interpolator * > * interpolators_
Collection< m_value_type > * generatedSegmentLengths_
m_value_type totalLength_
m_rate_type currentInterpolatorRate_
Detailed Description
This class is designed to allow users to specify the shape of an envelope. This is done by using a collection of the env_seg type, which can be found in Types.h. For each segment, a user must specify the x value of the right endpoint of the segment, the type of interpolation to use for the segment, and whether or not the segment has a FIXED or FLEXIBLE length. If the total length specified by the user is greater than the sum of the lengths of the segments, then every segment with a length type of FLEXIBLE will be scaled up to fit the total length specified. Sample programs of how to use this class can be found in the samples directory, named sampleenvelope*.cpp
Note: All of the public functions of the class increment the index by 1. This means that a sample program will normally not access the dummy segment information used for the first point. In other words, getSegment(0) will actually retrieve segments_[1]. This is why the index is changed when segments_->get() is used internally by the Envelope functions.
Author: Michael Aikins
Greg Augustine
Definition at line 56 of file Envelope.h.
Constructor & Destructor Documentation
Envelope::Envelope ()
This is the constructor. There are no parameters since it assumes data will be given later.
Definition at line 44 of file Envelope.cpp.
References currentInterpolatorRate_, generatedSegmentLengths_, interpolators_, segments_, and totalLength_.
Referenced by clone(), and multiply().
Envelope::Envelope (Envelope & env)
This is a copy constructor.
Parameters:
env The envolope to copy
Returns: A copy of env
Definition at line 54 of file Envelope.cpp.
References currentInterpolatorRate_, generatedSegmentLengths_, getSegments(), interpolators_, segments_, and totalLength_.
Envelope::Envelope (Collection< xy_point > xy_points, Collection< envelope_segment > segs)
Constructor - Make new envelope using a collection of envelope segments and points
Definition at line 68 of file Envelope.cpp.
References Collection< T >::add(), currentInterpolatorRate_, DefineShape(), generatedSegmentLengths_, Collection< T >::get(), interpolators_, segments_, Collection< T >::size(), totalLength_, xy_point::x, envelope_segment::x, xy_point::y, and envelope_segment::y.
Envelope::Envelope (Collection< envelope_segment > segs)
This is a constructor. It makes a new envelope using a collection of envelope segments.
Parameters:
segs A Collection of envelop segments
Definition at line 94 of file Envelope.cpp.
References currentInterpolatorRate_, DefineShape(), generatedSegmentLengths_, interpolators_, segments_, and totalLength_.
Envelope::~Envelope ()
This is a destructor.
Definition at line 108 of file Envelope.cpp.
References generatedSegmentLengths_, interpolators_, Collection< Interpolator * >::remove(), segments_, and Collection< Interpolator * >::size().
Member Function Documentation
void Envelope::addInterpolators (m_rate_type rate) [private]
This function populate the private member variable with actual interpolators.
Parameters:
rate The rate
Definition at line 909 of file Envelope.cpp.
References Collection< Interpolator * >::add(), Interpolator::addEntry(), CUBIC_SPLINE, EXPONENTIAL, generatedSegmentLengths_, Collection< m_value_type >::get(), Collection< Interpolator * >::get(), Collection< envelope_segment >::get(), getSegmentInterpolationType(), interpolators_, m_rate_type, m_value_type, segments_, DynamicVariable::setDuration(), DynamicVariable::setSamplingRate(), Collection< envelope_segment >::size(), and envelope_segment::y.
Referenced by valueIterator().
void Envelope::addPoint (xy_point point)
This function appends a point to the end of the envelope. It's default interpolation type is LINEAR and stretch type is FIXED.
Parameters:
point The point to append
Definition at line 658 of file Envelope.cpp.
References addSegment(), FIXED, envelope_segment::interType, envelope_segment::lengthType, LINEAR, xy_point::x, envelope_segment::x, xy_point::y, and envelope_segment::y.
void Envelope::addSegment (envelope_segment segment)
This function appends a segment to the end of the envelope.
Parameters:
segment The segment to append
Definition at line 648 of file Envelope.cpp.
References Collection< envelope_segment >::add(), Collection< envelope_segment >::get(), envelope_segment::length, segments_, Collection< envelope_segment >::size(), and envelope_segment::x.
Referenced by addPoint().
void Envelope::AddToShape (Envelope * shape)
This overloaded function appends one envelope to another.
Parameters:
shape The Envelope to append
Definition at line 432 of file Envelope.cpp.
void Envelope::AddToShape (Collection< envelope_segment > segs)
This function adds to the env the given segment descriptions.
Parameters:
segs A Collection of envelope segments
Definition at line 392 of file Envelope.cpp.
References envelope_segment::length, m_value_type, and envelope_segment::x.
bool Envelope::checkValidSegmentIndex (int index) [inline, private]
This function checks if a number is a valid index for a segment.
Parameters:
index The index to check
Return values:
true Is valid
false Is not valid
Definition at line 735 of file Envelope.cpp.
References segments_, and Collection< envelope_segment >::size().
Referenced by setSegment().
Envelope * Envelope::clone () [virtual]
This makes a copy of this object.
Returns: A new Envelope
Implements DynamicVariable.
Definition at line 207 of file Envelope.cpp.
References Envelope(), and segments_.
Referenced by EnvelopeLibrary::EnvelopeLibrary().
void Envelope::DefineShape (Collection< envelope_segment > segs) [inline]
This function (re)defines the Envelope given point and segment descriptions.
Parameters:
segs A Collection of envelope segments
Definition at line 366 of file Envelope.cpp.
References Collection< T >::get(), envelope_segment::length, m_value_type, segments_, Collection< T >::set(), Collection< T >::size(), and envelope_segment::x.
Referenced by Envelope(), and xml_read().
void Envelope::generateLengths (m_time_type totalLength) [private]
This function populates the private member variable with actual lengths. This functions scales all FIXED and FLEXIBLE lengths appropriately.
Note: If you want to scale the envelope publicly, use the function scale.
Parameters:
totalLength The total length of time to scale to
Definition at line 768 of file Envelope.cpp.
References Collection< m_value_type >::add(), FIXED, FLEXIBLE, generatedSegmentLengths_, Collection< m_value_type >::get(), getSegmentLength(), getSegmentLengthType(), m_time_type, segments_, Collection< m_value_type >::set(), setSegmentLength(), Collection< envelope_segment >::size(), and totalLength_.
Referenced by getValue(), and valueIterator().
m_value_type Envelope::getMaxValue () [virtual]
This function returns the maximum value in all the entries.
Returns: The maximum value
Implements DynamicVariable.
Definition at line 989 of file Envelope.cpp.
References Collection< envelope_segment >::get(), m_value_type, segments_, Collection< envelope_segment >::size(), and envelope_segment::y.
xy_point Envelope::getPoint (int index)
This function gets a point by its index.
Parameters:
index Which point to get
Returns: The point
Definition at line 635 of file Envelope.cpp.
References Collection< envelope_segment >::get(), segments_, envelope_segment::x, xy_point::x, envelope_segment::y, and xy_point::y.
Referenced by getValue().
Collection< xy_point > * Envelope::getPoints ()
This function returns a collection of points that make up the shape.
Returns: A Collection of points
Definition at line 573 of file Envelope.cpp.
References Collection< T >::add(), Collection< envelope_segment >::get(), segments_, Collection< envelope_segment >::size(), envelope_segment::x, xy_point::x, envelope_segment::y, and xy_point::y.
envelope_segment Envelope::getSegment (int index)
This function gets a segment by its index.
Parameters:
index Which segment to get
Returns: An envelope segment
Definition at line 615 of file Envelope.cpp.
References Collection< envelope_segment >::get(), and segments_.
interpolation_type Envelope::getSegmentInterpolationType (int index)
This function gets the interpolation type for the segment with the given index.
Parameters:
index Which segment to examine
Returns: The interpolation type
Return values:
LINEAR
EXPONENTIAL
etc.
Definition at line 714 of file Envelope.cpp.
Referenced by addInterpolators(), getValue(), and Print().
m_value_type Envelope::getSegmentLength (int index)
This function gets the indexed segment's length of time. If the segment length type is FLEXIBLE, the length returned will be the unscaled, original value.
Parameters:
index Which segment to examine
Returns: The segment's length
Definition at line 668 of file Envelope.cpp.
References Collection< envelope_segment >::get(), envelope_segment::length, m_value_type, and segments_.
Referenced by generateLengths(), and Print().
stretch_type Envelope::getSegmentLengthType (int index)
This function gets the type for the segment with the given index.
Parameters:
index Which segment to examine
Returns: The time type
Return values:
FIXED
FLEXIBLE
Definition at line 693 of file Envelope.cpp.
References Collection< envelope_segment >::get(), envelope_segment::lengthType, segments_, and stretch_type.
Referenced by generateLengths(), and Print().
Collection< envelope_segment > * Envelope::getSegments ()
This function returns a collection of segments that make up the shape.
Returns: A Collection of envelope segments
Definition at line 589 of file Envelope.cpp.
Referenced by Envelope(), and multiply().
m_value_type Envelope::getValue (m_value_type x, m_value_type totalLength)
This gets an approximation of the value at the specified time.
Parameters:
x The type of value
totalLength The length of time
Returns: The approximate value
Definition at line 216 of file Envelope.cpp.
References Interpolator::addEntry(), CUBIC_SPLINE, EXPONENTIAL, generatedSegmentLengths_, generateLengths(), Collection< m_value_type >::get(), Collection< envelope_segment >::get(), getPoint(), getSegmentInterpolationType(), m_value_type, Iterator< T >::next(), segments_, DynamicVariable::setDuration(), DynamicVariable::setSamplingRate(), Collection< envelope_segment >::size(), Interpolator::valueIterator(), xy_point::y, and envelope_segment::y.
Referenced by multiply().
Envelope * Envelope::multiply (Envelope & env1, Envelope & env2)
This function multiplies two envelopes together.
Parameters:
env1 The first Envelope
env2 The second Envelope
Returns: The new Envelope
Definition at line 444 of file Envelope.cpp.
References Collection< T >::add(), CUBIC_SPLINE, Envelope(), EXPONENTIAL, FLEXIBLE, Collection< T >::get(), getSegments(), getValue(), envelope_segment::interType, envelope_segment::lengthType, LINEAR, envelope_segment::x, and envelope_segment::y.
void Envelope::Print ()
This is a debugging function that gives a text output of what is stored in the Envelope.
Definition at line 137 of file Envelope.cpp.
References CUBIC_SPLINE, EXPONENTIAL, FLEXIBLE, Collection< envelope_segment >::get(), getSegmentInterpolationType(), getSegmentLength(), getSegmentLengthType(), LINEAR, segments_, Collection< envelope_segment >::size(), envelope_segment::x, and envelope_segment::y.
void Envelope::scale (m_value_type factor) [virtual]
This function scales all Entries' values by this factor.
Parameters:
factor The factor by which to scale
Implements DynamicVariable.
Definition at line 972 of file Envelope.cpp.
References Collection< envelope_segment >::get(), m_value_type, segments_, Collection< envelope_segment >::set(), Collection< envelope_segment >::size(), and envelope_segment::y.
void Envelope::setPoint (int index, xy_point point)
This function sets a point by identified by its index.
Parameters:
index Which point to set
point The new point value
Definition at line 625 of file Envelope.cpp.
References Collection< envelope_segment >::get(), segments_, Collection< envelope_segment >::set(), xy_point::x, envelope_segment::x, xy_point::y, and envelope_segment::y.
void Envelope::setSegment (int index, envelope_segment segment)
This function sets an envelope segment identified by its index.
Parameters:
index Which segment to set
segment The new segment value
Definition at line 597 of file Envelope.cpp.
References checkValidSegmentIndex(), Collection< envelope_segment >::get(), envelope_segment::length, segments_, Collection< envelope_segment >::set(), and envelope_segment::x.
void Envelope::setSegmentInterpolationType (int index, interpolation_type interType)
This function sets the interpolation type for the segment with the given index.
Parameters:
index Which segment to set
interType The new interpolation type
Definition at line 724 of file Envelope.cpp.
References interpolation_type, and envelope_segment::interType.
void Envelope::setSegmentLength (int index, m_value_type length)
This function sets the indexed segment's length of time.
Parameters:
index Which segment to set
length The new length of time
Definition at line 677 of file Envelope.cpp.
References Collection< envelope_segment >::get(), envelope_segment::length, m_value_type, segments_, and Collection< envelope_segment >::set().
Referenced by generateLengths().
void Envelope::setSegmentLengthType (int index, stretch_type lengthType)
This function sets the indexed segment's time type.
Parameters:
index Which segment to set
lengthType The new time type
Definition at line 702 of file Envelope.cpp.
References Collection< envelope_segment >::get(), envelope_segment::lengthType, segments_, and Collection< envelope_segment >::set().
Iterator< m_value_type > Envelope::valueIterator () [virtual]
This function returns an iterator that iterates through all the values.
Returns: An iterator
Implements DynamicVariable.
Definition at line 743 of file Envelope.cpp.
References addInterpolators(), currentInterpolatorRate_, generateLengths(), DynamicVariable::getDuration(), DynamicVariable::getSamplingRate(), interpolators_, and totalLength_.
void Envelope::xml_print (ofstream & xmlOutput) [virtual]
Deprecated This outputs an XML representation of the object to STDOUT
Implements DynamicVariable.
Definition at line 1009 of file Envelope.cpp.
References CUBIC_SPLINE, currentInterpolatorRate_, EXPONENTIAL, FIXED, FLEXIBLE, DynamicVariable::getDuration(), DynamicVariable::getSamplingRate(), Iterator< T >::hasNext(), envelope_segment::interType, Collection< envelope_segment >::iterator(), envelope_segment::length, envelope_segment::lengthType, LINEAR, Iterator< T >::next(), segments_, totalLength_, envelope_segment::x, and envelope_segment::y.
void Envelope::xml_print (ofstream & xmlOutput, list< DynamicVariable * > & dynObjs) [virtual]
Deprecated This outputs an XML representation of the object to STDOUT
Implements DynamicVariable.
Definition at line 1068 of file Envelope.cpp.
void Envelope::xml_read (XmlReader::xmltag * soundtag)
Deprecated
Definition at line 1089 of file Envelope.cpp.
References Collection< T >::add(), XmlReader::xmltag::children, CUBIC_SPLINE, DefineShape(), EXPONENTIAL, XmlReader::xmltag::findChildParamValue(), FIXED, FLEXIBLE, XmlReader::xmltag::getParamValue(), envelope_segment::interType, envelope_segment::lengthType, LINEAR, DynamicVariable::setDuration(), DynamicVariable::setSamplingRate(), envelope_segment::x, and envelope_segment::y.
Referenced by DynamicVariable::create_dv_from_xml().
Member Data Documentation
m_rate_type Envelope::currentInterpolatorRate_ [private]
This is the sampling rate with which interpolators were generated *
Definition at line 301 of file Envelope.h.
Referenced by Envelope(), valueIterator(), and xml_print().
Collection<m_value_type>* Envelope::generatedSegmentLengths_ [private]
This is a Collection of Time values for segments that were generated based on the stored value. This collection will not include the 0 dummy segment, so element 0 will correspond to element 1 in segments_.
Definition at line 295 of file Envelope.h.
Referenced by addInterpolators(), Envelope(), generateLengths(), getValue(), and ~Envelope().
Collection<Interpolator*>* Envelope::interpolators_ [private]
This is a Collection to hold interpolators.
Definition at line 287 of file Envelope.h.
Referenced by addInterpolators(), Envelope(), valueIterator(), and ~Envelope().
Collection<envelope_segment>* Envelope::segments_ [private]
This is a Collection to hold the segment data for this DVS.
Definition at line 282 of file Envelope.h.
Referenced by addInterpolators(), addSegment(), checkValidSegmentIndex(), clone(), DefineShape(), Envelope(), generateLengths(), getMaxValue(), getPoint(), getPoints(), getSegment(), getSegmentLength(), getSegmentLengthType(), getValue(), Print(), scale(), setPoint(), setSegment(), setSegmentLength(), setSegmentLengthType(), xml_print(), and ~Envelope().
m_value_type Envelope::totalLength_ [private]
This is the value with which the segment times were generated *
Definition at line 298 of file Envelope.h.
Referenced by Envelope(), generateLengths(), valueIterator(), and xml_print().
The documentation for this class was generated from the following files:
Envelope.h
Envelope.cpp