Score Class Reference
#include <Score.h>
Public Types
enum ClippingManagementMode {
NONE,
CLIP,
SCALE,
CHANNEL_SCALE,
ANTICLIP,
CHANNEL_ANTICLIP
 }
Public Member Functions
Score ()
MultiTrack * render (int numChannels, m_rate_type samplingRate=DEFAULT_SAMPLING_RATE)
MultiTrack * render (int numChannels, m_rate_type samplingRate, int nThreads)
void setClippingManagementMode (ClippingManagementMode mode)
ClippingManagementMode getClippingManagementMode ()
void use_reverb (Reverb *newReverbObj)
void xml_print ()
void xml_print (ofstream &xmlOutput)
void xml_print (const char *xmlOutputPath)
void xml_read (XmlReader::xmltag *scoretag)
Static Public Member Functions
void manageClipping (MultiTrack *mt, ClippingManagementMode mode)
Public Attributes
hash_map< long, Reverb * > * reverbHash
hash_map< long, DynamicVariable * > * dvHash
Static Private Member Functions
void clip (MultiTrack *mt)
void scale (MultiTrack *mt)
void channelScale (MultiTrack *mt)
void anticlip (MultiTrack *mt)
void channelAnticlip (MultiTrack *mt)
Private Attributes
ClippingManagementMode cmm_
Reverb * reverbObj
Detailed Description
A Score simply consists of a collection of Sounds. In addition to this, it provides functionality for managing clipping in a piece.
Author: Braden Kowitz
Definition at line 71 of file Score.h.
Member Enumeration Documentation
enum Score::ClippingManagementMode
This sets the clipping management mode for this score. This post-process is run after the score is rendered.
Enumeration values:
NONE
No clipping management is taken at all.
This lets the composer render once, then try different post-processes, saving some time.
CLIP
Any value over 1 or under -1 is clipped to these limits.
SCALE
The max amplitude value is found in the entire score (all tracks).
Each track is then scaled by 1/maxAmplitude.
CHANNEL_SCALE
For each track, a max amplitude value if found.
This track is then scaled by 1/maxAmplitude
ANTICLIP
If the total amplitude accross tracks at any given time is greater than 1, then that sample is scaled on all tracks by 1/totalAmplitude.
CHANNEL_ANTICLIP
For each channel, and each sample
if a sample has an amplitude greater than 1, then that sample is scaled by 1/amplitude.
Definition at line 125 of file Score.h.
Referenced by getClippingManagementMode(), and xml_read().
Constructor & Destructor Documentation
Score::Score ()
This is the default constructor. It sets the ClippingManagementMode to NONE.
Definition at line 60 of file Score.cpp.
References reverbObj.
Member Function Documentation
void Score::anticlip (MultiTrack * mt) [static, private]
This private function unclips the MultiTrack.
Parameters:
mt The MultiTrack to unclip
Definition at line 390 of file Score.cpp.
References Collection< Track * >::get(), Track::getAmp(), Track::getWave(), m_sample_count_type, m_sample_type, and Collection< Track * >::size().
Referenced by manageClipping().
void Score::channelAnticlip (MultiTrack * mt) [static, private]
This private function unclips the channels in a MultiTrack.
Parameters:
mt The MultiTrack to unclip
Definition at line 430 of file Score.cpp.
References Collection< Track * >::get(), Track::getAmp(), SoundSample::getSampleCount(), Track::getWave(), m_sample_count_type, and Collection< Track * >::size().
Referenced by manageClipping().
void Score::channelScale (MultiTrack * mt) [static, private]
This private function scales the channels in the MultiTrack.
Parameters:
mt The MultiTrack to scale
Definition at line 352 of file Score.cpp.
References Collection< Track * >::get(), Track::getAmp(), SoundSample::getSampleCount(), Track::getWave(), m_sample_count_type, m_sample_type, and Collection< Track * >::size().
Referenced by manageClipping().
void Score::clip (MultiTrack * mt) [static, private]
This private function clips the MultiTrack.
Parameters:
mt The MultiTrack to clip
Definition at line 284 of file Score.cpp.
References Collection< Track * >::get(), Track::getAmp(), SoundSample::getSampleCount(), Track::getWave(), m_sample_count_type, and Collection< Track * >::size().
Referenced by manageClipping().
Score::ClippingManagementMode Score::getClippingManagementMode ()
This function gets the current ClippingManagementMode for this score.
Returns: The ClippingManagementMode
Definition at line 251 of file Score.cpp.
References ClippingManagementMode, and cmm_.
Referenced by xml_print().
void Score::manageClipping (MultiTrack * mt, ClippingManagementMode mode) [static]
This function manages clipping on a MultiTrack object with the specified mode. This is performed automatically when a score is rendered, but is available for the user to render once, then post-process many times.
Parameters:
mt The MultiTrack to clip
mode The ClippingManagementMode
Definition at line 258 of file Score.cpp.
References anticlip(), ANTICLIP, CHANNEL_ANTICLIP, CHANNEL_SCALE, channelAnticlip(), channelScale(), clip(), CLIP, NONE, scale(), and SCALE.
Referenced by render().
MultiTrack * Score::render (int numChannels, m_rate_type samplingRate, int nThreads)
This function:
Renders each sound in this Score using a specified number of threads for parallel rendering
Composites the sounds into a MultiTrack object
Post-Processes the sound for clipping management
Note: The caller must delete this object. Also, the caller must specify a value for samplingRate (unlike single-threaded render)
Parameters:
numChannels The number of channels to render
samplingRate The sampling rate
nThreads The number of threads to use when rendering
Returns: a MultiTrack object
Definition at line 132 of file Score.cpp.
References Collection< T >::add(), cmm_, MultiTrack::composite(), Reverb::do_reverb_MultiTrack(), threadlist_entry::done, threadlist_entry::finishCondition, Collection< T >::get(), Reverb::getDecay(), ParameterLib< SoundStaticParam, SoundDynamicParam >::getParam(), Sound::getTotalDuration(), Iterator< T >::hasNext(), Collection< Sound >::iterator(), threadlist_entry::listMutex, m_rate_type, m_sample_count_type, m_time_type, manageClipping(), multithreaded_render_worker(), Iterator< T >::next(), threadlist_entry::numChannels, threadlist_entry::resultTrack, reverbObj, threadlist_entry::samplingRate, Collection< Sound >::size(), threadlist_entry::snd, START_TIME, and threadlist_entry::thread.
MultiTrack * Score::render (int numChannels, m_rate_type samplingRate = DEFAULT_SAMPLING_RATE)
This function:
Renders each sound in this Score.
Composites the sounds into a MultiTrack object
Post-Processes the sound for clipping management
Note: The caller must delete this object.
Parameters:
numChannels The number of channels to render
samplingRate The sampling rate which defaults to DEFAULT_SAMPLING_RATE
Returns: A MultiTrack object
Definition at line 67 of file Score.cpp.
References cmm_, MultiTrack::composite(), Reverb::do_reverb_MultiTrack(), Reverb::getDecay(), ParameterLib< SoundStaticParam, SoundDynamicParam >::getParam(), Sound::getTotalDuration(), Iterator< T >::hasNext(), Collection< Sound >::iterator(), m_rate_type, m_sample_count_type, m_time_type, manageClipping(), Iterator< T >::next(), Sound::render(), reverbObj, and START_TIME.
void Score::scale (MultiTrack * mt) [static, private]
This private function scales the MultiTrack.
Parameters:
mt The MultiTrack to scale
Definition at line 308 of file Score.cpp.
References Collection< Track * >::get(), Track::getAmp(), SoundSample::getSampleCount(), Track::getWave(), m_sample_count_type, m_sample_type, and Collection< Track * >::size().
Referenced by manageClipping().
void Score::setClippingManagementMode (ClippingManagementMode mode)
This function sets the ClippingManagementMode for this score.
Parameters:
mode The ClippingManagementMode to set
Definition at line 245 of file Score.cpp.
References cmm_.
Referenced by xml_read().
void Score::use_reverb (Reverb * newReverbObj)
This function performs reverb in the render() method.
Parameters:
newReverbObj The Reverb object
Definition at line 273 of file Score.cpp.
References reverbObj.
Referenced by xml_read().
void Score::xml_print (const char * xmlOutputPath)
Deprecated
Definition at line 567 of file Score.cpp.
References xml_print().
void Score::xml_print (ofstream & xmlOutput)
Deprecated
Definition at line 524 of file Score.cpp.
References getClippingManagementMode(), Iterator< T >::hasNext(), Collection< Sound >::iterator(), Iterator< T >::next(), reverbObj, and Sound::xml_print().
void Score::xml_print ()
Deprecated This outputs an XML representation of the object to STDOUT
Definition at line 580 of file Score.cpp.
Referenced by xml_print().
void Score::xml_read (XmlReader::xmltag * scoretag)
Deprecated
Definition at line 456 of file Score.cpp.
References Collection< Sound >::add(), XmlReader::xmltag::children, ClippingManagementMode, DynamicVariable::create_dv_from_xml(), dvHash, XmlReader::xmltag::findChildParamValue(), XmlReader::xmltag::getParamValue(), XmlReader::xmltag::name, reverbHash, setClippingManagementMode(), use_reverb(), Sound::xml_read(), and Reverb::xml_read().
Member Data Documentation
ClippingManagementMode Score::cmm_ [private]
Definition at line 221 of file Score.h.
Referenced by getClippingManagementMode(), render(), and setClippingManagementMode().
hash_map<long, DynamicVariable *>* Score::dvHash
Definition at line 218 of file Score.h.
Referenced by xml_read().
hash_map<long, Reverb *>* Score::reverbHash
Definition at line 217 of file Score.h.
Referenced by xml_read().
Reverb* Score::reverbObj [private]
Definition at line 223 of file Score.h.
Referenced by render(), Score(), use_reverb(), and xml_print().
The documentation for this class was generated from the following files:
Score.h
Score.cpp