DynamicVariable Class Reference
#include <DynamicVariable.h>
Public Member Functions
DynamicVariable ()
virtual ~DynamicVariable ()
virtual DynamicVariable * clone ()=0
virtual Iterator< m_value_type > valueIterator ()=0
virtual void scale (m_value_type factor)=0
virtual m_value_type getMaxValue ()=0
void setDuration (m_time_type duration)
m_time_type getDuration ()
void setSamplingRate (m_rate_type rate)
m_rate_type getSamplingRate ()
m_sample_count_type getSampleCount ()
virtual void xml_print (ofstream &xmlOutput, list< DynamicVariable * > &dynObjs)=0
virtual void xml_print (ofstream &xmlOutput)=0
Static Public Member Functions
DynamicVariable * create_dv_from_xml (XmlReader::xmltag *dvtag)
Private Attributes
m_time_type duration_
m_rate_type rate_
Detailed Description
An abstract definition of a simple Dynamic Variable. This simply defines an m_value_type that changes over time. Any implemention that derives from DynamicVariable can be added.
Author: Braden Kowitz
Definition at line 55 of file DynamicVariable.h.
Constructor & Destructor Documentation
DynamicVariable::DynamicVariable ()
Default constructor for DynamicVariables. Sets the length to 1 second. Sets the rate to DEFAULT_SAMPLING_RATE
Definition at line 42 of file DynamicVariable.cpp.
virtual DynamicVariable::~DynamicVariable () [inline, virtual]
Destructor.
Definition at line 69 of file DynamicVariable.h.
Member Function Documentation
virtual DynamicVariable* DynamicVariable::clone () [pure virtual]
Creates an exact duplicate of this variable.
Implemented in Constant, DynamicVariableSequence, Envelope, Interpolator, LinearInterpolator, ExponentialInterpolator, and CubicSplineInterpolator.
Referenced by Partial::render(), Pan::set(), and ParameterLib< StaticT, DynamicT >::setParam().
DynamicVariable * DynamicVariable::create_dv_from_xml (XmlReader::xmltag * dvtag) [static]
Deprecated This create a DynamicVariable from xml
Parameters:
dvtag Some xml
Returns: A DynamicVariable
Definition at line 80 of file DynamicVariable.cpp.
References CUBIC_SPLINE, EXPONENTIAL, XmlReader::xmltag::findChildParamValue(), LINEAR, Interpolator::xml_read(), Envelope::xml_read(), and Constant::xml_read().
Referenced by Partial::auxLoadParam(), and Score::xml_read().
m_time_type DynamicVariable::getDuration ()
Returns the Length in seconds of this Dynamic Variablei
Returns: The duration in seconds
Definition at line 54 of file DynamicVariable.cpp.
References duration_, and m_time_type.
Referenced by CubicSplineInterpolator::valueIterator(), ExponentialInterpolator::valueIterator(), LinearInterpolator::valueIterator(), Envelope::valueIterator(), DynamicVariableSequence::valueIterator(), Interpolator::xml_print(), Envelope::xml_print(), DynamicVariableSequence::xml_print(), and Constant::xml_print().
virtual m_value_type DynamicVariable::getMaxValue () [pure virtual]
Returns the maximum value present in this variable.
Returns: the max value
Implemented in Constant, DynamicVariableSequence, Envelope, and Interpolator.
Referenced by Loudness::calculate().
m_sample_count_type DynamicVariable::getSampleCount ()
Returns the number of samples at the current length and rate.
Returns: number of samples
Definition at line 73 of file DynamicVariable.cpp.
References duration_, m_sample_count_type, and rate_.
Referenced by Constant::valueIterator().
m_rate_type DynamicVariable::getSamplingRate ()
Returns the sampling rate.
Returns: The sampling rate
Definition at line 67 of file DynamicVariable.cpp.
References m_rate_type, and rate_.
Referenced by CubicSplineInterpolator::valueIterator(), ExponentialInterpolator::valueIterator(), LinearInterpolator::valueIterator(), Envelope::valueIterator(), DynamicVariableSequence::valueIterator(), Interpolator::xml_print(), Envelope::xml_print(), DynamicVariableSequence::xml_print(), and Constant::xml_print().
virtual void DynamicVariable::scale (m_value_type factor) [pure virtual]
Scales this DynamicIterator by the given factor.
Parameters:
factor The scaling factor
Implemented in Constant, DynamicVariableSequence, Envelope, and Interpolator.
void DynamicVariable::setDuration (m_time_type duration)
Sets the length of this dynamic variable. Will also affect the sample count for this variable.
Parameters:
duration The duration
Definition at line 48 of file DynamicVariable.cpp.
References duration_, and m_time_type.
Referenced by Envelope::addInterpolators(), DynamicVariableSequence::addInterpolators(), Loudness::calculate(), Envelope::getValue(), DynamicVariableSequence::getValue(), Partial::render(), Pan::spatialize(), Interpolator::xml_read(), Envelope::xml_read(), and Constant::xml_read().
void DynamicVariable::setSamplingRate (m_rate_type rate)
Sets the sampling rate for this dynamic variable. Will also affect the sample count for this variable.
Parameters:
rate The sampling rate
Definition at line 61 of file DynamicVariable.cpp.
References m_rate_type, and rate_.
Referenced by Envelope::addInterpolators(), DynamicVariableSequence::addInterpolators(), Loudness::calculate(), Envelope::getValue(), DynamicVariableSequence::getValue(), Partial::render(), Pan::spatialize(), Interpolator::xml_read(), Envelope::xml_read(), and Constant::xml_read().
virtual Iterator<m_value_type> DynamicVariable::valueIterator () [pure virtual]
Returns an iterator object that will iterate over all values in this DynamicVariable.
Returns: An iterator
Implemented in Constant, DynamicVariableSequence, Envelope, Interpolator, LinearInterpolator, ExponentialInterpolator, and CubicSplineInterpolator.
Referenced by Loudness::calculate(), Partial::render(), and Pan::spatialize().
virtual void DynamicVariable::xml_print (ofstream & xmlOutput) [pure virtual]
Deprecated This outputs an XML representation of the object to STDOUT
Implemented in Constant, DynamicVariableSequence, Envelope, and Interpolator.
virtual void DynamicVariable::xml_print (ofstream & xmlOutput, list< DynamicVariable * > & dynObjs) [pure virtual]
Deprecated This outputs an XML representation of the object to STDOUT
Implemented in Constant, DynamicVariableSequence, Envelope, and Interpolator.
Referenced by Partial::xml_print().
Member Data Documentation
m_time_type DynamicVariable::duration_ [private]
The duration
Definition at line 155 of file DynamicVariable.h.
Referenced by getDuration(), getSampleCount(), and setDuration().
m_rate_type DynamicVariable::rate_ [private]
The sampling rate
Definition at line 160 of file DynamicVariable.h.
Referenced by getSampleCount(), getSamplingRate(), and setSamplingRate().
The documentation for this class was generated from the following files:
DynamicVariable.h
DynamicVariable.cpp