Filter Class Reference
#include <Filter.h>
Public Member Functions
MultiTrack & do_filter_MultiTrack (MultiTrack &inWave)
Track & do_filter_Track (Track &inWave)
SoundSample * do_filter_SoundSample (SoundSample *inWave)
virtual m_sample_type do_filter (m_sample_type x_t)=0
virtual void reset (void)=0
Detailed Description
The filter class is a pure virtual class only meant to ensure that all filters have a common interface. The idea is that a collection of filters, specified by the user at run-time, perhaps, could be applied one after the next without regard to what type of filter each one is.
Each filter will likely have its own configuration that can be done, and if, in the future, this becomes something that needs to be generalized as well, perhaps this class could be expanded to include a ParameterLib.
Note: The Filter objects are stateful machines with internal feedback mechanisms. Thus this filter should be allocated anew each time you begin a new channel and should not be mixed between channels.
Author: Jim Lindstrom
Definition at line 52 of file Filter.h.
Member Function Documentation
virtual m_sample_type Filter::do_filter (m_sample_type x_t) [pure virtual]
This method should be redefined by each class derived from Filter to perform the actual filtering. It should take in a single sample and return the filtered sample. If, in the future, real-time filtering should become feasible and is desired, this is the entry-point to use.
Parameters:
x_t A sample to filter
Returns: the filtered sample
Implemented in AllPassFilter, LowPassFilter, and LPCombFilter.
Referenced by do_filter_SoundSample().
MultiTrack & Filter::do_filter_MultiTrack (MultiTrack & inWave)
This method applies the filter to a MultiTrack source, track by track. It does so by decomposing the wave into Track objects (organized as a Collection inside the MultiTrack object) and calling the virtual function, do_filter(SoundSample *inWave), for each Track.
Parameters:
inWave A reference to a MultiTrack object to Filter
Returns: A reference to a NEW MultiTrack, which the caller is responsible for deleting when done. The original MultiTrack remains intact and untouched
Definition at line 40 of file Filter.cpp.
References Collection< Track * >::add(), do_filter_SoundSample(), Iterator< T >::hasNext(), Collection< Track * >::iterator(), Iterator< T >::next(), and reset().
SoundSample * Filter::do_filter_SoundSample (SoundSample * inWave)
This method calls do_filter(m_sample_type x) for each sample in a track and builds a new SoundSample on the fly.
Parameters:
inWave A pointer to a SoundSample object to Filter
Returns: A reference to a NEW MultiTrack, which the caller is responsible for deleting when done. The original Track remains intact and untouched
Definition at line 84 of file Filter.cpp.
References do_filter(), SoundSample::getSampleCount(), and SoundSample::getSamplingRate().
Referenced by do_filter_MultiTrack(), and do_filter_Track().
Track & Filter::do_filter_Track (Track & inWave)
This method applies the filter to a source Track by calling the virtual function, do_filter(SoundSample *inWave).
Parameters:
inWave A reference to a Track object to Filter
Returns: A reference to a NEW MultiTrack, which the caller is responsible for deleting when done. The original Track remains intact and untouched.
Definition at line 69 of file Filter.cpp.
References do_filter_SoundSample(), and Track::getWave().
virtual void Filter::reset (void) [pure virtual]
This method should be redefined by each class derived from Filter to reset the filter to an initial state. It should have the same effect as deleting the filter and creating a new one.
Implemented in AllPassFilter, LowPassFilter, and LPCombFilter.
Referenced by do_filter_MultiTrack().
The documentation for this class was generated from the following files:
Filter.h
Filter.cpp