Collection< T > Class Template Reference
#include <Collection.h>
Public Member Functions
Collection ()
Collection (const Collection &c)
virtual ~Collection ()
Collection & operator= (const Collection &c)
void add (const T &element)
void add (int index, const T &element)
void clear ()
T & get (int index)
T remove (int index)
T set (int index, const T &element)
int size ()
void sortCollection ()
Iterator< T > iterator ()
void printPointers (char *collType)
Private Attributes
vector< T > vector_
Detailed Description
template<class T> class Collection< T >
Represents a collection of objects. They are kept in order, with consecutive index numbers running from 0 to (size-1). Each entry is also accompanied by a string name. Note: This class is heavily modeled from Java Collection and Vector
Author: Braden Kowitz
Definition at line 49 of file Collection.h.
Constructor & Destructor Documentation
template<class T> Collection< T >::Collection ()
This is the default constructor, which creates an empty collection.
Definition at line 42 of file Collection.cpp.
template<class T> Collection< T >::Collection (const Collection< T > & c)
This is a copy constructor.
Parameters:
c The Collection from which to make a copy
Definition at line 47 of file Collection.cpp.
References Collection< T >::vector_.
template<class T> Collection< T >::~Collection () [virtual]
This is the destructor.
Definition at line 55 of file Collection.cpp.
Member Function Documentation
template<class T> void Collection< T >::add (int index, const T & element)
Inserts the given element at the specified index. The element at that index, and subsequent elements are shifted to the right.
Note: This will make a COPY of the element in the Collection.
Exceptions:
IndexOutOfBoundsException
Parameters:
index An integer specifying where to insert the element
element The element to insert
Definition at line 96 of file Collection.cpp.
References Collection< T >::vector_.
template<class T> void Collection< T >::add (const T & element)
Appends the given element to the end of the Collection.
Note: This will make a COPY of the element in the Collection.
Parameters:
element An element to add to the collection
Definition at line 85 of file Collection.cpp.
References Collection< T >::vector_.
Referenced by Envelope::Envelope(), Envelope::getPoints(), EnvelopeLibrary::loadLibrary(), Envelope::multiply(), Collection< T >::operator=(), Score::render(), and Envelope::xml_read().
template<class T> void Collection< T >::clear ()
Clears every element from the collection.
Definition at line 113 of file Collection.cpp.
References Collection< T >::vector_.
Referenced by EnvelopeLibrary::loadLibrary(), and Collection< T >::operator=().
template<class T> T & Collection< T >::get (int index)
Exceptions:
IndexOutOfBoundsException
Parameters:
index An integer specifying which element to retrieve
Returns: A reference to the element at the specified index
Definition at line 119 of file Collection.cpp.
References Collection< T >::vector_.
Referenced by Envelope::DefineShape(), Envelope::Envelope(), Envelope::multiply(), and Score::render().
template<class T> Iterator< T > Collection< T >::iterator ()
Returns an iterator over the elements in this collection.
Returns: an iteration
Definition at line 182 of file Collection.cpp.
References Collection< T >::vector_.
template<class T> Collection< T > & Collection< T >::operator= (const Collection< T > & c)
This assigns one Collection to another.
Parameters:
c The Collection to assign
Definition at line 61 of file Collection.cpp.
References Collection< T >::add(), Collection< T >::clear(), and Collection< T >::vector_.
template<class T> void Collection< T >::printPointers (char * collType)
Definition at line 220 of file Collection.cpp.
References Collection< T >::vector_.
template<class T> T Collection< T >::remove (int index)
Removes the element at the specified index. All other elements are shifted left to fill the hole.
Exceptions:
IndexOutOfBoundsException
Parameters:
index An integer specifying which element to delete
Returns: A reference to the element at the specified index
Definition at line 133 of file Collection.cpp.
References Collection< T >::vector_.
template<class T> T Collection< T >::set (int index, const T & element)
Replaces the element at the specified index.
Exceptions:
IndexOutOfBoundsException
Parameters:
index An integer specifying which element to replace
element An element to replace the old one
Returns: A reference to the element that was replaced
Definition at line 153 of file Collection.cpp.
References Collection< T >::vector_.
Referenced by Envelope::DefineShape().
template<class T> int Collection< T >::size ()
Returns the size of this collection. This is a 0-based array so the entries are indexed from 0 to (size-1).
Returns: The size of the collection
Definition at line 169 of file Collection.cpp.
References Collection< T >::vector_.
Referenced by Envelope::DefineShape(), DynamicVariableSequenceIterator::DynamicVariableSequenceIterator(), Envelope::Envelope(), and EnvelopeIterator::EnvelopeIterator().
template<class T> void Collection< T >::sortCollection ()
This sorts the collection.
Note: only use this function if template type of this collection has well defined operator< , operator== , and operator> . Examples of this are standard types like int and float, as well as custom types like LinearInterpolatorEntry.
Definition at line 176 of file Collection.cpp.
References Collection< T >::vector_.
Member Data Documentation
template<class T> vector<T> Collection< T >::vector_ [private]
Definition at line 151 of file Collection.h.
Referenced by Collection< T >::add(), Collection< T >::clear(), Collection< T >::Collection(), Collection< T >::get(), Collection< T >::iterator(), Collection< T >::operator=(), Collection< T >::printPointers(), Collection< T >::remove(), Collection< T >::set(), Collection< T >::size(), and Collection< T >::sortCollection().
The documentation for this class was generated from the following files:
Collection.h
Collection.cpp