Reverb Class Reference
#include <Reverb.h>
Public Member Functions
Reverb (m_rate_type samplingRate)
Reverb (float room_size, m_rate_type samplingRate)
Reverb (float reverbPercent, float hilow_spread, float gainAllPass, float delay, m_rate_type samplingRate)
Reverb (float reverbPercent, float *combGainList, float *lpGainList, float gainAllPass, float delay, m_rate_type samplingRate)
void ConstructorCommon (float percentReverb, float *combGainList, float *lpGainList, float gainAllPass, float delay, m_rate_type samplingRate)
~Reverb ()
m_sample_type do_reverb (m_sample_type x_t)
void reset (void)
MultiTrack & do_reverb_MultiTrack (MultiTrack &inWave)
Track & do_reverb_Track (Track &inWave)
SoundSample * do_reverb_SoundSample (SoundSample *inWave)
float getDecay (void)
void xml_print (ofstream &xmlOutput)
void set_gainDirect (float new_gainDirect)
void set_gainReverb (float new_gainReverb)
void set_allPassDelay (float new_allPassDelay)
void set_decay_duration (float new_decay_duration)
void setLPComb (int idx, LPCombFilter *f)
void setAllPass (AllPassFilter *f)
void xml_read (XmlReader::xmltag *reverbtag)
Private Member Functions
SoundSample * constructAmp (SoundSample *wave)
Private Attributes
float gainDirect
float gainReverb
float allPassDelay
LPCombFilter * lpcfilter [REVERB_NUM_COMB_FILTERS]
AllPassFilter * apfilter
float decay_duration
Detailed Description
This is an artificial reverberator class. The Reverb class implements an artificial reverberator, built on the model in Moore's `Elements of Computer Music` book. That model, in turn, is based on Schroder's and Moorer's work.
In order to use this class you need to do three things 1. Create a reverb object using the parameters you want. There are a few different constructors to choose from, depending on how much control you want to have (and thus, how much you want to be burdened with details). 2. Call a Sound, Track, or MultiTrack object's use_reverb method and pass in your Reverb object as the parameter. 3. Render the corresponding object and let reverb run (the sound, track, or multitrack will call Reverb::do_reverb for you once you call its use_reverb member to setup a reverb object).
Note: Reverb relies on some filters with feedback and delay, thus the filters are partially dependent on old data sent to Reverb. In order to clear out the history in these filters, call Reverb::Reset before reusing a Reverb object.
Author: Andrew Kurtz
Jim Lindstrom
Definition at line 71 of file Reverb.h.
Constructor & Destructor Documentation
Reverb::Reverb (m_rate_type samplingRate)
This is the default constructor which uses default values for everything.
Parameters:
samplingRate The number of samples per second that the reverb will assume on any data it is fed
Definition at line 49 of file Reverb.cpp.
References ConstructorCommon(), m_rate_type, and REVERB_NUM_COMB_FILTERS.
Reverb::Reverb (float room_size, m_rate_type samplingRate)
This is a simple constructor.
Parameters:
room_size this is constructed to give some reasonable results when you input room_size values between 0.0 and 1.0. I found some parameter sets that I felt approximated various familiar rooms (lincoln hall, MB 1201, great hall, a large stadium, etc), and mapped these into a room_size space of 0.0 to 1.0. Then I used gnumeric (spreadsheet for linux, like excel) to find a linear regression to get all the parameters simply in terms of room_size. Thus a value of 0.0 will have virtually no reverb. A value of 1.0 will have a very high degree of reverb.
samplingRate The number of samples per second that the reverb will assume on any data it is fed
Definition at line 70 of file Reverb.cpp.
References ConstructorCommon(), m_rate_type, and REVERB_NUM_COMB_FILTERS.
Reverb::Reverb (float reverbPercent, float hilow_spread, float gainAllPass, float delay, m_rate_type samplingRate)
This is a moderately advanced constructor.
Parameters:
reverbPercent This determines the mix (in the resultant sound) between the direct sound (the input sound) and the reverbed sound. The value 0.0 is no reverb, all direct sound; 1.0 is all reverb, no direct sound.
hilow_spread In most rooms the low frequecy response will be higher than the high frequency response. If we hold other parameters constant, the math gives a range of possible ratios between low frequence to high frequence response. A value of 1.0 will choose the maximum low-frequence response, holding the high-frequency response at a given. A value of 0.0 will mean an even response across all frequencies.
gainAllPass Moore's reverberator has only one all-pass filter, and this is its gain. The default value is 0.7. Higher values (up to 1.0) cause more ringing at certain frequencies. Lower values (down to 0.0) cause less ringing.
delay This is the length (in seconds) of the first echo response.
samplingRate The number of samples per second that the reverb will assume on any data it is fed
Definition at line 95 of file Reverb.cpp.
References ConstructorCommon(), m_rate_type, and REVERB_NUM_COMB_FILTERS.
Reverb::Reverb (float reverbPercent, float * combGainList, float * lpGainList, float gainAllPass, float delay, m_rate_type samplingRate)
This is an advanced constructor.
Parameters:
reverbPercent This determines the mix (in the resultant sound) between the direct sound (the input sound) and the reverbed sound. The value 0.0 is no reverb, all direct sound; 1.0 is all reverb, no direct sound.
combGainList This is the address of an array of 6 floats that are the comb filter gains.
lpGainList This is the address of an array of 6 floats that are the low-pass filter gains.
gainAllPass Moore's reverberator has only one all-pass filter, and this is its gain. The default value is 0.7. Higher values (up to 1.0) cause more ringing at certain frequencies. Lower values (down to 0.0) cause less ringing.
delay The length (in seconds) of the first echo response
samplingRate The number of samples per second that the reverb will assume on any data it is fed
Definition at line 140 of file Reverb.cpp.
References ConstructorCommon(), and m_rate_type.
Reverb::~Reverb ()
This is the destructor. This will destroy the filters and release any dynamically allocated memory.
Definition at line 219 of file Reverb.cpp.
References apfilter, lpcfilter, and REVERB_NUM_COMB_FILTERS.
Member Function Documentation
SoundSample * Reverb::constructAmp (SoundSample * wave) [private]
This reconstructs an Amp SoundSample given the Wave SoundSample. The input SoundSample is unmodified. The returned SoundSample has been allocated with 'new' and is the caller's responsibility to 'delete' at some point.
Parameters:
wave A pointer to the 'wave' component of a Track
Returns: A new SoundSample to be used as the 'amp' component of a Track
Definition at line 379 of file Reverb.cpp.
References SoundSample::getSampleCount(), SoundSample::getSamplingRate(), m_rate_type, m_sample_count_type, and m_sample_type.
Referenced by do_reverb_MultiTrack(), and do_reverb_Track().
void Reverb::ConstructorCommon (float percentReverb, float * combGainList, float * lpGainList, float gainAllPass, float delay, m_rate_type samplingRate)
This contains common code used by all constructors
Parameters:
percentReverb This determines the mix (in the resultant sound) between the direct sound (the input sound) and the reverbed sound. The value 0.0 is no reverb, all direct sound; 1.0 is all reverb, no direct sound.
combGainList This is the address of an array of 6 floats that are the comb filter gains.
lpGainList This is the address of an array of 6 floats that are the low-pass filter gains.
gainAllPass Moore's reverberator has only one all-pass filter, and this is its gain. The default value is 0.7. Higher values (up to 1.0) cause more ringing at certain frequencies. Lower values (down to 0.0) cause less ringing.
delay The length (in seconds) of the first echo response
samplingRate The number of samples per second that the reverb will assume on any data it is fed
Definition at line 179 of file Reverb.cpp.
References allPassDelay, apfilter, decay_duration, gainDirect, gainReverb, lpcfilter, m_rate_type, m_time_type, and REVERB_NUM_COMB_FILTERS.
Referenced by Reverb().
m_sample_type Reverb::do_reverb (m_sample_type x_t)
This method applies reverb to a single sample.
Parameters:
x_t The sample to apply reverb to
Returns: The new sample
Definition at line 232 of file Reverb.cpp.
References apfilter, AllPassFilter::do_filter(), LPCombFilter::do_filter(), gainDirect, gainReverb, lpcfilter, m_sample_type, and REVERB_NUM_COMB_FILTERS.
Referenced by do_reverb_SoundSample().
MultiTrack & Reverb::do_reverb_MultiTrack (MultiTrack & inWave)
This method applies reverb to a source MultiTrack, track by track. It does so by decomposing the wave into Track objects (organized with a Collection inside the MultiTrack object) and calling the virtual function, do_reverb(SoundSample *inWave), for each Track.
Parameters:
inWave The MultiTrack to apply reverb to
Returns: The original MultiTrack remains intact and untouched. The return is a reference to a NEW MultiTrack, which the caller is responsible for deleting when done.
Definition at line 278 of file Reverb.cpp.
References Collection< Track * >::add(), constructAmp(), do_reverb_SoundSample(), Track::getWave(), Iterator< T >::hasNext(), Collection< Track * >::iterator(), Iterator< T >::next(), and reset().
Referenced by Score::render().
SoundSample * Reverb::do_reverb_SoundSample (SoundSample * inWave)
This method calls do_reverb(m_sample_type x) for each sample in a track and builds a new SoundSample on the fly.
Parameters:
inWave The SoundSample to apply reverb to
Returns: The original TraSoundSample remains intact and untouched. The return is a reference to a NEW SoundSample, which the caller is responsible for deleting when done.
Definition at line 330 of file Reverb.cpp.
References do_reverb(), SoundSample::getSampleCount(), and SoundSample::getSamplingRate().
Referenced by do_reverb_MultiTrack(), and do_reverb_Track().
Track & Reverb::do_reverb_Track (Track & inWave)
This method applies the reverb to a source Track by calling the virtual function, do_reverb(SoundSample *inWave)
Parameters:
inWave The Track to apply reverb to
Returns: The original Track remains intact and untouched. The return is a reference to a NEW Track, which the caller is responsible for deleting when done.
Definition at line 311 of file Reverb.cpp.
References constructAmp(), do_reverb_SoundSample(), Track::getWave(), and reset().
Referenced by Sound::render(), and Partial::render().
float Reverb::getDecay (void)
This retrieves the decay length. It is intended to be used by Sound, Score, and Partial objects to figure out how many samples to allocate for a sound. I.e., the object must add enough cycles to the end of a sound for the delay to die out. It is in units of seconds.
Returns: The decay time (in seconds)
Definition at line 349 of file Reverb.cpp.
References decay_duration.
Referenced by Sound::getTotalDuration(), Partial::getTotalDuration(), Score::render(), and Partial::render().
void Reverb::reset (void)
This method resets internal parameters in the reverberator to an initial state. The Reverb class relies on some filters with feedback and delay, thus the filters are partially dependent on old data sent to Reverb. In order to clear out the history in these filters, call Reverb::Reset before reusing a Reverb object.
Definition at line 266 of file Reverb.cpp.
References apfilter, lpcfilter, AllPassFilter::reset(), LPCombFilter::reset(), and REVERB_NUM_COMB_FILTERS.
Referenced by do_reverb_MultiTrack(), and do_reverb_Track().
void Reverb::set_allPassDelay (float new_allPassDelay)
Used to reconstruct a Reverb object. This sets the reverb's internal member data and, in general, shouldn't be used anywhere else.
Definition at line 518 of file Reverb.cpp.
References allPassDelay.
Referenced by xml_read().
void Reverb::set_decay_duration (float new_decay_duration)
Used to reconstruct a Reverb object. This sets the reverb's internal member data and, in general, shouldn't be used anywhere else.
Definition at line 522 of file Reverb.cpp.
References decay_duration.
Referenced by xml_read().
void Reverb::set_gainDirect (float new_gainDirect)
Used to reconstruct a Reverb object. This sets the reverb's internal member data and, in general, shouldn't be used anywhere else.
Definition at line 510 of file Reverb.cpp.
References gainDirect.
Referenced by xml_read().
void Reverb::set_gainReverb (float new_gainReverb)
Used to reconstruct a Reverb object. This sets the reverb's internal member data and, in general, shouldn't be used anywhere else.
Definition at line 514 of file Reverb.cpp.
References gainReverb.
Referenced by xml_read().
void Reverb::setAllPass (AllPassFilter * f)
Used to reconstruct a Reverb object. This sets the reverb's internal member data and, in general, shouldn't be used anywhere else.
Definition at line 530 of file Reverb.cpp.
References apfilter.
Referenced by xml_read().
void Reverb::setLPComb (int idx, LPCombFilter * f)
Used to reconstruct a Reverb object. This sets the reverb's internal member data and, in general, shouldn't be used anywhere else.
Definition at line 526 of file Reverb.cpp.
References lpcfilter.
Referenced by xml_read().
void Reverb::xml_print (ofstream & xmlOutput)
Deprecated This outputs an XML representation of the object to STDOUT
Definition at line 440 of file Reverb.cpp.
References allPassDelay, apfilter, decay_duration, gainDirect, gainReverb, lpcfilter, REVERB_NUM_COMB_FILTERS, AllPassFilter::xml_print(), and LPCombFilter::xml_print().
void Reverb::xml_read (XmlReader::xmltag * reverbtag)
Deprecated Used by XML parsing code to reconstruct a Reverb object. This sets the reverb's internal member data and, in general, shouldn't be used anywhere else.
Definition at line 461 of file Reverb.cpp.
References XmlReader::xmltag::children, XmlReader::xmltag::findChildParamValue(), XmlReader::xmltag::name, set_allPassDelay(), set_decay_duration(), set_gainDirect(), set_gainReverb(), setAllPass(), setLPComb(), AllPassFilter::xml_read(), and LPCombFilter::xml_read().
Referenced by Score::xml_read().
Member Data Documentation
float Reverb::allPassDelay [private]
Definition at line 293 of file Reverb.h.
Referenced by ConstructorCommon(), set_allPassDelay(), and xml_print().
AllPassFilter* Reverb::apfilter [private]
Definition at line 295 of file Reverb.h.
Referenced by ConstructorCommon(), do_reverb(), reset(), setAllPass(), xml_print(), and ~Reverb().
float Reverb::decay_duration [private]
Definition at line 296 of file Reverb.h.
Referenced by ConstructorCommon(), getDecay(), set_decay_duration(), and xml_print().
float Reverb::gainDirect [private]
Definition at line 291 of file Reverb.h.
Referenced by ConstructorCommon(), do_reverb(), set_gainDirect(), and xml_print().
float Reverb::gainReverb [private]
Definition at line 292 of file Reverb.h.
Referenced by ConstructorCommon(), do_reverb(), set_gainReverb(), and xml_print().
LPCombFilter* Reverb::lpcfilter[REVERB_NUM_COMB_FILTERS] [private]
Definition at line 294 of file Reverb.h.
Referenced by ConstructorCommon(), do_reverb(), reset(), setLPComb(), xml_print(), and ~Reverb().
The documentation for this class was generated from the following files:
Reverb.h
Reverb.cpp