EnvelopeLibrary Class Reference
#include <EnvelopeLibrary.h>
Public Member Functions
EnvelopeLibrary ()
~EnvelopeLibrary ()
EnvelopeLibrary (EnvelopeLibrary &lib)
EnvelopeLibrary & operator= (EnvelopeLibrary &lib)
bool saveLibrary (char *filename)
int loadLibrary (char *filename)
Envelope * getEnvelope (int index)
int addEnvelope (Envelope *env)
int addEnvelope (Collection< xy_point > points, Collection< envelope_segment > segments)
bool updateEnvelope (int index, Envelope *env)
void showEnvelope (int index)
int size ()
Private Attributes
Collection< Envelope * > library
Detailed Description
This class manages a collection of Envelopes, providing methods for loading and saving the collection to a library file as well as functionality for adding to, retrieving from, updating the collection with, and displaying individual Envelope items. The name Envelope is used informally to designate an Envelope.
Note: All methods in this class that take an index argument begin with a first value of 1 for user ease, though the actual Collection indices begin at 0.
Author: Philipp Fraund
Definition at line 48 of file EnvelopeLibrary.h.
Constructor & Destructor Documentation
EnvelopeLibrary::EnvelopeLibrary ()
This is the Constructor.
Definition at line 42 of file EnvelopeLibrary.cpp.
EnvelopeLibrary::~EnvelopeLibrary ()
This is the destructor. It deallocates all the Envelopes stored in the library.
Definition at line 46 of file EnvelopeLibrary.cpp.
References library, Collection< Envelope * >::remove(), and Collection< Envelope * >::size().
EnvelopeLibrary::EnvelopeLibrary (EnvelopeLibrary & lib)
This is a copy constructor.
Parameters:
lib The EnvelopeLibrary to copy
Returns: A copy of lib
Definition at line 54 of file EnvelopeLibrary.cpp.
References Collection< Envelope * >::add(), Envelope::clone(), Collection< Envelope * >::get(), library, and Collection< Envelope * >::size().
Member Function Documentation
int EnvelopeLibrary::addEnvelope (Collection< xy_point > points, Collection< envelope_segment > segments)
This function adds a Collection of n+1 points and a Collection of n segments to the EnvelopeLibrary and returns the index at which it has been added.
Parameters:
points A Collection of n+1 points
segments A Collection of n segments
Returns: The index where they were added
Definition at line 268 of file EnvelopeLibrary.cpp.
References addEnvelope().
int EnvelopeLibrary::addEnvelope (Envelope * env)
This function adds an Envelope (passed by pointer) to the EnvelopeLibrary and returns the index at which it has been added.
Parameters:
env The new Envelope to add to the EnvelopeLibrary
Returns: The index of the new Envelope in the EnvelopeLibrary
Definition at line 260 of file EnvelopeLibrary.cpp.
References Collection< Envelope * >::add(), library, and Collection< Envelope * >::size().
Referenced by addEnvelope().
Envelope * EnvelopeLibrary::getEnvelope (int index)
This function returns a pointer to a new Envelope given an index to an existing EnvelopeLibrary, or NULL if index is out of range.
Note: This returns a clone of the env and not a pointer to the library object itself
Parameters:
index Which Envelope in the EnvelopeLibrary to find
Returns: A pointer to a COPY of the original envelope
Definition at line 250 of file EnvelopeLibrary.cpp.
References Collection< Envelope * >::get(), library, and Collection< Envelope * >::size().
int EnvelopeLibrary::loadLibrary (char * filename)
This function reads the Envelope library from a disk file.
Parameters:
filename The name of the file to read from
Returns: The number of entries in the library of -1 if unsucessful
Definition at line 153 of file EnvelopeLibrary.cpp.
References Collection< Envelope * >::add(), Collection< T >::add(), Collection< T >::clear(), CUBIC_SPLINE, EXPONENTIAL, FIXED, FLEXIBLE, interpolation_type, envelope_segment::interType, envelope_segment::length, envelope_segment::lengthType, library, LINEAR, m_time_type, Collection< Envelope * >::size(), stretch_type, xy_point::x, and xy_point::y.
EnvelopeLibrary & EnvelopeLibrary::operator= (EnvelopeLibrary & lib)
This is an overloaded assignment operator for EvelopeLibraries
Definition at line 62 of file EnvelopeLibrary.cpp.
References Collection< Envelope * >::add(), Collection< Envelope * >::get(), library, Collection< Envelope * >::remove(), and Collection< Envelope * >::size().
bool EnvelopeLibrary::saveLibrary (char * filename)
This function writes the Envelope library to a disk file.
Parameters:
filename The name of the file to write to
Return values:
true If successful
false If unsuccessful
Definition at line 80 of file EnvelopeLibrary.cpp.
References CUBIC_SPLINE, EXPONENTIAL, FLEXIBLE, Collection< Envelope * >::get(), library, LINEAR, size(), and Collection< Envelope * >::size().
void EnvelopeLibrary::showEnvelope (int index)
This function displays the indexed Envelope's contents using the standard output stream.
Parameters:
index The Envelope in the EvelopeLibrary to show
Definition at line 291 of file EnvelopeLibrary.cpp.
References Collection< Envelope * >::get(), library, and Collection< Envelope * >::size().
int EnvelopeLibrary::size ()
This function returns the number of envelopes existing in the EnvelopeLibrary
Returns: The number of envelopes
Definition at line 306 of file EnvelopeLibrary.cpp.
References library, and Collection< Envelope * >::size().
Referenced by saveLibrary().
bool EnvelopeLibrary::updateEnvelope (int index, Envelope * env)
This function updates the EnvelopeLibrary entry at the index with an Envelope (passed by pointer)
Parameters:
index Which Envelope in the EnvelopeLibrary to update
env A pointer to the new Envelope
Return values:
true Successful
false Unsuccessful (index out of range)
Definition at line 278 of file EnvelopeLibrary.cpp.
References library, Collection< Envelope * >::set(), and Collection< Envelope * >::size().
Member Data Documentation
Collection<Envelope *> EnvelopeLibrary::library [private]
This is a data structure to hold the library of envelopes.
Definition at line 152 of file EnvelopeLibrary.h.
Referenced by addEnvelope(), EnvelopeLibrary(), getEnvelope(), loadLibrary(), operator=(), saveLibrary(), showEnvelope(), size(), updateEnvelope(), and ~EnvelopeLibrary().
The documentation for this class was generated from the following files:
EnvelopeLibrary.h
EnvelopeLibrary.cpp