MultiTrack Class Reference
#include <MultiTrack.h>
Public Member Functions
MultiTrack ()
MultiTrack (int channels, m_sample_count_type numSamples, m_rate_type samplingRate)
MultiTrack (MultiTrack &mt)
MultiTrack & operator= (MultiTrack &mt)
~MultiTrack ()
void composite (MultiTrack &mt, m_time_type startTime=0)
Detailed Description
A MultiTrack is basically a collection of track pointers. When the MultiTrack object is deleted, it deletes each of the tracks in the collection. When it is copied or assigned, it copies the underlying objects. When tracks are removed or replaced, they are not deleted.
The idea is that copying entire MultiTrack objects should be covered, but editing elements in the MultiTrack objects should leave users to their own object management. Just remember, a MultiTrack owns a pointer when it is added to it.
Author: Braden Kowitz
Definition at line 50 of file MultiTrack.h.
Constructor & Destructor Documentation
MultiTrack::MultiTrack ()
This is the default constructor which creates a MultiTrack with 0 tracks.
Definition at line 38 of file MultiTrack.cpp.
MultiTrack::MultiTrack (int channels, m_sample_count_type numSamples, m_rate_type samplingRate)
This constructor creates an empty MultiTrack.
This is good for composition.
It also zeros out data if requested.
Parameters:
channels The number of channels
numSamples The number of samples
samplingRate The sampling rate
Definition at line 44 of file MultiTrack.cpp.
References Collection< Track * >::add(), m_rate_type, and m_sample_count_type.
MultiTrack::MultiTrack (MultiTrack & mt)
This is a copy Constructor.
Todo The argument should be const.
Parameters:
mt The MultiTrack to copy
Definition at line 60 of file MultiTrack.cpp.
References Collection< Track * >::add(), Iterator< T >::hasNext(), Collection< Track * >::iterator(), and Iterator< T >::next().
MultiTrack::~MultiTrack ()
This is a destructor.
Definition at line 91 of file MultiTrack.cpp.
References Collection< Track * >::clear(), Iterator< T >::hasNext(), Collection< Track * >::iterator(), and Iterator< T >::next().
Member Function Documentation
void MultiTrack::composite (MultiTrack & mt, m_time_type startTime = 0)
This composites another MultiTrack object on top of this one.
Any extra tracks are skipped (with warning).
startTime will offset the argument MultiTrack before compositing.
Definition at line 103 of file MultiTrack.cpp.
References Iterator< T >::hasNext(), Collection< Track * >::iterator(), m_time_type, and Iterator< T >::next().
Referenced by Score::render().
MultiTrack & MultiTrack::operator= (MultiTrack & mt)
This is an overloaded assignment operator.
Todo The argument should be const.
Parameters:
mt The MultiTrack to assign.
Returns: A MultiTrack
Definition at line 69 of file MultiTrack.cpp.
References Collection< Track * >::add(), Collection< Track * >::clear(), Iterator< T >::hasNext(), Collection< Track * >::iterator(), and Iterator< T >::next().
The documentation for this class was generated from the following files:
MultiTrack.h
MultiTrack.cpp