EnvelopeIterator Class Reference
#include <EnvelopeIterator.h>
Public Member Functions
EnvelopeIterator (Collection< Interpolator * > interpolators)
~EnvelopeIterator ()
EnvelopeIterator * clone ()
bool hasNext ()
m_value_type & next ()
Private Attributes
Collection< Interpolator * > * interpolators_
int iSegmentIndex_
Iterator< m_value_type > * currentIterator_
m_value_type currentValue_
bool moreValues_
long tempCounter_
Detailed Description
An iterator that interpolates over a Envelope. Since a Envelope acts like a single DynamicVariable, when we want to use it as such, we need a way to iterate through its value. That's what this does.
Author: Michael Aikins
Definition at line 48 of file EnvelopeIterator.h.
Constructor & Destructor Documentation
EnvelopeIterator::EnvelopeIterator (Collection< Interpolator * > interpolators)
This is the constructor which initalizes some basic values.
Parameters:
interpolators
Definition at line 37 of file EnvelopeIterator.cpp.
References currentIterator_, currentValue_, Collection< InterpolatorEntry >::get(), Collection< Interpolator * >::get(), interpolators_, iSegmentIndex_, moreValues_, Collection< InterpolatorEntry >::size(), Collection< Interpolator * >::size(), Collection< T >::size(), InterpolatorEntry::time_, and InterpolatorEntry::value_.
Referenced by clone().
EnvelopeIterator::~EnvelopeIterator ()
This is the Destructor.
Definition at line 81 of file EnvelopeIterator.cpp.
References currentIterator_, and interpolators_.
Member Function Documentation
EnvelopeIterator * EnvelopeIterator::clone () [virtual]
This makes a copy of this iterator.
Returns: A copy of this iterator.
Implements AbstractIterator< m_value_type >.
Definition at line 100 of file EnvelopeIterator.cpp.
References EnvelopeIterator().
bool EnvelopeIterator::hasNext () [virtual]
Indicate whether the iterator has another value to return.
Return values:
true If there is another value to return
false If there is not another value to return
Implements AbstractIterator< m_value_type >.
Definition at line 107 of file EnvelopeIterator.cpp.
References moreValues_.
m_value_type & EnvelopeIterator::next () [virtual]
Gets the next value in the iteration.
Note: Because this returns a reference type, value_ can be changed by the caller. Steps should be taken to prevent this (with a pass-to-caller member variable perhaps).
Returns: a reference to the next value in the iteration
Implements AbstractIterator< m_value_type >.
Definition at line 115 of file EnvelopeIterator.cpp.
References currentIterator_, currentValue_, Collection< Interpolator * >::get(), Iterator< m_value_type >::hasNext(), interpolators_, iSegmentIndex_, m_value_type, moreValues_, Iterator< m_value_type >::next(), Collection< Interpolator * >::size(), tempCounter_, and Interpolator::valueIterator().
Member Data Documentation
Iterator<m_value_type>* EnvelopeIterator::currentIterator_ [private]
This is the current DV iterator.
Definition at line 99 of file EnvelopeIterator.h.
Referenced by EnvelopeIterator(), next(), and ~EnvelopeIterator().
m_value_type EnvelopeIterator::currentValue_ [private]
This is the current value.
Definition at line 104 of file EnvelopeIterator.h.
Referenced by EnvelopeIterator(), and next().
Collection<Interpolator*>* EnvelopeIterator::interpolators_ [private]
This is a collection that holds the interpolators for all the segments.
Definition at line 89 of file EnvelopeIterator.h.
Referenced by EnvelopeIterator(), next(), and ~EnvelopeIterator().
int EnvelopeIterator::iSegmentIndex_ [private]
This is the current segment's index.
Definition at line 94 of file EnvelopeIterator.h.
Referenced by EnvelopeIterator(), and next().
bool EnvelopeIterator::moreValues_ [private]
This indicates whether we have more values.
Definition at line 109 of file EnvelopeIterator.h.
Referenced by EnvelopeIterator(), hasNext(), and next().
long EnvelopeIterator::tempCounter_ [private]
Definition at line 111 of file EnvelopeIterator.h.
Referenced by next().
The documentation for this class was generated from the following files:
EnvelopeIterator.h
EnvelopeIterator.cpp