CubicSplineInterpolator Class Reference
#include <InterpolatorTypes.h>
Public Member Functions
CubicSplineInterpolator ()
CubicSplineInterpolator * clone ()
Iterator< m_value_type > valueIterator ()
virtual interpolation_type getType ()
Detailed Description
This is a DynamicVariable that changes over time. This does cubic spline interpolation between a set of points ordered in time.
Author: Braden Kowitz
Philipp Fraund
Definition at line 117 of file InterpolatorTypes.h.
Constructor & Destructor Documentation
CubicSplineInterpolator::CubicSplineInterpolator ()
This is the default constructor.
Definition at line 195 of file InterpolatorTypes.cpp.
Referenced by clone().
Member Function Documentation
CubicSplineInterpolator * CubicSplineInterpolator::clone () [virtual]
This makes a clone of a CubicSplineInterpolator.
Returns: A new CubicSplineInterpolator
Implements Interpolator.
Definition at line 200 of file InterpolatorTypes.cpp.
References CubicSplineInterpolator().
interpolation_type CubicSplineInterpolator::getType () [virtual]
This provides an implementation to get the type of interpolator.
Returns: The interpolation type
Implements Interpolator.
Definition at line 267 of file InterpolatorTypes.cpp.
References CUBIC_SPLINE, and interpolation_type.
Iterator< m_value_type > CubicSplineInterpolator::valueIterator () [virtual]
This creates an iterator over CubicSplineInterpolators.
Returns: An iterator
Implements Interpolator.
Definition at line 209 of file InterpolatorTypes.cpp.
References InterpolatorIterator::append(), Collection< InterpolatorEntry >::get(), DynamicVariable::getDuration(), DynamicVariable::getSamplingRate(), Iterator< T >::hasNext(), Collection< InterpolatorEntry >::iterator(), m_sample_count_type, m_time_type, m_value_type, Iterator< T >::next(), Collection< InterpolatorEntry >::size(), Collection< InterpolatorEntry >::sortCollection(), InterpolatorEntry::time_, and InterpolatorEntry::value_.
The documentation for this class was generated from the following files:
InterpolatorTypes.h
InterpolatorTypes.cpp