AuWriter Class Reference
#include <AuWriter.h>
Static Public Member Functions
bool write (SoundSample &ss, string filename)
bool write (Track &t, string filename)
bool write (MultiTrack &mt, string filename)
bool write_one_per_track (MultiTrack &mt, char *filename,...)
Static Private Member Functions
bool write (vector< SoundSample * > &channels, string filename)
void WriteIntMsb (ostream &out, long l, int size)
Detailed Description
Writes out SoundSample, Track, and MultiTrack objects to an AU file. All files are written as 16 bits.
Author: Braden Kowitz
Definition at line 46 of file AuWriter.h.
Member Function Documentation
bool AuWriter::write (vector< SoundSample * > & channels, string filename) [static, private]
This write the channels of a SoundSample out as an AU file
Parameters:
channels A vector of SoundSamples to write out
filename The name of the file to write out to
Return values:
true On success
false On failure
Definition at line 89 of file AuWriter.cpp.
References m_rate_type, m_sample_count_type, m_sample_type, m_time_type, and WriteIntMsb().
bool AuWriter::write (MultiTrack & mt, string filename) [static]
This writes a MultiTrack object out as an AU file.
Note: Some systems may not correctly read AU files with more than 2 tracks. Try converting the file to another format if you have issues (tool: SOX, sound exchange)
Parameters:
mt The MultiTrack to write out
filename The name of the file to write out to
Return values:
true On success
false On failure
Definition at line 52 of file AuWriter.cpp.
References Iterator< T >::hasNext(), Collection< Track * >::iterator(), Iterator< T >::next(), and write().
bool AuWriter::write (Track & t, string filename) [static]
This writes a Track object out as an AU file.
Parameters:
t The Track to write out
filename The name of the file to write out to
Return values:
true On success
false On failure
Definition at line 43 of file AuWriter.cpp.
References Track::getWave(), and write().
bool AuWriter::write (SoundSample & ss, string filename) [static]
This writes a SoundSample object out as an AU file.
Parameters:
ss The SoundSample to write out
filename The name of the file to write out to
Return values:
true On success
false On failure
Definition at line 35 of file AuWriter.cpp.
Referenced by write(), and write_one_per_track().
bool AuWriter::write_one_per_track (MultiTrack & mt, char * filename, ...) [static]
This writes the individual Tracks in a MultiTrack to a set of filenames specified.
Parameters:
mt The MultiTrack to write out
filename A pointer to an array holding the names of the files to write out to
Return values:
true On success
false On failure
Definition at line 66 of file AuWriter.cpp.
References Iterator< T >::hasNext(), Collection< Track * >::iterator(), Iterator< T >::next(), and write().
void AuWriter::WriteIntMsb (ostream & out, long l, int size) [inline, static, private]
Todo Recursive inlining? This is insane. This needs to be reworked.
Definition at line 218 of file AuWriter.cpp.
Referenced by write().
The documentation for this class was generated from the following files:
AuWriter.h
AuWriter.cpp