High Class Reference
#include <high.h>
Public Member Functions
High (float aStartTime, float aDuration, int aType, char *aName)
High (const High &origHigh)
~High ()
High & operator= (const High &origHigh)
void clear ()
void Print ()
Protected Attributes
double highDensity
Constructor & Destructor Documentation
High::High (float aStartTime, float aDuration, int aType, char * aName)
Definition at line 43 of file high.cpp.
References Event::aName, bottomID, highID, lowID, Event::setDensity(), Event::setDuration(), Event::setName(), Event::setStartTime(), and Event::setType().
High::High (const High & origHigh)
Definition at line 77 of file high.cpp.
References bottomID, and highID.
High::~High ()
Definition at line 90 of file high.cpp.
Member Function Documentation
void High::clear () [virtual]
Clears several internal structures in the Event(p.): nameType, maxTypes, layerDens, objsInLayer, remainObjs, typesInLayer, starTarray, probSieveArray, durArray, probDurArray
Reimplemented from Event (p.).
Definition at line 101 of file high.cpp.
High& High::operator= (const High & origHigh)
void High::Print () [virtual]
Reimplemented from Event (p.).
Definition at line 110 of file high.cpp.
References highID, outputFile, Event::theDuration, Event::theName, Event::theStartTime, and Event::uPerSec.
Member Data Documentation
double High::highDensity [protected]
Definition at line 37 of file high.h.
The documentation for this class was generated from the following files:
high.h
high.cpp