DataIn Class Reference
#include <dataIn.h>
Public Member Functions
DataIn (char *)
DataIn (int)
DataIn ()
~DataIn ()
void clear ()
void ReadTags (int size)
void ReadDummies ()
void ReadCharArray ()
void GenInts (int size)
void GenFloats (int size)
void GenChars (int size)
void ReadInts (int)
void ReadVarInts (int, int)
void ReadFloats (int)
void ReadFLong (int)
void ReadArray (int)
void ReadChars (int)
void ReadChars2 (int)
void openFile (char *)
void closeFile ()
void rewindFile (long loc)
long fileLoc ()
void RememberFileLoc (int posNum, char *fileName, long &location)
void Skip (int size)
void ReadBuffer ()
Public Attributes
int intVect [100]
int gIntVect [100]
float floatVect [100]
float gFloatVect [100]
long longVect [100]
char buffer [80]
char dummy [30]
char cAr [30]
char tag
int arraySize
int nameSize
int pieceLength
long loc
double * array
char * fileName
char lib_file [10]
char ** nameOf
char ** nameOf2
Static Public Attributes
ifstream * inputFile = NULL
Private Member Functions
void setFileName (char *)
Constructor & Destructor Documentation
DataIn::DataIn (char *)
Definition at line 42 of file dataIn.cpp.
References array, fileName, inputFile, nameOf, openFile(), and setFileName().
DataIn::DataIn (int)
Definition at line 61 of file dataIn.cpp.
References array, and nameOf.
DataIn::DataIn ()
Definition at line 73 of file dataIn.cpp.
References array, fileName, fileName, inputFile, nameOf, and setFileName().
DataIn::~DataIn ()
Definition at line 94 of file dataIn.cpp.
References array, clear(), inputFile, loc, and nameOf.
Member Function Documentation
void DataIn::clear ()
Definition at line 108 of file dataIn.cpp.
References array, nameOf, and nameSize.
Referenced by ~DataIn().
void DataIn::closeFile ()
Definition at line 158 of file dataIn.cpp.
References inputFile.
Referenced by openFile().
long DataIn::fileLoc ()
Definition at line 181 of file dataIn.cpp.
References inputFile.
Referenced by EnvelopeBuilder(), Event::NumObjs(), and RememberFileLoc().
void DataIn::GenChars (int size)
Definition at line 281 of file dataIn.cpp.
References inputFile, nameOf, and nameSize.
Referenced by CharSequence().
void DataIn::GenFloats (int size)
Definition at line 245 of file dataIn.cpp.
References gFloatVect, and inputFile.
Referenced by Sequence().
void DataIn::GenInts (int size)
Definition at line 263 of file dataIn.cpp.
References gIntVect, and inputFile.
Referenced by EnvelopeBuilder(), Patter::GetPatty(), and Patter::InitPat().
void DataIn::openFile (char *)
Definition at line 141 of file dataIn.cpp.
References closeFile(), fileName, and inputFile.
Referenced by DataIn(), and RememberFileLoc().
void DataIn::ReadArray (int)
Definition at line 385 of file dataIn.cpp.
References array, dummy, and inputFile.
void DataIn::ReadBuffer ()
Definition at line 476 of file dataIn.cpp.
References buffer, and inputFile.
Referenced by Patter::Recorder().
void DataIn::ReadCharArray ()
Definition at line 220 of file dataIn.cpp.
References cAr, dummy, and inputFile.
void DataIn::ReadChars (int)
Definition at line 426 of file dataIn.cpp.
References dummy, inputFile, nameOf, and nameSize.
Referenced by Patter::Chooser(), Event::CopyName(), Patter::Delivery(), Event::DurationMethods(), Patter::Expand(), Event::NumObjs(), Patter::Nursery(), Event::PointsProbs(), and Event::Sweep3().
void DataIn::ReadChars2 (int)
Definition at line 444 of file dataIn.cpp.
References dummy, inputFile, nameOf2, and nameSize.
void DataIn::ReadDummies ()
Definition at line 208 of file dataIn.cpp.
References cAr, and inputFile.
Referenced by Event::CopyName(), Patter::Delivery(), Event::DurationMethods(), Patter::GetPatty(), Event::LayerDef(), Event::NumObjs(), Patter::Nursery(), and Event::PointsProbs().
void DataIn::ReadFloats (int)
Definition at line 342 of file dataIn.cpp.
References dummy, floatVect, and inputFile.
Referenced by Event::PointsProbs().
void DataIn::ReadFLong (int)
Definition at line 364 of file dataIn.cpp.
References dummy, inputFile, and longVect.
void DataIn::ReadInts (int)
Definition at line 304 of file dataIn.cpp.
References dummy, inputFile, and intVect.
Referenced by CharSequence(), Event::CopyName(), Patter::Equivalence(), Patter::GetPatty(), Patter::InitPat(), Event::LayerDef(), Patter::Nursery(), Event::PointsProbs(), Sequence(), and Event::Stimes().
void DataIn::ReadTags (int size)
Definition at line 232 of file dataIn.cpp.
References inputFile, and tag.
void DataIn::ReadVarInts (int, int)
Definition at line 323 of file dataIn.cpp.
References dummy, inputFile, and intVect.
void DataIn::RememberFileLoc (int positionNum, char * fileName, long & location)
RememberFileLocation.
Definition at line 191 of file dataIn.cpp.
References fileLoc(), fileName, openFile(), and rewindFile().
void DataIn::rewindFile (long loc)
Definition at line 171 of file dataIn.cpp.
References inputFile.
Referenced by EnvelopeBuilder(), Event::NumObjs(), Patter::Recorder(), and RememberFileLoc().
void DataIn::setFileName (char *) [private]
Definition at line 131 of file dataIn.cpp.
References fileName.
Referenced by DataIn().
void DataIn::Skip (int size)
Definition at line 462 of file dataIn.cpp.
References buffer, and inputFile.
Referenced by Patter::GetPatty().
Member Data Documentation
double* DataIn::array
Definition at line 80 of file dataIn.h.
Referenced by clear(), DataIn(), ReadArray(), and ~DataIn().
int DataIn::arraySize
Definition at line 76 of file dataIn.h.
char DataIn::buffer[80]
Definition at line 71 of file dataIn.h.
Referenced by ReadBuffer(), Patter::Recorder(), and Skip().
char DataIn::cAr[30]
Definition at line 73 of file dataIn.h.
Referenced by ReadCharArray(), and ReadDummies().
char DataIn::dummy[30]
Definition at line 72 of file dataIn.h.
Referenced by ReadArray(), ReadCharArray(), ReadChars(), ReadChars2(), ReadFloats(), ReadFLong(), ReadInts(), and ReadVarInts().
char* DataIn::fileName
Definition at line 82 of file dataIn.h.
Referenced by DataIn(), and setFileName().
float DataIn::floatVect[100]
Definition at line 68 of file dataIn.h.
Referenced by Event::PointsProbs(), and ReadFloats().
float DataIn::gFloatVect[100]
Definition at line 69 of file dataIn.h.
Referenced by GenFloats(), and Sequence().
int DataIn::gIntVect[100]
Definition at line 67 of file dataIn.h.
Referenced by EnvelopeBuilder(), GenInts(), Patter::GetPatty(), and Patter::InitPat().
ifstream * DataIn::inputFile = NULL [static]
Definition at line 34 of file dataIn.cpp.
Referenced by closeFile(), DataIn(), fileLoc(), GenChars(), GenFloats(), GenInts(), openFile(), ReadArray(), ReadBuffer(), ReadCharArray(), ReadChars(), ReadChars2(), ReadDummies(), ReadFloats(), ReadFLong(), ReadInts(), ReadTags(), ReadVarInts(), rewindFile(), Skip(), and ~DataIn().
int DataIn::intVect[100]
Definition at line 66 of file dataIn.h.
Referenced by CharSequence(), Event::CopyName(), Patter::Equivalence(), Patter::GetPatty(), Patter::InitPat(), Event::LayerDef(), Patter::Nursery(), Event::PointsProbs(), ReadInts(), ReadVarInts(), Sequence(), and Event::Stimes().
char DataIn::lib_file[10]
Definition at line 83 of file dataIn.h.
long DataIn::loc
Definition at line 79 of file dataIn.h.
Referenced by ~DataIn().
long DataIn::longVect[100]
Definition at line 70 of file dataIn.h.
Referenced by ReadFLong().
char** DataIn::nameOf
Definition at line 84 of file dataIn.h.
Referenced by CharSequence(), Patter::Chooser(), clear(), Event::CopyName(), DataIn(), Patter::Delivery(), Event::DurationMethods(), Patter::Expand(), GenChars(), Event::NumObjs(), Patter::Nursery(), Event::PointsProbs(), ReadChars(), Event::Sweep3(), and ~DataIn().
char** DataIn::nameOf2
Definition at line 85 of file dataIn.h.
Referenced by ReadChars2().
int DataIn::nameSize
Definition at line 77 of file dataIn.h.
Referenced by clear(), GenChars(), ReadChars(), and ReadChars2().
int DataIn::pieceLength
Definition at line 78 of file dataIn.h.
char DataIn::tag
Definition at line 74 of file dataIn.h.
Referenced by ReadTags().
The documentation for this class was generated from the following files:
dataIn.h
dataIn.cpp